### ISSUE TITLE
Iphone SE, Galaxy Fold,  Galaxy S5 Responsive Issue📱

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#1014]
On these devices, the responsiveness issues are there a sample screenshot is attached below👇
 Avoid Overflow of text and widgets

![image](https://user-images.githubusercontent.com/40017559/120124044-d02e0500-c1cf-11eb-9457-c2011f9cd681.png)
![image](https://user-images.githubusercontent.com/40017559/120124050-db813080-c1cf-11eb-998e-613a0cce9766.png)

**Comment by ashuvssut** [comment]
i want to work on this
