### ISSUE TITLE
Set up Pre-Commit Hooks

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#1016]
Use Husky

Reference(s):

- [1](https://dev.to/botreetechnologies/setting-up-husky-pre-commit-hook-with-eslint-prettier-and-lint-staged-for-react-and-react-native-d05) # Read the comments as well for getting around some possible errors
- [2](https://markoskon.com/create-a-pre-commit-hook-with-husky-and-lint-staged/)

**Comment by ashuvssut** [comment]
I want to work on this
