### ISSUE TITLE
Major Bug in Editor Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#1043]
![Bug_in_editor_page](https://user-images.githubusercontent.com/46641503/120498584-f5439300-c3dc-11eb-9403-aa0e2bcd2765.png)

Due to some recent PRs, the functioning of the editor page is broken. From entering text to saving the file, nothing is accessible

**Comment by sparshsharma2510** [comment]
I want to work on this issue. Kindly assign it to me.
