### ISSUE TITLE
Adding login page

### ISSUE THREAD

**Issue by PranavChauhan22** [smaranjitghose/doc2pen#1047]
I want to design login page in the site so that the verified user can only use the services provided in order to maintain security check on the website.
I will take care that the color schema of the website is maintained.
The login page will contain cool animations,dynamic as well as static content.

Please assign me this issue under lgm-soc participant.

**Comment by smaranjitghose** [comment]
We want the end-user experience to be simple without having to ever enter any identifiable information or see any ads.
