### ISSUE TITLE
Night mOde

### ISSUE THREAD

**Issue by SanjeevKumar22** [smaranjitghose/doc2pen#1048]
add dark mode and footer design

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by SanjeevKumar22** [comment]
> Please assign me this issue under LGMSOC'21

**Comment by smaranjitghose** [comment]
We are not having any plans to shift to dark mode since achieving that for the editor and sketch page would require a lot of effort in terms of UI
