### ISSUE TITLE
Improve navigation bar 

### ISSUE THREAD

**Issue by tjanhvi** [smaranjitghose/doc2pen#1049]

**Comment by tjanhvi** [comment]
Please assign me this issue

**Comment by smaranjitghose** [comment]
@tjanhvi Please elaborate on the issue. What are your proposals for improvement? Perhaps attach some screenshots to make your ideas more visually understandable. Please avoid raising issues without a PR description. Since this is your first time, I am open to giving you the opportunity to rectify it.

**Comment by tjanhvi** [comment]
> @tjanhvi Please elaborate on the issue. What are your proposals for improvement? Perhaps attach some screenshots to make your ideas more visually understandable. Please avoid raising issues without a PR description. Since this is your first time, I am open to giving you the opportunity to rectify it.

Thank you sir for giving me chance to rectifying it, I just want to make the navigation bar's menu at more distance and below the heading "Doc2pen"  so that it looks better n highlights each and every menu in a proper manner and looks good, Hope you got my point, sir.

**Comment by tusharnankani** [comment]
Any updates? @tjanhvi

**Comment by vedant-jain03** [comment]
@smaranjitghose I have one reference   [ref](https://codepen.io/alvic/pen/eVWMYj)
I am thinking of giving a transparent theme
Left side: logo
Right side: buttons
text color: white
hover color : theme blue and bg white

**Comment by smaranjitghose** [comment]
We have to alter the remaining theme for incorporating it.
