### ISSUE TITLE
File Converter has no preview for PDF's

### ISSUE THREAD

**Issue by Rutuj-Runwal** [smaranjitghose/doc2pen#1050]
**The file converter shows a broken image when pdf's are uploaded.**

![Screenshot (2174)](https://user-images.githubusercontent.com/59436520/121639043-8edc0600-caa9-11eb-8388-75f706caf547.png)

Proposition:

- Add a default image for pdf's so that users get a better experience 
OR
- Show preview of the 1st page of the pdf as image

The latter would be harder to implement and could be problematic for large file sizes so, I could add a default image.

**Comment by smaranjitghose** [comment]
Currently we don't have a PDF to X functionality. If you want you can work on a PDF splitter and PDF merger functionality

**Comment by Rutuj-Runwal** [comment]
Yaa I know PDF to X is not supported currently but PDF merger is happening.I could work on that too.Plus, as I mentioned above about the broken preview...

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on this.
