### ISSUE TITLE
Fix some parts of webpage by making it responsive

### ISSUE THREAD

**Issue by SNEHAL311998** [smaranjitghose/doc2pen#1051]
![doc2pen](https://user-images.githubusercontent.com/61999845/121661674-133a8300-cac2-11eb-8f5d-79b31eed3c73.JPG)
![doc2pen2](https://user-images.githubusercontent.com/61999845/121662047-82b07280-cac2-11eb-8102-4a458ec7b216.JPG)
<br>
### Here image and the content in the card are overflowing on mobile view. I would like to fix this problem. Please assign me

**Comment by smaranjitghose** [comment]
@SNEHAL311998 

- Nice work figuring out the bug 🌟
- Whenever you report a responsiveness issue, please be specific about the screen size or the default model type. For example, I can see that this issue occurs in the iPhone xe/5 models.
- You are assigned this with a deadline of 3 days from today

**Comment by SNEHAL311998** [comment]
Thank you for assigning.Sorry for the late reply since I was not well for two days.

**Comment by tusharnankani** [comment]
Will you be working on this?  @SNEHAL311998

**Comment by SNEHAL311998** [comment]
No @tusharnankani you can go ahead. If you need help do let me know

**Comment by vedant-jain03** [comment]
I want to work on the responsive

**Comment by smaranjitghose** [comment]
> I want to work on the responsive

Raise a new issue for this and start working on that
