### ISSUE TITLE
Add project as a part of LGM-SOC'21

### ISSUE THREAD

**Issue by ishitakapoor26** [smaranjitghose/doc2pen#1054]
Add project as a part of LGM-SOC'21 section.

**Comment by ishitakapoor26** [comment]
@smaranjitghose pls assign this issue to me.

**Comment by smaranjitghose** [comment]
> @smaranjitghose pls assign this issue to me.

Avoid writing these messages

**Comment by smaranjitghose** [comment]
> Add project as a part of LGM-SOC'21 section.

Please elaborate

**Comment by ishitakapoor26** [comment]
> > Add project as a part of LGM-SOC'21 section.
> 
> Please elaborate

I want to add LGM-SOC'21 label in open source program section which would redirect to LGM-SOC website.

**Comment by smaranjitghose** [comment]
Not required for now
