### ISSUE TITLE
Input area in the editor does not supports 'Tab' key.

### ISSUE THREAD

**Issue by prathamjagga** [smaranjitghose/doc2pen#1074]
Issue: When we press Tab key, in the input area on '/editor' page, it moves to the next field, instead 'a few spaces' must be indented for the user's accessibility.

Actual behavior: Pressing the 'Tab' key, moves control to the next field.
Expected behavior: Pressing the 'Tab' key should provide indentation (a bunch of spaces) as other editors support.
Steps to reproduce : (1) Go to '/editor' from the root (home-page).
(2) Press the 'Tab' key on your keyboard.

Additional info: 
Machine: Windows 10 x64 arch.
Node Version: 14.17.0

**Comment by smaranjitghose** [comment]
Would you like to resolve this bug?

**Comment by prathamjagga** [comment]
@smaranjitghose Sir, the issue is solved kindly review the PR #1075
