### ISSUE TITLE
Idea - Change icon to more user friendly.

### ISSUE THREAD

**Issue by CodingSpecies** [smaranjitghose/doc2pen#1077]
For those who put their browsers on dark mode, the icon is not so visible, so I have an idea to change it:

## Right Now:
![image](https://user-images.githubusercontent.com/70807500/128359523-97a2d161-93b0-4df9-9f4f-118be4242a2a.png)

## Icon to replace:

[icon link](https://www.flaticon.com/free-icon/contract_684930)

## Preview:

![image](https://user-images.githubusercontent.com/70807500/128359702-7dcaecc4-6f99-4858-84c1-c180991b81e8.png)

**Comment by smaranjitghose** [comment]
This is a fantastic proposal for the UI.

Make sure to test the favicon on all pages
