### ISSUE TITLE
Adding a Footer 

### ISSUE THREAD

**Issue by sameersrivastava13** [smaranjitghose/doc2pen#110]
# Description:

Currently there is no Footer at the bottom of the page. Therefore i would like to add a footer using [materializecss](https://materializecss.com/footer.html)

# Screenshots:

![Screenshot (73)](https://user-images.githubusercontent.com/56088741/91183910-acea9c80-e709-11ea-880c-3878a84cd065.png)

**Comment by sameersrivastava13** [comment]
Please assign me this issue. @anushbhatia @smaranjitghose

**Comment by himanshujaidka** [comment]
@sameersrivastava13 I have already make an issue and I have already added it

**Comment by imPGupta** [comment]
I also want to contribute on footer.

**Comment by sameersrivastava13** [comment]
> @sameersrivastava13 I have already make an issue and I have already added it

Actually i can't see any footer in the web application that's why i created this issue. I remember the footer was there but i guess someone removed that.
that's why i asked if footer is to be added then i can work on it.

**Comment by himanshujaidka** [comment]
yes, I made PR once again, if my PR will merge then you could add links on that actually that footer is incomplete. @sameersrivastava13

**Comment by sameersrivastava13** [comment]
> yes, I made PR once again, if my PR will merge then you could add links on that actually that footer is incomplete. @sameersrivastava13

Sure.
