### ISSUE TITLE
Contact Page not found

### ISSUE THREAD

**Issue by kmlhsn** [smaranjitghose/doc2pen#118]
1. Go to https://doc2pen.smaranjitghose.codes/ or run app from your local machine
2. Click on contact on top nav bar

Description:
when I click on contact, it shows "Oops! Page not Found." 

Expectation:
when I click on contact, it should show a contact page

![image](https://user-images.githubusercontent.com/32615215/91639354-c5272800-ea37-11ea-88dd-d941158d1505.png)

**Comment by yashaswibiyahut** [comment]
I would like to work on this issue but there is no contact option on the top of nav bar. 
Explain and assign me to do this as a part of Hakin codes @kmlhsn

**Comment by anushbhatia** [comment]
Comment on the contact page directly I will assign you the project
