### ISSUE TITLE
No Footer

### ISSUE THREAD

**Issue by kmlhsn** [smaranjitghose/doc2pen#119]
1.  Go to https://doc2pen.smaranjitghose.codes/ or run app from your local machine
2. Click on "Editor" on top nav bar

Description:
There is no Footer on "Editor" page

Expectation:
There should have footer
![image](https://user-images.githubusercontent.com/32615215/91639511-dde40d80-ea38-11ea-962e-d0a2138c44f4.png)

**Comment by himanshujaidka** [comment]
@kmlhsn please refer to previous issues before opening a new one, already discussed and assigned
