### ISSUE TITLE
Different color option is missing

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#123]
![Screenshot (62)](https://user-images.githubusercontent.com/58654018/91683346-fc015900-eb71-11ea-8564-6d6e9912a34e.png)
# Description:

# Screenshots:

**Comment by himanshujaidka** [comment]
? @smaranjitghose

**Comment by smaranjitghose** [comment]
> ? @smaranjitghose

Yes. You want to fix the bug for missing option of pen color?

**Comment by himanshujaidka** [comment]
yes
