### ISSUE TITLE
Page Speed

### ISSUE THREAD

**Issue by Aniruddhmuley2001** [smaranjitghose/doc2pen#124]
# Description:
The page speed of the website is good, but has a pretty good chance of improvement. General points on this are the format of the introductory video and general code practices. The detailed report is given below, with individual analysis for mobile and desktop.

Desktop: 
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdoc2pen.smaranjitghose.codes%2F&tab=desktop

Mobile: 
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdoc2pen.smaranjitghose.codes%2F&tab=mobile

**Comment by Aniruddhmuley2001** [comment]
I would like to work on this issue.

**Comment by anushbhatia** [comment]
Go ahead with it. Mention the changes you have made and the enhanced website's pagespeed when making a PR.
