### ISSUE TITLE
Contribution.md FIle

### ISSUE THREAD

**Issue by ritiksoni00** [smaranjitghose/doc2pen#126]
it is need ithink?? @smaranjitghose

**Comment by ritiksoni00** [comment]
IT WILL NEED SOME CHANGES IN README TOO..

**Comment by ritiksoni00** [comment]
@anushbhatia

**Comment by ashishnagpal2498** [comment]
Kindly explain in brief, what all changes you have to make.

**Comment by ritiksoni00** [comment]
like remove CoDe of conduct text in Readme And link This file with some instructions
