### ISSUE TITLE
PR template needed

### ISSUE THREAD

**Issue by rutujadhanawade** [smaranjitghose/doc2pen#128]
# Description:

-  There is no PR template right now.
-  I want to create a custom PR template so that Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.

Please assign this to me as a part of CH20

**Comment by rutujadhanawade** [comment]
Please assign this issue to me @anushbhatia .
And add proper labels to it.

**Comment by anushbhatia** [comment]
Explain the procedure and what all features are you going to include in this. So that I can recommend changes right now only

**Comment by rutujadhanawade** [comment]
I want to create something like this 👇

#### Description

 #### Checklist

 - [ ] I've read the contribution guidelines.
- [ ] This PR mets all the requirements like Clean Code, proper README and Documentation

 #### Related Issues or Pull Requests

 (Write your answer here.)

 #### Screenshots (if any)

  Original           | Updated
 :--------------------: |:--------------------:

**Comment by anushbhatia** [comment]
go ahead and ask for suggestions form @smaranjitghose regarding this.
