### ISSUE TITLE
[Bug]Two instances of Navbar are present in the editor section of the website

### ISSUE THREAD

**Issue by AdityaJ7** [smaranjitghose/doc2pen#132]
# Description
There are two instances of navbar present in the editor section of the website which can be checked [here](https://doc2pen.smaranjitghose.codes/editor.html)

## Screenshot

![bug](https://user-images.githubusercontent.com/42397096/92345659-d3d0a780-f0e7-11ea-887c-79bbd03e91ab.png)

## Possible Fix

Remove the lower navbar.

**Comment by smaranjitghose** [comment]
![screen_menu](https://user-images.githubusercontent.com/46641503/92348887-0e3f4200-f0f2-11ea-81ef-a4d594d191f4.jpg)
This should be the layout. Two menu bars above the input and output screens

**Comment by AdityaJ7** [comment]
@anushbhatia I guess this issue has been addressed in  PR  #125
