### ISSUE TITLE
[Bug]The Bug Report Template doesn't shows up when opening a new issue

### ISSUE THREAD

**Issue by AdityaJ7** [smaranjitghose/doc2pen#133]
# Description

So when I created an issue there was no option to choose a bug report template though I can see a bug report template is present in the ISSUE TEMPLATES folder of this repo.

## Screenshot 
![bug2](https://user-images.githubusercontent.com/42397096/92346454-7722bc00-f0ea-11ea-9991-868482913bd4.png)

## Possible fix

Maybe the bug report template hasn't been linked properly so we can check that out.

**Comment by smaranjitghose** [comment]
For now, we are avoiding using any bug or feature templates for PRs or issue
