### ISSUE TITLE
Addition of pro features

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#149]
We have to add some pro features and when user wants to use them then they have to log in, so we have to link database with it

**Comment by smaranjitghose** [comment]
> We have to add some pro features and when user wants to use them then they have to log in, so we have to link database with it

That's a good idea, but I would love to keep this project free and open source so that we as students can make use of it without any hassle

**Comment by himanshujaidka** [comment]
Make this open source but, I think login feature is good so that we count the number of students and make a contact with them to improve us

**Comment by smaranjitghose** [comment]
> Make this open source but, I think login feature is good so that we count the number of students and make a contact with them to improve us

A contact form is already there for feedback. Since this is not a commercial project, spamming people for feedback would drive them away
