### ISSUE TITLE
Implement Word Count feature as required

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#183]
Refer [this](https://github.com/smaranjitghose/doc2pen/issues/137)

**Comment by mharshita** [comment]
@smaranjitghose @anushbhatia I want to work on this issue

**Comment by himanshujaidka** [comment]
pls assign this to me as I have code of this

**Comment by himanshujaidka** [comment]
and previously I am woked on this issue 😕

**Comment by himanshujaidka** [comment]
@smaranjitghose pls have a look at it, or we could do one thing that I will implement the logic and @mharshita will improve the UI of it?

**Comment by smaranjitghose** [comment]
> @smaranjitghose pls have a look at it, or we could do one thing that I will implement the logic and @mharshita will improve the UI of it?

If you are taking the issue you are expected to complete it and not leave the rest of the work for another mentee

**Comment by himanshujaidka** [comment]
I am saying this because you have already assigned this issue to her but previously I have done that, 😅

**Comment by smaranjitghose** [comment]
> I am saying this because you have already assigned this issue to her but previously I have done that, 😅

That was for the previous version and it did not meet the requirements of the current one.
Even I have made the entire editor myself for the initial project but now we are revamping it

**Comment by himanshujaidka** [comment]
okay
