### ISSUE TITLE
Add Option to upload document, read text from it and render handwriting

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#186]

**Comment by paraschhugani** [comment]
@smaranjitghose  i would like to contribute to this issue, To be sure i have to also make the js functionality or just the front-end part.

**Comment by smaranjitghose** [comment]
> @smaranjitghose i would like to contribute to this issue, To be sure i have to also make the js functionality or just the front-end part.

The JS Functionality along with frontend is expected

**Comment by paraschhugani** [comment]
@smaranjitghose i successfully made a document upload and able to read file txt from it and printing it in textarea below ,, can you just guide me what function to be called to update the handwriting.

<img width="1438" alt="Screenshot 2020-10-05 at 1 46 24 AM" src="https://user-images.githubusercontent.com/51089028/95026207-57f95900-06ad-11eb-8265-f03118d5c1cb.png">
