### ISSUE TITLE
Add Option for Adding Sketches/Images to the Document

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#188]

**Comment by sahebsunny** [comment]
I want to work on it if you can assign this issue to me for DWOC.
I can add Images and drawing on canvas.

**Comment by shreyasY2k** [comment]
@smaranjitghose Could u please assign this to me? Can you tell me in brief as to how the uploaded image should look like? Should it be b/w version of uploaded image? (DWOC)

**Comment by smaranjitghose** [comment]
> @smaranjitghose Could u please assign this to me? Can you tell me in brief as to how the uploaded image should look like? Should it be b/w version of uploaded image? (DWOC)

It function the same way as we do it in Google Docs or Microsoft word. Actually, keeping the image as it is would save a lot of trouble

**Comment by shreyasY2k** [comment]
ok then i would like to work on it could u please assign it to me?

**Comment by shreyasY2k** [comment]
I'm working on it. Will send PR asap. As asked in discord is it ok to change the textarea tag to a div with content editable property? Bevat if i do that the functioning of whole app wil change

**Comment by sahebsunny** [comment]
@shreyasY2k I tried it 
I changed the textarea tag to a div with content editable

**Comment by shreyasY2k** [comment]
@sahebsunny yes i too did it. It will work for the input side. But for output bock the canvas of p5 has only text function and a imageUpload function whish takes only single image. That is what we're using for type of page. But to place an image on an image? I have no idea.

**Comment by sahebsunny** [comment]
> @sahebsunny yes i too did it. It will work for the input side. But for output bock the canvas of p5 has only text function and a imageUpload function whish takes only single image. That is what we're using for type of page. But to place an image on an image? I have no idea.

Yes that's the issue
