### ISSUE TITLE
Improve the Menubar UI in the Editor Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#189]

**Comment by ymaheshwari1** [comment]
@smaranjitghose  Do we have any file to take reference from?

**Comment by smaranjitghose** [comment]
> @smaranjitghose Do we have any file to take reference from?

@anushbhatia can help you out with that

**Comment by ymaheshwari1** [comment]
@smaranjitghose I am interested.

**Comment by paraschhugani** [comment]
@smaranjitghose i am interested , should i change only the frontend or make js functionality which keeps on updating the word count as you keep typing along ?

**Comment by smaranjitghose** [comment]
> @smaranjitghose i am interested , i would be start with some Neumorphism effect , i think that will easily differ the Menubar

Awesome! Also, note that the current menubar is made like another navbar and looks pretty weird in the mobile view. We need to change it as well
