### ISSUE TITLE
Contributor's Section

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#191]
- Ensure all the contributors so far have been added
- Some of the contributors towards the end have their pictures and named swapped. Please fix those by checkout out their GitHub profiles

**Comment by rutujadhanawade** [comment]
I would like to work on this. Can you add the CH20 label and relevant difficulty tag on it?

**Comment by smaranjitghose** [comment]
In the main.js, make the following changes in the contributor section variable

- title --> Name
- image --> Profile Picture
- Githublink --> Github Handle
