### ISSUE TITLE
Improve Contact Form UI

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#192]
Required Fields:
- First Name
- Last Name
- Email ID
- Message

Optional Fields:
- Rating ( 1 to 10 slider)
- Phone Number

**Comment by AyuSoni25** [comment]
I'll do it @smaranjitghose

**Comment by dipanshparmar** [comment]
@smaranjitghose if no one is working on this then I'll do it. You can assign me this issue.

**Comment by smaranjitghose** [comment]
> @smaranjitghose if no one is working on this then I'll do it. You can assign me this issue.

Please have a look the feedback [here](https://github.com/smaranjitghose/doc2pen/pull/263) before you start making changes

**Comment by dipanshparmar** [comment]
> > @smaranjitghose if no one is working on this then I'll do it. You can assign me this issue.
> 
> Please have a look the feedback [here](https://github.com/smaranjitghose/doc2pen/pull/263) before you start making changes

@smaranjitghose Yeah! I got this.
