### ISSUE TITLE
Contribute new fonts built from actual handwritings

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#193]

**Comment by himanshujaidka** [comment]
I want to add font of mine

**Comment by himanshujaidka** [comment]
@smaranjitghose how to convert handwriting to a particular font, earlier you have told about some software?

**Comment by smaranjitghose** [comment]
> @smaranjitghose how to convert handwriting to a particular font, earlier you have told about some software?

@anushbhatia can guide you elaborately on it

**Comment by himanshujaidka** [comment]
okay, after gdrive integration, I'll work on that
