### ISSUE TITLE
Add Option for Font Size

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#197]

**Comment by rutujadhanawade** [comment]
I think there is already a option for font size

**Comment by smaranjitghose** [comment]
> I think there is already a option for font size

I would like to have it in the menu bar as we commonly see in document readers like Microsoft Word or Google Docs

**Comment by dipanshparmar** [comment]
> > I think there is already a option for font size
> 
> I would like to have it in the menu bar as we commonly see in document readers like Microsoft Word or Google Docs

![image](https://user-images.githubusercontent.com/49204837/95007243-1de77300-062b-11eb-93fd-3d60af81e07d.png)
@smaranjitghose You want it like in that highlighted area?

**Comment by smaranjitghose** [comment]
> > > I think there is already a option for font size
> > 
> > 
> > I would like to have it in the menu bar as we commonly see in document readers like Microsoft Word or Google Docs
> 
> ![image](https://user-images.githubusercontent.com/49204837/95007243-1de77300-062b-11eb-93fd-3d60af81e07d.png)
> @smaranjitghose You want it like in that highlighted area?

Yes, in the menu bar but with a drop down like we have it in Google Docs or Microsoft Word

**Comment by dipanshparmar** [comment]
@smaranjitghose okay! I'll do it. Please assign me this issue.
