### ISSUE TITLE
Add Option for Adding Margins over pages

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#198]

**Comment by paraschhugani** [comment]
@smaranjitghose i would like to work on this issue , just this small query : option is needed in menubar or adjacent to option like "Font size".

**Comment by smaranjitghose** [comment]
> @smaranjitghose i would like to work on this issue , just this small query : option is needed in menubar or adjacent to option like "Font size".

Yes. Similar to what we have it Google Docs or Microsoft Word

**Comment by sahebsunny** [comment]
Sir, I love to work on it.
I would be grateful if you can assign this issue to me for DSWOC.
Thank you.

**Comment by Sloth-Panda** [comment]
hey would love to work, let me know if you can assign more than one guy

**Comment by smaranjitghose** [comment]
> hey would love to work, let me know if you can assign more than one guy

Collaborate with @sahebsunny on this please. One of you add the feature in the right position and the other can improve the UI

**Comment by sahebsunny** [comment]
@smaranjitghose Sir I am adding the margin option after "choose page" option. is it alright
![Screenshot 2020-12-28 at 2 23 39 AM](https://user-images.githubusercontent.com/55354715/103179673-5908e380-48b4-11eb-8530-cde875039f94.png)

**Comment by smaranjitghose** [comment]
![doc2pen_editor](https://user-images.githubusercontent.com/46641503/103203033-0eba4d80-491a-11eb-92ea-d1e9d5bdc6b1.png)

+ the margin option

**Comment by sahebsunny** [comment]
sir, I added the margin option as we have it in the Microsoft office word.

![Screenshot 2020-12-28 at 2 46 41 PM](https://user-images.githubusercontent.com/55354715/103203745-9eacc700-491b-11eb-8dbf-6fdc339733a5.png)

**Comment by smaranjitghose** [comment]
> sir, I added the margin option as we have it in the Microsoft office word.
> 
> ![Screenshot 2020-12-28 at 2 46 41 PM](https://user-images.githubusercontent.com/55354715/103203745-9eacc700-491b-11eb-8dbf-6fdc339733a5.png)

Actually, what we mean here is not only leaving indentation for the margin but also drawing lines over the page to make a physical margin.

But ya, you  can start with the addition of this feature

**Comment by sahebsunny** [comment]
sir, I am not able to understand why the output canvas keeps loading
any suggestion
![Screenshot 2020-12-28 at 10 44 05 AM](https://user-images.githubusercontent.com/55354715/103221862-a6836000-4949-11eb-90f0-ec1681064e16.png)

**Comment by sahebsunny** [comment]
> > sir, I added the margin option as we have it in the Microsoft office word.
> > ![Screenshot 2020-12-28 at 2 46 41 PM](https://user-images.githubusercontent.com/55354715/103203745-9eacc700-491b-11eb-8dbf-6fdc339733a5.png)
> 
> Actually, what we mean here is not only leaving indentation for the margin but also drawing lines over the page to make a physical margin.
> 
> But ya, you can start with the addition of this feature

Sir do you want a border for the output canvas ???

**Comment by sahebsunny** [comment]
sir I am adding border to the pages

**Comment by smaranjitghose** [comment]
> sir I am adding border to the pages

Yes. Go ahead
