### ISSUE TITLE
Add to Google Drive, Dropbox feature

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#199]

**Comment by himanshujaidka** [comment]
assign this to me

**Comment by himanshujaidka** [comment]
for this I have to use node, https://developers.google.com/drive/api/v3/manage-uploads#node.js

**Comment by smaranjitghose** [comment]
> for this I have to use node, https://developers.google.com/drive/api/v3/manage-uploads#node.js

You can make use of Axios for doing a POST request or a simple python backend. NodeJS would make the app heavier for the current state

**Comment by himanshujaidka** [comment]
okay

**Comment by vilsi12** [comment]
Can I add

**Comment by smaranjitghose** [comment]
> Can I add

Sure

**Comment by smaranjitghose** [comment]
> > Can I add
> 
> Sure

Are you a part of DWOC or SWOC?

**Comment by Utkarshn10** [comment]
@smaranjitghose I want to contribute to this repo. Could you please inform me how to run this project in local machine as I tried npm install but it isn't working.
