### ISSUE TITLE
Support Us Section

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#200]
Below the Contact Form, add a section for patreon, buymeacoffee and relevant text+illustrations about Support US

**Comment by AyuSoni25** [comment]
I'll do it @smaranjitghose

**Comment by smaranjitghose** [comment]
@AyuSoni25 are you giving a PR today?

**Comment by AyuSoni25** [comment]
Yes sir, today I'll make a PR for this

**Comment by smaranjitghose** [comment]
DM me over slack when you make a PR

**Comment by AyuSoni25** [comment]
sir, what is patreon and buy me coffee, kindly share some refernces

**Comment by paraschhugani** [comment]
@smaranjitghose  i would like to contribute to this, for starters : i would add about open source cultural and how important it is. and with that support US "buymecoffe" and "patreon" .

**Comment by paraschhugani** [comment]
@sameersrivastava13  can i join the slack of this Project , and how do i update my details in contribution section.

**Comment by smaranjitghose** [comment]
> @sameersrivastava13 can i join the slack of this Project, and how do I update my details in the contribution section.

We currently have a [![Gitter](https://badges.gitter.im/doc2pen/community.svg)](https://gitter.im/doc2pen/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
