### ISSUE TITLE
Open Source Subection

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#201]
Below the Team Section, add a subsection for open source programs:

# Suggestions:

- A small quote related to open source followed by a line like " We are proud to have been a part of..:"

- Programs:

     - HackInCodes 2020
     - PClubSummerofCode 2020
     - DSLOP 2020
- For each of the programs add logos, Name of the Program, a short description, link to websites

**Comment by AyuSoni25** [comment]
I'll do it. @smaranjitghose

**Comment by smaranjitghose** [comment]
@AyuSoni25 Do you mind updating the README with the same content as on the website?

**Comment by AyuSoni25** [comment]
No, I won't mind, I'll do it.

**Comment by smaranjitghose** [comment]
Are you updating the website as well?

**Comment by AyuSoni25** [comment]
What updations are required, please let me know..

**Comment by smaranjitghose** [comment]
> What updations are required, please let me know..

Below the Team Section, another section on open source
