### ISSUE TITLE
Editor is not working properly

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#206]
![Screenshot (87)](https://user-images.githubusercontent.com/58654018/94648016-4875bb00-030f-11eb-9e07-bd9bb1969973.png)

**Comment by smaranjitghose** [comment]
This is because you are putting a very long string without line break. You need to modify the script for the canvas for giving automatic line  breaks

**Comment by himanshujaidka** [comment]
okay
