### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#23]

**Comment by ymaheshwari1** [comment]
What kind of Footer design we are expecting?
I can work on making the footer more user friendly.

**Comment by anushbhatia** [comment]
[https://materializecss.com/footer.html](https://materializecss.com/footer.html)

**Comment by ymaheshwari1** [comment]
I can work on this.

**Comment by anushbhatia** [comment]
go an comment on the new issue
