### ISSUE TITLE
Editor not working at all

### ISSUE THREAD

**Issue by Curioo** [smaranjitghose/doc2pen#243]
![image](https://user-images.githubusercontent.com/47332301/94941264-ee265700-04d4-11eb-818a-fa5f10fefc37.png)
All i see is this. Ive already selected a page and a font.

**Comment by smaranjitghose** [comment]
> ![image](https://user-images.githubusercontent.com/47332301/94941264-ee265700-04d4-11eb-818a-fa5f10fefc37.png)
> All i see is this. Ive already selected a page and a font.

Please let some seconds for the entire page to load

**Comment by Curioo** [comment]
i have... i waited about 30 seconds.

**Comment by Curioo** [comment]
![image](https://user-images.githubusercontent.com/47332301/94959484-93e7bf00-04f1-11eb-9472-d9af36eded21.png)
It says this forever

**Comment by smaranjitghose** [comment]
I have resolved it and updated the codebase. Have a look at it again and let me know
