### ISSUE TITLE
"Clan Of Contributors" sections doesn't have all the contributors info.

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/doc2pen#250]
My info is not there :(

**Comment by dipanshparmar** [comment]
@smaranjitghose Can I add my info there?

**Comment by smaranjitghose** [comment]
> @smaranjitghose Can I add my info there?

Definitely. Please add your pic, name, and GitHub

**Comment by dipanshparmar** [comment]
Thanks :)
