### ISSUE TITLE
Team info missing

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/doc2pen#251]
Profile pictures of team members in the team section is not visible without hovering.

You can see here:
![image](https://user-images.githubusercontent.com/49204837/95075712-4b691500-072e-11eb-9518-c082bb1deecd.png)

**Comment by smaranjitghose** [comment]
> Profile pictures of team members in the team section is not visible without hovering.
> 
> You can see here:
> ![image](https://user-images.githubusercontent.com/49204837/95075712-4b691500-072e-11eb-9518-c082bb1deecd.png)

Can you fix the bug?

**Comment by dipanshparmar** [comment]
@smaranjitghose I'll let you know after checking the source code :)
