### ISSUE TITLE
Import from Page Option

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#269]
In the editor page, add a button clicking which the user can upload a text document in .txt or .docx format, and the contents of the file are converted into the corresponding handwritten font

**Comment by carbseater** [comment]
Can you provide a better description for this issue

**Comment by smaranjitghose** [comment]
> Can you provide a better description for this issue

I have updated it now

**Comment by Jahnavi-Jonnalagadda** [comment]
@smaranjitghose Would like to work on this issue. Could you please assign this to me.

**Comment by sahebsunny** [comment]
Sir, I love to work on it.
I would be grateful if you can assign this issue to me for DWOC.
I want to use Handwriting detection with Optical Character Recognition to get the notes from the image or pdf.

**Comment by smaranjitghose** [comment]
@Jahnavi-Jonnalagadda Do it in two PRs

1) read the contents of a text file and paste it into our input screen
2) repeat the same for a doc file

**Comment by smaranjitghose** [comment]
> Sir, I love to work on it.
> I would be grateful if you can assign this issue to me for DWOC.
> I want to use Handwriting detection with Optical Character Recognition to get the notes from the image or pdf.

Well the goal of this project is quite opposite, we want to generate handwritings from text. There is a way to train a LSTM for it.  You can look it up

**Comment by smaranjitghose** [comment]
> @smaranjitghose Would like to work on this issue. Could you please assign this to me.

1 more day

**Comment by sahebsunny** [comment]
Sir, It's interesting if it's open let me work too

**Comment by Jahnavi-Jonnalagadda** [comment]
@smaranjitghose, should the code identify the font in the uploaded file and then convert to handwritten?

**Comment by smaranjitghose** [comment]
> @smaranjitghose, should the code identify the font in the uploaded file and then convert to handwritten?

Basic reading of the text works since we would be anyways converting it to handwritten

**Comment by Jahnavi-Jonnalagadda** [comment]
> > @smaranjitghose, should the code identify the font in the uploaded file and then convert to handwritten?
> 
> Basic reading of the text works since we would be anyways converting it to handwritten

Okay, so just read the text in the uploaded file and convert to handwritten. This what has to be done right?

**Comment by smaranjitghose** [comment]
> > > @smaranjitghose, should the code identify the font in the uploaded file and then convert to handwritten?
> > 
> > 
> > Basic reading of the text works since we would be anyways converting it to handwritten
> 
> Okay, so just read the text in the uploaded file and convert to handwritten. This what has to be done right?

Yes Jahnavi

**Comment by Jahnavi-Jonnalagadda** [comment]
@smaranjitghose, I've unassigned the issue for myself. Found it quite tricky to trace out on how to work on this. Sorry for that.

**Comment by smaranjitghose** [comment]
> @smaranjitghose, I've unassigned the issue for myself. Found it quite tricky to trace out on how to work on this. Sorry for that.

It's fine😊

**Comment by sahebsunny** [comment]
@smaranjitghose 
Sir the idea behind this is to read the notes from the doc or image 
and generate handwriting from that so we could use that handwriting in our output canvas
is that correct???

**Comment by sahebsunny** [comment]
if yes then sir I am thinking of making two different Pr for this
1 for uploading the notes from the doc or image to input and it's obviously going to show up in the output canvas cause the
 " Page Upload " button does not work properly.
2 for generating the handwriting( writing style ) from the doc or image.
is this fine sir

**Comment by smaranjitghose** [comment]
> if yes then sir I am thinking of making two different Pr for this
> 1 for uploading the notes from the doc or image to input and it's obviously going to show up in the output canvas cause the
> " Page Upload " button does not work properly.
> 2 for generating the handwriting( writing style ) from the doc or image.
> is this fine sir


It's simply that, there is text in a .txt or .doc file your friend sent you, you need to open it, read the text (Simple JS file handling), paste in our window and automatically get it converted.

We don't need any image here.

Do it in two PRs:
1) for the .txt file
2) for the .doc file

Rename the button "Import From"

**Comment by sahebsunny** [comment]
@smaranjitghose 
sir I am working on this issue trying to figure out how to convert the RTF to plain text as uploading .txt or .doc file is getting automatically converted in RTF format

**Comment by smaranjitghose** [comment]
> @smaranjitghose
> sir I am working on this issue trying to figure out how to convert the RTF to plain text as uploading .txt or .doc file is getting automatically converted in RTF format

Okaay

**Comment by sahebsunny** [comment]
@smaranjitghose  sir I am done with this issue but as the source files are modified with react it's taking some time for me to understand.

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir I am done with this issue but as the source files are modified with react it's taking some time for me to understand.

Oh don't worry, just change the branch to compare to `base`. The master branch is the new react code. The previous HTML,CSS and JS one is on `base`

**Comment by sahebsunny** [comment]
thank you sir
@smaranjitghose sir im removing the page upload button and adding import from button
