### ISSUE TITLE
Implement options to Download as png,jpg,jpeg and pdf

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#271]

**Comment by paraschhugani** [comment]
@smaranjitghose I would like to contribute in this issue

**Comment by paraschhugani** [comment]
@smaranjitghose hey, my college had exams going one and so I wasn't able to contribute, will make the Pr in a day

**Comment by paraschhugani** [comment]
@smaranjitghose 
 I have made the UI and don't understand the save(str(pageNum)) function is being used to download, I couldn’t find any context in any other file. Can you please guide me to a source where I can more about this function?

**Comment by mharshita** [comment]
@smaranjitghose @anushbhatia I want to work on this issue.

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia I want to work on this issue.

You are part of DWOC @mharshita ?

**Comment by mharshita** [comment]
> > @smaranjitghose @anushbhatia I want to work on this issue.
> 
> You are part of DWOC @mharshita ?

Yes Sir
