### ISSUE TITLE
Add a feature for having a multi page document [Modify the canvas]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#273]

**Comment by Anu-MADMAX** [comment]
i'm interested in this issue. How can I get started

**Comment by anushbhatia** [comment]
https://saurabhdaware.github.io/text-to-handwriting/
Refer this project to implement the multiple page functionality.

**Comment by smaranjitghose** [comment]
Feel free to approach us over discord for any queries

**Comment by Anu-MADMAX** [comment]
Hi! thanks for assigning me this issue although I'm a beginner , so can you
give me some tips on going about this project?

**Comment by anushbhatia** [comment]
This is open source repo so you can refer the code there and copy it here and implement it.

**Comment by amandp13** [comment]
@smaranjitghose NTERESTED IN THIS ISSUE, CAN YOU ASSIGN IT TO ME...PART OF SWOC2021

**Comment by Bishal05** [comment]
Hello I wanted to contribute under Swoc can you please assign me this issue
