### ISSUE TITLE
Sketch Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#275]
Another page similar to our editor page where we can sketch using the mouse, have common shapes that are available in MS Paint, insert text and save our drawings

**Comment by carbseater** [comment]
Can i work on this ?

**Comment by bhoomika07** [comment]
Interested. SWOC Participant.

**Comment by smaranjitghose** [comment]
> Interested. SWOC Participant.

@carbseater has one more day.
After that, you can take this till 31st

**Comment by bhoomika07** [comment]
@carbseater connect with me on discord asap bhoomika#2206

**Comment by carbseater** [comment]
I have sent you a request on discord @bhoomika07

**Comment by anushbhatia** [comment]
Any update guys?

**Comment by bhoomika07** [comment]
I unassigned myself by mistake and we are adding a bit of styling, we are done with the basic functionality.

**Comment by bhoomika07** [comment]
<img width="1258" alt="Screenshot 2021-01-03 at 9 43 22 PM" src="https://user-images.githubusercontent.com/65896648/103483379-e4cac480-4e0c-11eb-8069-3ac5e55349ca.png">

Only, size feature not working as of now
