### ISSUE TITLE
Implementing Map

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#282]
You can use https://www.openstreetmap.org/ for adding a basic map to program

**Comment by carbseater** [comment]
Why do we need to add map feature ? jsut curious to know

**Comment by smaranjitghose** [comment]
> Why do we need to add map feature ? jsut curious to know

Nothing specific. Basically for the footer of the home page. Like made in India

**Comment by Tejas-Ladhani** [comment]
![image](https://user-images.githubusercontent.com/67834407/103153025-5377a480-47b3-11eb-8307-af7119915fd0.png)


do we need something like this ??

**Comment by Cruel-Crab** [comment]
I am interested in this issue; do we need to add a map like in which many websites shows their official address?

**Comment by sahebsunny** [comment]
Sir, I love to work on it.
I would be grateful if you can assign this issue to me.
I can implement google map API or openstreetmap api which ever you want at the footer of the home page with the addresses and all.

**Comment by aryan-alt** [comment]
Hello,
I am interested in this issue and would like to contribute in this project. I will set the map at the footer of the website as you need.

**Comment by Kerveyfelix** [comment]
Can I work on this issue?

**Comment by smaranjitghose** [comment]
> ![image](https://user-images.githubusercontent.com/67834407/103153025-5377a480-47b3-11eb-8307-af7119915fd0.png)
> 
> do we need something like this ??

Yes

**Comment by smaranjitghose** [comment]
> I am interested in this issue; do we need to add a map like in which many websites shows their official address?

Yes

**Comment by smaranjitghose** [comment]
Assigned to @Cruel-Crab for 2 days.
After that @sahebsunny can take up

**Comment by Cruel-Crab** [comment]
> Assigned to @Cruel-Crab for 2 days.
> After that @sahebsunny can take up

Yes sir! I am working on it. The map needs to get added to the index file right?

**Comment by Cruel-Crab** [comment]
> Assigned to @Cruel-Crab for 2 days.
> After that @sahebsunny can take up

Thank you for assigning it to me sir :) I am working on it.
