### ISSUE TITLE
On hover of navbar items the style should be changed

### ISSUE THREAD

**Issue by Shruti3004** [smaranjitghose/doc2pen#285]

**Comment by shriyaMadan** [comment]
can this issue be assigned to me? (Under DWOC2020)

**Comment by dollyjain51099** [comment]
I would like to work on this issue, please assign it to me!

**Comment by shriyaMadan** [comment]
@smaranjitghose kindly review my PR

**Comment by smaranjitghose** [comment]
> @smaranjitghose kindly review my PR

Could please incorporate the changes as suggested by @anushbhatia

**Comment by smaranjitghose** [comment]
> I would like to work on this issue, please assign it to me!

Let's give @shriyaMadan a couple of days more, then you can take up this issue

**Comment by Amit366** [comment]
Can this issue be given to me??

**Comment by Sloth-Panda** [comment]
Hey, can you also assign this to me?

**Comment by Amit366** [comment]
style means the color or font-size?

**Comment by Amit366** [comment]
because the text color isn't changing on hovering but font size and background colors are changing . So what can I change?

**Comment by Sloth-Panda** [comment]
Yes, not able to change the text color. Any other suggestions on what to change??

**Comment by Amit366** [comment]
kindly review my PR

**Comment by chehak123** [comment]
hii 
i would like to work on this issue

**Comment by Amit366** [comment]
#303

**Comment by Amit366** [comment]
#304
