### ISSUE TITLE
When hovering over the "Page Upload" option in canvas, the pointer should change to link pointer instead of the I-Beam pointer

### ISSUE THREAD

**Issue by apuneet839** [smaranjitghose/doc2pen#288]

**Comment by apuneet839** [comment]
I have a fix for it and can make a pr right away. So can you please assign it to me?

**Comment by rajiv8** [comment]
My contribution has been merged. Please make me Assignee of this issue.

**Comment by smaranjitghose** [comment]
> My contribution has been merged. Please make me Assignee of this issue.

As I communicated earlier, I had assumped that you were assigned this issue but later on finding out otherwise I had to revert your PR
