### ISSUE TITLE
Update the Open Source Section

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#297]
Include Cards for Script Winter of Code and DevScript Winter of Code

**Comment by satyampandeygit** [comment]
I want to do this kindly assign me this

**Comment by smriti1313** [comment]
Hi, Can i work on it too? I am really excited to work on this project. Thank you

**Comment by Utkarshn10** [comment]
I would like to work on this issue. I am a Swoc participant.

**Comment by satyampandeygit** [comment]
The issue is resolved in PR #306
