### ISSUE TITLE
Update the ReadMe of the project with the contents on the home page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#298]
- Use Storytelling or Creative Writing
- Replace the illustrations with gips. Use Giphy
- Make the Contribution Guidelines more detailed 
- Separate Subsection for License
- Separate Subsection for Code of Conduct
- Add a team subsection

- Add section for open  source programs
Reference: [Awesome Portfolio Website](https://github.com/smaranjitghose/awesome-portfolio-websites)

**Comment by chehak123** [comment]
hii 
i would like to work on this issue

**Comment by smriti1313** [comment]
hi, it would be great if you could give me a chance to work on it.

**Comment by smaranjitghose** [comment]
@smriti1313 @chehak123 Could you two please divide the work among yourself.

Do not forget to add DWOC and SWOC2021 in the open source sub section 😊

**Comment by Sloth-Panda** [comment]
Hey @smaranjitghose  can I do the same?

**Comment by smriti1313** [comment]
> @smriti1313 @chehak123 Could you two please divide the work among yourself.
> 
> Do not forget to add DWOC and SWOC2021 in the open source sub section


Yeah sure.

@chehak123 can we connect and divide work on discord doc2pen channel? just leave a text regarding this issue. I will text back to you.

**Comment by smaranjitghose** [comment]
> Hey @smaranjitghose can I do the same?

This issue is too simple for 3 people. I'll assign other issues once they are available

**Comment by chehak123** [comment]
> > @smriti1313 @chehak123 Could you two please divide the work among yourself.
> > Do not forget to add DWOC and SWOC2021 in the open source sub section
> 
> Yeah sure.
> 
> @chehak123 can we connect and divide work on discord doc2pen channel? just leave a text regarding this issue. I will text back to you.

Yeah sure @smriti1313

**Comment by smriti1313** [comment]
@chehak123 I had left a message in doc2open channel on discord.

**Comment by smaranjitghose** [comment]
> @chehak123 I had left a message in doc2open channel on discord.

One tiny request: Put these messages on the discord channel only, otherwise I get notifications for these too 😅

**Comment by smriti1313** [comment]
Hi, sorry for those unnecessary notifications. I would like if you assign this to me too since chehak's the only one right now who's been assigned

**Comment by smaranjitghose** [comment]
> Hi, sorry for those unnecessary notifications. Can you please assign this to me too since chehak's the only one right now who's been assigned??

OOPs missed that earlier😅

**Comment by bhoomika07** [comment]
Interested.

**Comment by smaranjitghose** [comment]
> Interested.

Let's wait for a couple of days till @smriti1313 and @chehak123 give their PRs. After that, if there's any improvement to be done, you can take it up

**Comment by smriti1313** [comment]
Update : I have changed few lines and added a whole contribution.md which I linked to main readme.md. All i have to do now is get some cool gifs. I will do it by today midnight.

**Comment by smaranjitghose** [comment]
> Update : I have changed few lines and added a whole contribution.md which I linked to main readme.md. All i have to do now is get some cool gifs. I will do it by today midnight.

Awesome!. Waiting for your PR😊
