### ISSUE TITLE
Change the hover effect of the NavBar to something more aesthically soothing

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#299]
Consult with @anushbhatia on the UI/UX if required.
Feel free to use inspirations from codepen.io

**Comment by Sloth-Panda** [comment]
okay let me take this then

**Comment by smaranjitghose** [comment]
> okay let me take this then

The current effect you did is not bad but I believe we can do more

**Comment by Sloth-Panda** [comment]
But what do you suggest to do then?

**Comment by shraddha-1402** [comment]
I would like to work on this issue for DWOC. Can you assign this to me?

**Comment by smaranjitghose** [comment]
> I would like to work on this issue for DWOC. Can you assign this to me?

Discuss the effect with @anushbhatia please.

**Comment by Amit366** [comment]
I would like to solve this. 
But What kind of change do you suggest??

**Comment by shraddha-1402** [comment]
> > I would like to work on this issue for DWOC. Can you assign this to me?
> 
> Discuss the effect with @anushbhatia please.

yes!

**Comment by shraddha-1402** [comment]
> > > I would like to work on this issue for DWOC. Can you assign this to me?
> > 
> > 
> > Discuss the effect with @anushbhatia please.
> 
> yes!



> > I would like to work on this issue for DWOC. Can you assign this to me?
> 
> Discuss the effect with @anushbhatia please.

Where should i discuss? here or on Discussions?

**Comment by shraddha-1402** [comment]
@anushbhatia please share the changes and effects i should do to the navigation menu

**Comment by Amit366** [comment]
@anushbhatia please can you suggest the changes.

**Comment by anushbhatia** [comment]
https://codepen.io/davidicus/full/emgQKJ
Something kind of this the first button present here

**Comment by Amit366** [comment]
https://user-images.githubusercontent.com/60662775/103338750-620cd700-4aa5-11eb-8d49-25892774c7b9.mp4

I have modified the nav bar design. can I send the pull request?
