### ISSUE TITLE
Fix or change the top section. 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#301]
On loading the website for the first time we get the error as shown in the screenshot below
![home_error](https://user-images.githubusercontent.com/46641503/103168969-f4229e80-485d-11eb-862d-bf9efe713f4c.jpg)

Feel free to change the design if required

**Comment by Amit366** [comment]
I can try this one

**Comment by Amit366** [comment]
Sir I have sent the pull request for the hover of nav-items and also I have fixed this issue so please accept it.

**Comment by Akshit42-hue** [comment]
@smaranjitghose  can you please assigned me this issue I want to work on this issue

**Comment by Sloth-Panda** [comment]
Let me know if I can help

**Comment by shraddha-1402** [comment]
Is this issue still open?

**Comment by Akshit42-hue** [comment]
@smaranjitghose Please review my PR

**Comment by smaranjitghose** [comment]
> @smaranjitghose Please review my PR

Please have patience. The project maintainers will review the PRs as per their available timings. These messages give us additional notifications which are not useful

**Comment by smaranjitghose** [comment]
> Is this issue still open?

Yes

**Comment by chehak123** [comment]
I want to work on this issue

**Comment by smaranjitghose** [comment]
> Is this issue still open?

Assigned for 1 day

**Comment by shraddha-1402** [comment]
> > Is this issue still open?
> 
> Assigned for 1 day

So, should i start working on it?

**Comment by smaranjitghose** [comment]
> > > Is this issue still open?
> > 
> > 
> > Assigned for 1 day
> 
> So, should i start working on it?

Sure

**Comment by himanshujaidka** [comment]
@shraddha-1402 if you need help then ping me

**Comment by Amit366** [comment]
Can I work on this issue?

**Comment by shraddha-1402** [comment]
> @shraddha-1402 if you need help then ping me

Sure!!

**Comment by himanshu007-creator** [comment]
please assign me this issue.

**Comment by dhwanishingala** [comment]
I would like to work on this issue.

**Comment by ashuvssut** [comment]
@smaranjitghose  I have a clear idea how to do this. I will submit my PR within one day. 

Please assign me this issue.
