### ISSUE TITLE
Add Cursor Where Its Start Writing

### ISSUE THREAD

**Issue by raman08** [smaranjitghose/doc2pen#309]
It would be easy if we can Where is the program start writing **in handwriting mode**.

**Comment by shraddha-1402** [comment]
Can you please elaborate what you are suggesting?

**Comment by smaranjitghose** [comment]
> It would be easy if we can Where is the program start writing **in handwriting mode**.

If you mean the position of starting of the text, it can be adjusted using X and Y axes
