### ISSUE TITLE
Adding Zoom in/Zoom out effects

### ISSUE THREAD

**Issue by bhavesh1129** [smaranjitghose/doc2pen#315]
Hey @smaranjitghose!
I want to add some cool CSS animation like **Zoom in/Zoom out** on your website to look it more better.
Hope you like it.

Thank you!

**Comment by smaranjitghose** [comment]
> Hey @smaranjitghose!
> I want to add some cool CSS animation like **Zoom in/Zoom out** on your website to look it more better.
> Hope you like it.
> 
> Thank you!

Sure.
Which parts?

**Comment by bhavesh1129** [comment]
In-Home section (Images), Project Maintainers, and icons in support us.

**Comment by smaranjitghose** [comment]
> Thankyou!
> In-Home section (Images), Project Maintainers, and icons in support us.

Sure. Go ahead

**Comment by anushbhatia** [comment]
Any update?

**Comment by bhavesh1129** [comment]
Yeah, I had almost added the feature.
And make a PR soon.
