### ISSUE TITLE
Downloaded PDF doesn't open correctly

### ISSUE THREAD

**Issue by sj-on** [smaranjitghose/doc2pen#323]
It's probably the case that the PDF isn't being encoded correctly by the tool. When I tried to download the writing in PDF form and opened it, it failed to open.
![image](https://user-images.githubusercontent.com/46680993/103396485-9fcb3780-4b59-11eb-920c-2f2557a3965a.png)

And this is what the file  originally looks on the website:
![image](https://user-images.githubusercontent.com/46680993/103396513-ca1cf500-4b59-11eb-8442-bda3e616515a.png)

**Comment by sj-on** [comment]
I have tried opening it more than one time, the same error persists.

**Comment by smaranjitghose** [comment]
> It's probably the case that the PDF isn't being encoded correctly by the tool. When I tried to download the writing in PDF form and opened it, it failed to open.
> ![image](https://user-images.githubusercontent.com/46680993/103396485-9fcb3780-4b59-11eb-920c-2f2557a3965a.png)
> 
> And this is what the file originally looks on the website:
> ![image](https://user-images.githubusercontent.com/46680993/103396513-ca1cf500-4b59-11eb-8442-bda3e616515a.png)

Yes, there's an error in the encoding.
Would like to rewrite the function for Export as PDF?

**Comment by anushbhatia** [comment]
@sj-on will you like to work on this or you want anyone else to take this up?

**Comment by sj-on** [comment]
You can assign it to someone else. 😅  @anushbhatia

**Comment by avinashupadhya99** [comment]
Hey, I would like to work on this issue, can you please assign it to me?

**Comment by nagasrisai** [comment]
can you assign it to me @anushbhatia
