### ISSUE TITLE
Screen size changes the dimensions and content of Image exported

### ISSUE THREAD

**Issue by sj-on** [smaranjitghose/doc2pen#324]
![image](https://user-images.githubusercontent.com/46680993/103396745-e4a39e00-4b5a-11eb-8dff-a540a188a8eb.png)
When I had two apps opened side by side (two different browser windows), the Doc2Pen site adjusted itself (screen responsiveness), but that changed the output of when I downloaded the resultant PNG file.

![3](https://user-images.githubusercontent.com/46680993/103396779-17e62d00-4b5b-11eb-929f-e5c050a45fe3.png)
This is when the screen was divided among two windows (not full screen).

![3 (1)](https://user-images.githubusercontent.com/46680993/103396791-2af8fd00-4b5b-11eb-8adf-83ac56dc2442.png)
This is when the website tab occupied the whole screen (laptop screen).

This might cause difference in download quality/size/dimensions when using the website on different screens.

**Comment by Swapnil-Gaur** [comment]
@smaranjitghose can I work on this issue?

**Comment by smaranjitghose** [comment]
> ![image](https://user-images.githubusercontent.com/46680993/103396745-e4a39e00-4b5a-11eb-8dff-a540a188a8eb.png)
> When I had two apps opened side by side (two different browser windows), the Doc2Pen site adjusted itself (screen responsiveness), but that changed the output of when I downloaded the resultant PNG file.
> 
> ![3](https://user-images.githubusercontent.com/46680993/103396779-17e62d00-4b5b-11eb-929f-e5c050a45fe3.png)
> This is when the screen was divided among two windows (not full screen).
> 
> ![3 (1)](https://user-images.githubusercontent.com/46680993/103396791-2af8fd00-4b5b-11eb-8adf-83ac56dc2442.png)
> This is when the website tab occupied the whole screen (laptop screen).
> 
> This might cause difference in download quality/size/dimensions when using the website on different screens.

Would you like to fix this bug?

**Comment by Swapnil-Gaur** [comment]
Have you set the mobile view?

**Comment by Swapnil-Gaur** [comment]
Have you set the mobile view , if yes so we can fix this issue by applying  media query on font size , should I send you pull request  for this?
