### ISSUE TITLE
Special Characters aren't rendered properly in certain fonts

### ISSUE THREAD

**Issue by Akshu-on-github** [smaranjitghose/doc2pen#329]
Special characters like the ampersand (&) and apostrophe('), common punctuation like commas and full-stops, and numbers are not rendered properly in Dewebeauty Demo. Screenshots attached below:

![image](https://user-images.githubusercontent.com/61582763/103454127-d2666300-4d06-11eb-83cf-3e5a71d4ebef.png)

![image](https://user-images.githubusercontent.com/61582763/103454096-61bf4680-4d06-11eb-886a-fb4849ca486c.png)

![image](https://user-images.githubusercontent.com/61582763/103454138-e6aa6000-4d06-11eb-9101-5cdaf8ae40f2.png)

The apostrophe seems to be a problem in these fonts as well: (may not be limited to the following)
- Simple font
- Messed font
- Curved font
- Small font
- Clear font
- Thin font
- Thin messed font

![image](https://user-images.githubusercontent.com/61582763/103454245-15750600-4d08-11eb-8571-35b20d9d9ecd.png)

I hope that all is in order,
Akshu

**Comment by ashuvssut** [comment]
this is same as issue #322.
