### ISSUE TITLE
Drop Down menu is  For Download alignment Problem

### ISSUE THREAD

**Issue by dsnehasish74** [smaranjitghose/doc2pen#330]
![Screenshot (505)](https://user-images.githubusercontent.com/58779604/103458033-351d2600-4d2a-11eb-86d9-16492de3d881.png)

Hope It helps
I want to work on this issue as a part of DevScript Winter of Code 2020 so please assign this to me

**Comment by ashuvssut** [comment]
@smaranjitghose  I know this issue. It just needs 2 lines of CSS🥴. There was a mistake in my last PR (coz I was a little confused with that long bootstrap html😵). I will submit my PR right away after you allow me to work on this.

Please assign me this one. I will submit that fix right away.

--(DWoC n SWoC Participant)

**Comment by ashuvssut** [comment]
@anushbhatia  should I submit my PR?

**Comment by anushbhatia** [comment]
Sure
