### ISSUE TITLE
Drop Down options overlapping in smaller screen  and is not shown because white background

### ISSUE THREAD

**Issue by ayeshaqaisar** [smaranjitghose/doc2pen#332]
![Screenshot (76)](https://user-images.githubusercontent.com/56070872/103465826-46cfef00-4d65-11eb-94ba-6ed70bb5befd.png)
![Screenshot (77)](https://user-images.githubusercontent.com/56070872/103465832-4cc5d000-4d65-11eb-80ae-8c8d3e368e02.png)

Can I work on this? SWoC 2021 participant

**Comment by ashuvssut** [comment]
@smaranjitghose I have worked on this navbar and I know how to fix it. I will submit my PR within 1 day.

Please assign me this issue. 
 -- DWoC and SWoC 2021 participant

**Comment by anushbhatia** [comment]
Let @ayeshaqaisar work on this if he is not able to do it in 3-4 days then will assign this to you.

**Comment by ashuvssut** [comment]
ok @anushbhatia. I have no problem. I have actually fixed it today😅.

This is a event to give everyone a chance to learn. Let @ayeshaqaisar work on it😁😁

**Comment by ayeshaqaisar** [comment]
I have fixed the issue
should  I make the PR now or after 5th for SWoC?
![Screenshot (92)](https://user-images.githubusercontent.com/56070872/103476456-ea5be680-4ddb-11eb-8e04-a9ca52dc5f2a.png)

**Comment by Amit366** [comment]
I have also solved this issue
![IMG_20210103_203636](https://user-images.githubusercontent.com/60662775/103481874-7d5c4700-4e03-11eb-8eae-e56f63440b8c.jpg)

**Comment by ashuvssut** [comment]
amazing! congrats

**Comment by Amit366** [comment]
https://user-images.githubusercontent.com/60662775/103482360-77b43080-4e06-11eb-8fa0-1cdce9cd3e2f.mp4

This is for the editor page.

**Comment by smaranjitghose** [comment]
Mobile View Nav bar correction: https://girlscriptboilerplate.netlify.app/

**Comment by smaranjitghose** [comment]
> Mobile View Nav bar correction: https://girlscriptboilerplate.netlify.app/

@ayeshaqaisar Your fix is right. Just expand it to the entire page as shown in the above reference

**Comment by smaranjitghose** [comment]
>  hambuirger.mp4 
> This is for the editor page.

The current design is more soothing than this change

**Comment by Amit366** [comment]
So should I change it according to https://girlscriptboilerplate.netlify.app/

**Comment by ayeshaqaisar** [comment]
> > Mobile View Nav bar correction: https://girlscriptboilerplate.netlify.app/
> 
> @ayeshaqaisar Your fix is right. Just expand it to the entire page as shown in the above reference

ok

**Comment by Amit366** [comment]
@smaranjitghose should I expand it ?

**Comment by ayeshaqaisar** [comment]
![iimg](https://user-images.githubusercontent.com/56070872/104123003-7aff6d00-536e-11eb-94a3-4e68d628f76e.png)

SWoC Participant
