### ISSUE TITLE
The map section overlaps the contact us form in the "Get in touch section"

### ISSUE THREAD

**Issue by Abhijay007** [smaranjitghose/doc2pen#339]
The map overlaps the contact us form in the "Get in touch section"

![footer](https://user-images.githubusercontent.com/64387054/103559787-b61c1f00-4edc-11eb-85b3-963d30fb3d6c.PNG)
 
Maybe it can be resolved by setting overflow = hidden or by changing the dimensions of the maps API section/display.

**Comment by thevivekpande** [comment]
@Abhijay007 @eagleanurag @thealphacod3r @shreyakapoor08 @nerdynikhil <h1> can i solve this ?</h1>

**Comment by Abhijay007** [comment]
close #339 via #341
