### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by Kashishjain04** [smaranjitghose/doc2pen#342]
Hamburger nav menu is mixing with other content of the page.
![Screenshot 2021-01-05 at 10 45 29 PM](https://user-images.githubusercontent.com/55389276/103676944-b8977b00-4fa7-11eb-910e-19469e2a03ab.png)

**Comment by Kashishjain04** [comment]
I can fix this issue. Please assign this to me..

**Comment by thevivekpande** [comment]
@Kashishjain04 @eagleanurag @thealphacod3r can i fix it?
