### ISSUE TITLE
REACT: Add Navigation bar to the react version of the project!

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#350]

**Comment by RitikPandey1** [comment]
I would like to work on this @smaranjitghose

**Comment by smaranjitghose** [comment]
@sanjay270899  @RitikPandey1 @neeagwl I would suggest to collaborate over the slack channel while working on your respective issues so that there are no merge conflicts among your PRs

**Comment by neeagwl** [comment]
Sure, would do that

**Comment by RitikPandey1** [comment]
Can I make whole header again with navigation bar using bootstrap in react ?
like this
![pic1](https://user-images.githubusercontent.com/57366926/104117492-ae7ad100-5347-11eb-9910-58393e73e744.PNG)
or only add navigation bar in current header 
current header in react
![pic2](https://user-images.githubusercontent.com/57366926/104117478-95722000-5347-11eb-8c0d-4eaf404316e9.PNG)

@smaranjitghose

**Comment by smaranjitghose** [comment]
> Can I make whole header again with navigation bar using bootstrap in react ?
> like this
> ![pic1](https://user-images.githubusercontent.com/57366926/104117492-ae7ad100-5347-11eb-9910-58393e73e744.PNG)
> or only add navigation bar in current header
> current header in react
> ![pic2](https://user-images.githubusercontent.com/57366926/104117478-95722000-5347-11eb-8c0d-4eaf404316e9.PNG)
> 
> @smaranjitghose

I'll suggest using Tailwind for making custom components

**Comment by RitikPandey1** [comment]
> > Can I make whole header again with navigation bar using bootstrap in react ?
> > like this
> > ![pic1](https://user-images.githubusercontent.com/57366926/104117492-ae7ad100-5347-11eb-9910-58393e73e744.PNG)
> > or only add navigation bar in current header
> > current header in react
> > ![pic2](https://user-images.githubusercontent.com/57366926/104117478-95722000-5347-11eb-8c0d-4eaf404316e9.PNG)
> > @smaranjitghose
> 
> I'll suggest using Tailwind for making custom components

I am not familiar with Tailwind and currently I don't have enough time to explore it due to my exams, so should I use bootstrap to make  header and navigation ?

**Comment by smaranjitghose** [comment]
> > > Can I make whole header again with navigation bar using bootstrap in react ?
> > > like this
> > > ![pic1](https://user-images.githubusercontent.com/57366926/104117492-ae7ad100-5347-11eb-9910-58393e73e744.PNG)
> > > or only add navigation bar in current header
> > > current header in react
> > > ![pic2](https://user-images.githubusercontent.com/57366926/104117478-95722000-5347-11eb-8c0d-4eaf404316e9.PNG)
> > > @smaranjitghose
> > 
> > 
> > I'll suggest using Tailwind for making custom components
> 
> I am not familiar with Tailwind and currently I don't have enough time to explore it due to my exams, so should I use bootstrap to make header and navigation ? @smaranjitghose

Do the changes as suggested by @anushbhatia. After that we can go to Tailwind.  Perhaps after your exams
