### ISSUE TITLE
REACT:  APP UI Update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#352]
Make the UI Similar to Google Docs or Microsoft Word, with the Control panel (horizontally laid out) above the text area. The text area should cover the rest of the screen as in other document or text editors

**Comment by carbseater** [comment]
Assign me for this

**Comment by carbseater** [comment]
Before working on the UI, I want to know how you are expecting the UI, So give me any reference or I have creaated a Design, have a look at this and give review 
![prop](https://user-images.githubusercontent.com/59422042/104116049-31e1f580-533b-11eb-8aea-dff38d6c8236.png)

**Comment by carbseater** [comment]
@smaranjitghose should i start working on this design?

**Comment by anushbhatia** [comment]
yes
