### ISSUE TITLE
REACT: Add option to change font color (red, blue, black, green)

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#355]
Implementing a feature to add different colours of the pen to react app of the website. Having different colours of pen-like blue, green, red, black.
Sample Dropdown is attached. You Can Look Through this.
![image](https://user-images.githubusercontent.com/40017559/104086346-0c8eb200-527d-11eb-8026-03c1cb1394f8.png)

**Comment by neeagwl** [comment]
I would like to work on this issue.

**Comment by kenkirito** [comment]
can i work on this
