### ISSUE TITLE
REACT: Add Option to change background sheet

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#356]

**Comment by shubhraagarwal** [comment]
Can you please elaborate the issue?

**Comment by smaranjitghose** [comment]
> Can you please elaborate the issue?

We need to change the background of the output screen with other styles of pages. Check out doc2pen.smaranjitghose.codes/editor

**Comment by riyasavant** [comment]
Can I work on this issue?

**Comment by Chaitanya31612** [comment]
@smaranjitghose I'd like to work on this issue if it's available.

**Comment by Chaitanya31612** [comment]
@smaranjitghose please review my pull request #430
