### ISSUE TITLE
REACT: Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#357]
Make it similar to the one in the basic HTML,CSS and JS version

**Comment by RitikPandey1** [comment]
I would like to work on this

**Comment by shraddha-1402** [comment]
Hey @smaranjitghose i would like to work on this issue. please assign me

**Comment by sanjay270899** [comment]
I want to work on this.

**Comment by sanjay270899** [comment]
@smaranjitghose Where is the Home Page with the basic version?

**Comment by smaranjitghose** [comment]
> @smaranjitghose Where is the Home Page with the basic version?

In the base branch

**Comment by nehaparmar99** [comment]
Can i work on it?

**Comment by kenkirito** [comment]
can you assign me this I will complete this at midnight. and also please add level tags @smaranjitghose

**Comment by smaranjitghose** [comment]
> Can i work on it?

Improve upon @sanjay270899 's PR

**Comment by nehaparmar99** [comment]
> > Can i work on it?
> 
> Improve upon @sanjay270899 's PR

**Comment by nehaparmar99** [comment]
> > Can i work on it?
> 
> Improve upon @sanjay270899 's PR

Sure, working on it.

**Comment by nehaparmar99** [comment]
> > Can i work on it?
> 
> Improve upon @sanjay270899 's PR

Hey, can i contact you on Slack?Had a few doubts regarding the improvements.

**Comment by anushbhatia** [comment]
> > > Can i work on it?
> > 
> > 
> > Improve upon @sanjay270899 's PR
> 
> Hey @smaranjitghose , can i contact you on Slack?Had a few doubts regarding the improvements.

Feel Free to use our slack channel for doubts

**Comment by anushbhatia** [comment]
You can work on the enhancement of the cover page by adding something that represents doc2pen in the best way possible.
https://texttohandwritingconverter.online/
https://www.openpeeps.com/ illustrations can be used from here
