### ISSUE TITLE
Deep Learning: Train a LSTM to generate hand writing

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#358]
### Reference Paper:
[Generating Sequences With Recurrent Neural Networks](https://arxiv.org/abs/1308.0850)

### Reference Code:
[Repo](https://github.com/sjvasquez/handwriting-synthesis)

### Instructions:
- Please use Google Colab as a platform to train the model
- Using TensorFlow is preferred

**Comment by TanweerulHaque** [comment]
Hi there Sir,
Can you assign me this issue ??
I would like to proceed with the working

**Comment by smaranjitghose** [comment]
> Hi there Sir,
> Can you assign me this issue ??
> I would like to proceed with the working

It's almost a week. @TanweerulHaque  what's your update on this?

**Comment by TanweerulHaque** [comment]
Hi there @smaranjitghose This LSTM paper was a bit difficult to comprehend. However, I have started with the coding part. I'll just be needing a couple of days more. Thank you.

**Comment by smaranjitghose** [comment]
No worries @TanweerulHaque. Just give us some updates every two days. consult with @vidhi-mody if required
