### ISSUE TITLE
Import Text From Doc or txt file📄

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#369]
Adding functionality to add text imported from the .txt format or .doc format
![image](https://user-images.githubusercontent.com/40017559/104086561-12859280-527f-11eb-91f8-e4570ee5e4e6.png)

**Comment by shreyasY2k** [comment]
I wan’t to work on this

**Comment by shreyasY2k** [comment]
Hey @vidhi-mody sorry to say this. My University exams just got announced. So I couldn't proceed with the issue. Please unassign and give it to anyone who needs. Sorry Again!

**Comment by smaranjitghose** [comment]
/polls Option1 'Option 2' "Option 3"

# Automatically replace with the following markdown =>
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXZMATAZ5BXF8RVRAMRSSANA/Option1)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXZMATAZ5BXF8RVRAMRSSANA/Option1/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXZMATAZ5BXF8RVRAMRSSANA/Option%202)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXZMATAZ5BXF8RVRAMRSSANA/Option%202/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXZMATAZ5BXF8RVRAMRSSANA/Option%203)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXZMATAZ5BXF8RVRAMRSSANA/Option%203/vote)
