### ISSUE TITLE
REACT: Adding Line spacing and Width 📑

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#372]
Line Spacing between two elements.
Width of the number of words in a line. It can be done by adding a slider just like that specified in the image.
***Bonus**
Adding letter Spacing. Space between two letters in a word.
![image](https://user-images.githubusercontent.com/40017559/104086950-1666e400-5282-11eb-8a0a-203288addb04.png)

**Comment by carbseater** [comment]
Assign me please

**Comment by anushbhatia** [comment]
Any update

**Comment by smaranjitghose** [comment]
@carbseater Let me or @anushbhatia know if you are still interested

**Comment by ashuvssut** [comment]
please assign me this issue.
