### ISSUE TITLE
feature request: Add pagination and provide the functionality to download compiled page pdf

### ISSUE THREAD

**Issue by Abhijay007** [smaranjitghose/doc2pen#385]
Add pagination and provide the functionality to download compiled page pdf

According to current functionality, when the user is done with the writing of first page then he/she first needs to remove everything and after that need to start from the very beginning to write their second page which means they need to download what they have written first then need to write the second page which also they need to download if they switch to the third one and so on, which is a kinda annoying and challenging task.

***What I want to suggest/request***

Provide ***pagination*** means if the user is done with the writing of first page then give him option to switch between pages in order to write his second page and when the user is done with all his writing stuff give him the option to download a complied pdf or docs file.

The video below gives you a better picture of the issue:

![doc2pen-issue](https://user-images.githubusercontent.com/64387054/104130402-954d4100-5396-11eb-8acc-6b464f9fee29.gif)

**Comment by Chaitanya31612** [comment]
@anushbhatia I'd like to work on this issue.

**Comment by smaranjitghose** [comment]
> @anushbhatia I'd like to work on this issue.

We are doing this exclusively for the version on the master (i.e. the REACT code, the base branch version is discontinued)
