### ISSUE TITLE
Extracting texts from images/online screenshots

### ISSUE THREAD

**Issue by SinghShreya05** [smaranjitghose/doc2pen#393]
I'll like to work on it, kindly assign me this issue under SWOC label. @vidhi-mody

**Comment by SinghShreya05** [comment]
@vidhi-mody can I proceed with this?

**Comment by vidhi-mody** [comment]
@SinghShreya05 sure. I have assigned it to you!

**Comment by smaranjitghose** [comment]
@SinghShreya05  Are you proposing an OCR?

**Comment by SinghShreya05** [comment]
@smaranjitghose Yes, I am applying python-ocr to extract texts.

**Comment by smaranjitghose** [comment]
> @smaranjitghose Yes, I am thinking of applying python-ocr to extract texts from images. Can you please attach SWOC2021 label to it?

Actually the concept of this project is quite the opposite so it won't be relevant. 

You can implement it in https://github.com/smaranjitghose/DocLense
