### ISSUE TITLE
REACT: Improve navbar design 🎨

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#399]
feel free to contact me over discord or slack for the design changes. Will guide you through it.

**Comment by sakshikhachane** [comment]
@anushbhatia I would like to work on this issue.

**Comment by khusboobothra** [comment]
@anushbhatia , Is the issue still open? I would like to work on it.

**Comment by smaranjitghose** [comment]
> @anushbhatia , Is the issue still open? I would like to work on it.

Yes. Go ahead with your proposition for improvement

**Comment by khusboobothra** [comment]
![Screenshot (114)](https://user-images.githubusercontent.com/59091399/105357315-a6aa0f00-5c1a-11eb-9002-127f0b431068.png)
![Screenshot (113)](https://user-images.githubusercontent.com/59091399/105357321-a873d280-5c1a-11eb-88ac-e1fac51839f2.png)

@smaranjitghose ,What are your thoughts on this, sir?

**Comment by kenkirito** [comment]
@smaranjitghose assign me this issue

**Comment by nehaparmar99** [comment]
Is this still up for grabs?

**Comment by smaranjitghose** [comment]
> Is this still up for grabs?

I guess you have already commented on #439 and assigned the same so I am closing this one @nehaparmar99
