### ISSUE TITLE
React: Improve footer🌟

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#401]
![image](https://user-images.githubusercontent.com/40017559/104852370-bd9de800-5920-11eb-9b22-50fd9505c5a5.png)
Improving the current footer by adding more functionality like contact us form or subscribe to newsletter kind of section

**Comment by AbhipsaGuru1012** [comment]
@anushbhatia can I work on this issue?

**Comment by AbhipsaGuru1012** [comment]
![doc2pen](https://user-images.githubusercontent.com/58511560/104909916-92fa7080-59ae-11eb-974a-5d53b7f3789e.PNG)

@anushbhatia @vidhi-mody is this footer okay? Please note that the footer is responsive and on hovering on the subscribe button it turns blue.

**Comment by anushbhatia** [comment]
the font is a bit dull change that to bolder one you can take inspiration from this project https://girlscriptboilerplate.netlify.app/

**Comment by AbhipsaGuru1012** [comment]
> the font is a bit dull change that to bolder one you can take inspiration from this project https://girlscriptboilerplate.netlify.app/
> The button can have kind of off white colour inside on hover u can add blue colour

Okay sure, I will make the changes.

**Comment by anushbhatia** [comment]
Then you make a PR

**Comment by AbhipsaGuru1012** [comment]
@anushbhatia can you please give an overview of the functionalities that can be added to the newsletter

**Comment by anushbhatia** [comment]
First work on the UI part of it then we can take steps towards functionality once the UI is perfect.

**Comment by AbhipsaGuru1012** [comment]
> First work on the UI part of it then we can take steps towards functionality once the UI is perfect.

Okay sure, once the UI is properly done I will make a PR

**Comment by anushbhatia** [comment]
Great work @AbhipsaGuru1012 🎉🎉. Now we can proceed with the functionality part https://blog.mailtrap.io/react-send-email/
I would recommend nodemailer or pure react for this it might be quite new to you and for a demo, email uses your for now then once the PR is approved will add our org email to it. If you face any issues feel free to message me on slack or discord.

**Comment by AbhipsaGuru1012** [comment]
Thank you so much @anushbhatia. I will try adding functionality to the newsletter. If I face any issue then I will ping on discord.

**Comment by anushbhatia** [comment]
Any updates @AbhipsaGuru1012

**Comment by AbhipsaGuru1012** [comment]
@anushbhatia I am working on it, I am getting some errors while clicking on the subscribe button. Will complete at the earliest
