### ISSUE TITLE
REACT:Import Text From Doc or txt file📄

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#402]
Implementing something similar to this on the current React Webpage
![image](https://user-images.githubusercontent.com/40017559/104852552-b5927800-5921-11eb-86ac-ff8d93a666d7.png)
https://smaranjitghose.github.io/doc2pen/

**Comment by imakash3011** [comment]
I would like to work on this issue.

**Comment by smaranjitghose** [comment]
> I would like to work on this issue.

Deadline: within next 4 days
Do it only for importing text from .txt files. Leave .doc files for now

**Comment by Chaitanya31612** [comment]
@smaranjitghose I'd like to work on it, kindly assign if it's available.

**Comment by Chaitanya31612** [comment]
> Implementing something similar to this on the current React Webpage
> ![image](https://user-images.githubusercontent.com/40017559/104852552-b5927800-5921-11eb-86ac-ff8d93a666d7.png)
> https://smaranjitghose.github.io/doc2pen/

@smaranjitghose may I know where is the code for doc2pen.smaranjitghose.codes/ which I can use as reference. As I couldn't find any branch for it?

**Comment by smaranjitghose** [comment]
> > Implementing something similar to this on the current React Webpage
> > ![image](https://user-images.githubusercontent.com/40017559/104852552-b5927800-5921-11eb-86ac-ff8d93a666d7.png)
> > https://smaranjitghose.github.io/doc2pen/
> 
> @smaranjitghose may I know where is the code for doc2pen.smaranjitghose.codes/ which I can use as reference. As I couldn't find any branch for it?

We have it on the `base` branch. However, feel free to go ahead with the work without that reference. When the issue was raised, the react version was not developed into what we have now

**Comment by Chaitanya31612** [comment]
@smaranjitghose please review my pull request #449
