### ISSUE TITLE
REACT: APP UI Update✨

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#403]
Make the UI Similar to Google Docs or Microsoft Word, with the Control panel (horizontally laid out) above the text area. The text area should cover the rest of the screen as in other document or text editors
[Link to the design](https://user-images.githubusercontent.com/59422042/104116049-31e1f580-533b-11eb-8aea-dff38d6c8236.png)

**Comment by ashuvssut** [comment]
I can to work on this. I know the React basics. can you assign me this. I can submit a PR within 5-6 days. 

I am new to React...thats why I am not confident how much time I will take. so 5-6 days will suffice!

**Comment by anushbhatia** [comment]
Suree no problem you can bug us on slack or discord for any doubts if faced.

**Comment by smaranjitghose** [comment]
> I want to work on this. I learned React basics to contribute this project😅. can you assign me this please. I will submit a PR within 5-6 days.
> 
> I am new to React...thats why I am not confident how much time I will take. so 5-6 days will suffice!

Listen @ashuvssut, I surely have no problem with you taking a week for this. However, I would suggest you make daily PRs if not once in two days so that we can give you feedback while you learn.  Because the perfect pr never happens at once, all of us learn by doing mistakes 😊

**Comment by ashuvssut** [comment]
> > I want to work on this. I learned React basics to contribute this project😅. can you assign me this please. I will submit a PR within 5-6 days.
> > I am new to React...thats why I am not confident how much time I will take. so 5-6 days will suffice!
> 
> Listen @ashuvssut, I surely have no problem with you taking a week for this. However, I would suggest you make daily PRs if not once in two days so that we can give you feedback while you learn. Because the perfect pr never happens at once, all of us learn by doing mistakes 😊

Oh I get it! 😁

**Comment by ashuvssut** [comment]
![image](https://user-images.githubusercontent.com/60546840/105343779-eaf3cb80-5b96-11eb-97a2-2603c81907c4.png)

design n colors copied from both Google Docs or Microsoft Word.

@anushbhatia I want our slider to look like as shown
![image](https://user-images.githubusercontent.com/60546840/105344046-4756eb00-5b97-11eb-91b1-5fd405bc2000.png)
**_source: google docs_**
- user can set values accurately (by directly inserting a value in it.)
- It is looks clean. 
-  And, above all it consumes less  space in the navbar.

@anushbhatia Please tell me to if i can use this (replacing the old sliders)

**Comment by ashuvssut** [comment]
> ![image](https://user-images.githubusercontent.com/60546840/105343779-eaf3cb80-5b96-11eb-97a2-2603c81907c4.png)
> 
> design n colors copied from both Google Docs /Microsoft Word.
> 
> @anushbhatia I want our slider to look like as shown
> ![image](https://user-images.githubusercontent.com/60546840/105344046-4756eb00-5b97-11eb-91b1-5fd405bc2000.png)
> **_source: google docs_**
> 
> * user can set values accurately (by directly inserting a value in it.)
> * It is looks clean.
> * And, above all, it consumes less  space in the navbar.
> 
> @anushbhatia Please tell me to if i should use this (replacing the old sliders) or not

@anushbhatia  @smaranjitghose  please give your opinion regarding this. After that, I can work on this.

**Comment by ashuvssut** [comment]
Hello @smaranjitghose , @anushbhatia 

I know that I am late submitting my PR
I just wanted to inform you that I am still working on this issue.

![image](https://user-images.githubusercontent.com/60546840/105741307-fd4f6b80-5eee-11eb-8d06-694f21aa568b.png)

this design is half from Microsoft's doc(layout), and half from google docs (colors and design of button in input  tags)

The code works all fine, but I have observed few bugs. I am trying to fix those.

-------------------


Our new slider looks like as shown
![image](https://user-images.githubusercontent.com/60546840/105344046-4756eb00-5b97-11eb-91b1-5fd405bc2000.png)
**_source: google docs_**
- user can set values accurately (by directly inserting a value in it.)
- It is looks clean. 
-  And, above all, it consumes less  space in the navbar.

**Comment by anushbhatia** [comment]
Sureee

**Comment by ashuvssut** [comment]
@anushbhatia @smaranjitghose, can you please put the level tag for dwoc/swoc
