### ISSUE TITLE
REACT: Add feature to export as PNG, JPG, PDF📄

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#404]
Currently, the site exports image to only png format adds more formats relevant for export in it.

**Comment by Harshita-Kanal** [comment]
Can I try this, I am from SWoC

**Comment by 07yuvraj** [comment]
Can i work on this issue under SWOC and DWOC?

**Comment by Chaitanya31612** [comment]
@anushbhatia I'd like to work on this if it's available.

**Comment by smaranjitghose** [comment]
> @anushbhatia I'd like to work on this if it's available.

The PNG one is already resolved.

The PDF one has a catch.

We have to set the dimensions of each page (to be specific the amount of text it can hold in a single image given all the other parameters), once that exceeds the remainder of the input text should be moved to a new page internally (image) and so one.

The PDF feature would implement this along with converting a batch of images into a PDF
