### ISSUE TITLE
REACT: Add word count feature🔢

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#405]
![image](https://user-images.githubusercontent.com/40017559/104852773-d7402f00-5922-11eb-982a-94c0addc6bfa.png)

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by smaranjitghose** [comment]
> I would Like to work on this.

Deadline: within next 3 days. 
If you need more time after that, let @anushbhatia or me know

**Comment by sanjay270899** [comment]
@smaranjitghose @anushbhatia where should I keep the `word count`?

![image](https://user-images.githubusercontent.com/43892590/105048518-ad594a80-5a91-11eb-8ce2-c966f7dfeddd.png)

**Comment by anushbhatia** [comment]
add it near the drop-down section that would be convenient. If you are facing major issues in it then place it beside the download icon.

**Comment by sanjay270899** [comment]
@anushbhatia and @smaranjitghose Is it fine?
![image](https://user-images.githubusercontent.com/43892590/105165533-78560200-5b3c-11eb-8412-9b99c73e4426.png)

**Comment by sanjay270899** [comment]
@anushbhatia @smaranjitghose we can close this issue if you wish. Thanks.
