### ISSUE TITLE
REACT: Add option to change font color (red, blue, black, green) 🎨

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#406]
Implementing a feature to add different colours of the pen to react app of the website. Having different colours of pen-like blue, green, red, black.
Sample Dropdown is attached. You Can Look Through this.
![image](https://user-images.githubusercontent.com/40017559/104086346-0c8eb200-527d-11eb-8026-03c1cb1394f8.png)

**Comment by anushbhatia** [comment]
@kenkirito do you want to work on this

**Comment by riyasavant** [comment]
Can I work on this?

**Comment by anushbhatia** [comment]
Sure but do give PR

**Comment by smaranjitghose** [comment]
> Can I work on this?

Deadline: within next couple of days
@riyasavant if you require more time after that, do let us know

**Comment by riyasavant** [comment]
Yes sure

**Comment by riyasavant** [comment]
I have added the functionality, but the text color does not seem to change. Attaching screenshots for reference.

![Screenshot (247)](https://user-images.githubusercontent.com/46701530/105039946-3d45c700-5a87-11eb-86a6-ddb7038e6df2.png)
![Screenshot (246)](https://user-images.githubusercontent.com/46701530/105039957-4040b780-5a87-11eb-825f-f8d32e009ed4.png)
![Screenshot (245)](https://user-images.githubusercontent.com/46701530/105039976-43d43e80-5a87-11eb-94d8-eba2303a641a.png)

**Comment by anushbhatia** [comment]
Create a new file if this is having a problem with props and add that to the project. I think this props file is having some issue related to this

**Comment by riyasavant** [comment]
Okay, will try it out

**Comment by sanjay270899** [comment]
@anushbhatia I would Like to work on this.

**Comment by sanjay270899** [comment]
@smaranjitghose You can close this issue if you wish.
