### ISSUE TITLE
Implement React Code Splitting to improve page loadtime

### ISSUE THREAD

**Issue by ashuvssut** [smaranjitghose/doc2pen#407]
refer [here](https://reactjs.org/docs/code-splitting.html) to react code splitting examples.

In Code splitting User only downloads the files related to the page he is visiting instead of loading the entire site's files.
It improves loadtime in react

Right now this app has just one page. so code splitting is not required. But, I will implement code splitting so that in future contributors can add pages that will have this code splitting.

I want to work on this feature. Please assign me this.

--(DWoC and SWoC Participant)

**Comment by ashuvssut** [comment]
After this, I can put a documentation on describing the file structure of this project's current file structure. But, first this Issue's PR is a must to support the documentation.

**Comment by anushbhatia** [comment]
You want to use webpck rollup and Browserify in this too?

**Comment by anushbhatia** [comment]
Sure you can impove the current structure

**Comment by ashuvssut** [comment]
> You want to use webpck rollup and Browserify in this too?

No, actually I dont know about these three. I will look into it.
For now , i will do whatever the [React Code splitting](https://reactjs.org/docs/code-splitting.html) documentation has taught me.

**Comment by anushbhatia** [comment]
> > You want to use webpck rollup and Browserify in this too?
> 
> No, actually I dont know about these three. I will look into it.
> For now , i will do whatever the [React Code splitting](https://reactjs.org/docs/code-splitting.html) documentation has taught me.

okay go ahead

**Comment by smaranjitghose** [comment]
> After this, I can put a documentation on describing the file structure of this project's current file structure. But, first this Issue's PR is a must to support the documentation.

Use Docusaurus or MkDocs for documentation

**Comment by smaranjitghose** [comment]
@ashuvssut This is a great thing to incorporate into our project

**Comment by ashuvssut** [comment]
@smaranjitghose  @anushbhatia please consider my PR for DWoC. I want to get a good ranking in DWoC😅. Just trying to make a good achievements section in my linkedin profile😄
