### ISSUE TITLE
Feature request: Add "ToTop" button on the home page.

### ISSUE THREAD

**Issue by Abhijay007** [smaranjitghose/doc2pen#410]
On the Home page of the doc2pen website add a "to top" button in the bottom right corner of the page

**Comment by ashuvssut** [comment]
I want to work on this. 

will complete this in a day!

**Comment by anushbhatia** [comment]
you both can work on this and collaborate within yourself for it.

**Comment by ashuvssut** [comment]
Sir i have completed this yesterday

**Comment by ashuvssut** [comment]
i just need to open up a pr

**Comment by anushbhatia** [comment]
okay then you both can give PR by that time which UI is better will merge that

**Comment by ashuvssut** [comment]
sir please review my PR

**Comment by Abhijay007** [comment]
> okay then you both can give PR by that time which UI is better will merge that

ok sir 👍
