### ISSUE TITLE
REACT: Enable Routing 📍

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#418]
Implementing Routing
1. Adding homepage as a default page in when opened.
2. Making the navbar to move down on different sections.

**Comment by sanjay270899** [comment]
@anushbhatia Can you please elaborate point 2?

**Comment by smaranjitghose** [comment]
> @anushbhatia Can you please elaborate point 2?

Basically, section-wise navigation for the home page as described by About, Team, Contact in the navbar

**Comment by sanjay270899** [comment]
I would Like to work on this.
