### ISSUE TITLE
Feature request : Drop down on hover 

### ISSUE THREAD

**Issue by Abhijay007** [smaranjitghose/doc2pen#422]
Currently, when a user wants to see the contents of the drop-down menu he/she needs to click on the dropdown.

![before-doc](https://user-images.githubusercontent.com/64387054/105598674-4eaa0e80-5dba-11eb-8df8-32d761d608ed.gif)

I want to suggest a feature that when the user hovers over the dropdown then the contents of the drop-down pops out.

![after-doc](https://user-images.githubusercontent.com/64387054/105601546-1eaf3b00-5dbb-11eb-8fa0-22f7ccec7db1.gif)

**Comment by ashuvssut** [comment]
can i be assigned to this ?

**Comment by Abhijay007** [comment]
closed #422 via #419
