### ISSUE TITLE
Implement a Cool Preloader

### ISSUE THREAD

**Issue by ashuvssut** [smaranjitghose/doc2pen#424]
I wan to implement a cool preloader that i am working right now. It will always appear when pages load. 

It will use just some **simple** css animation😁. NO gif or svg.

would take one day at max

**Comment by anushbhatia** [comment]
A sample if possible

**Comment by ashuvssut** [comment]
I am working on it. I will provide it today only...
Or maybe tomorrow morning

**Comment by anushbhatia** [comment]
Suree

**Comment by ashuvssut** [comment]
Preview : https://vimeo.com/user132135983/review/504920987/2aa26c23d2
