### ISSUE TITLE
Design loading animation when page is loaded.

### ISSUE THREAD

**Issue by Chaitanya31612** [smaranjitghose/doc2pen#427]
As of now when the page is loaded only text saying "Loading Page..." is rendered. It can be improved by adding loading animation.

![image](https://user-images.githubusercontent.com/54992097/106030542-4f151300-60f4-11eb-809b-42f810c9c571.png)

![loadinganim](https://user-images.githubusercontent.com/54992097/106095790-65ee5080-615a-11eb-9f11-b0749391e84d.gif)

I'd like to work on this under SWOC.

**Comment by smaranjitghose** [comment]
> As of now when the page is loaded only text saying "Loading Page..." is rendered. It can be improved by adding loading animation.
> 
> ![image](https://user-images.githubusercontent.com/54992097/106030542-4f151300-60f4-11eb-809b-42f810c9c571.png)
> 
> ![final](https://camo.githubusercontent.com/21435d123ea485c1001e3727dc580fccba8ab40612c94489b3fb65c1a50b1030/68747470733a2f2f696d332e657a6769662e636f6d2f746d702f657a6769662d332d3533323330353534663966352e676966)
> 
> I'd like to work on this under SWOC.

@anushbhatia could you suggest some appropriate animations as well

**Comment by Chaitanya31612** [comment]
> > As of now when the page is loaded only text saying "Loading Page..." is rendered. It can be improved by adding loading animation.
> > ![image](https://user-images.githubusercontent.com/54992097/106030542-4f151300-60f4-11eb-809b-42f810c9c571.png)
> > ![final](https://camo.githubusercontent.com/21435d123ea485c1001e3727dc580fccba8ab40612c94489b3fb65c1a50b1030/68747470733a2f2f696d332e657a6769662e636f6d2f746d702f657a6769662d332d3533323330353534663966352e676966)
> > I'd like to work on this under SWOC.
> 
> @anushbhatia could you suggest some appropriate animations as well

Just to mention the background will be white, it's appearing as such because it has been paused through the debugger.

**Comment by ashuvssut** [comment]
this issue is same as #424.

**Comment by smaranjitghose** [comment]
@Chaitanya31612 @ashuvssut if you are interested in animation related tasks do check out [this project which is also a part of DWOC, SWOC and JWOC](https://github.com/smaranjitghose/awesome-portfolio-websites/issues)

**Comment by smaranjitghose** [comment]
> this issue is same as #424.

I guess not, he is doing this for the editor page

**Comment by Chaitanya31612** [comment]
@smaranjitghose is this loading animation cool or something else needs to be implemented?

**Comment by smaranjitghose** [comment]
> @smaranjitghose is this loading animation cool or something else needs to be implemented?

Check out the example i gave on awesome-portfolio-project for the preloader. A small tweak in design would be nice

**Comment by smaranjitghose** [comment]
@Chaitanya31612 if you are still working on this do raise a new issue
