### ISSUE TITLE
Option for multicolor text in editor.

### ISSUE THREAD

**Issue by Chaitanya31612** [smaranjitghose/doc2pen#429]
There should be an option for multicolor text inside the body itself. Like if the student want to use blue red/green but currently they can only have one color.

![image](https://user-images.githubusercontent.com/54992097/106375578-3c7c3180-63b3-11eb-994b-d4bf6bcbeb35.png)

**Comment by smaranjitghose** [comment]
> There should be an option for multicolor text inside the body itself. Like if the student want to use blue red/green but currently they can only have one color.
> 
> ![image](https://user-images.githubusercontent.com/54992097/106375578-3c7c3180-63b3-11eb-994b-d4bf6bcbeb35.png)

True, this is would be a great addition.
Do you have a proposal on how to implement this?

**Comment by Chaitanya31612** [comment]
> > There should be an option for multicolor text inside the body itself. Like if the student want to use blue red/green but currently they can only have one color.
> > ![image](https://user-images.githubusercontent.com/54992097/106375578-3c7c3180-63b3-11eb-994b-d4bf6bcbeb35.png)
> 
> True, this is would be a great addition.
> Do you have a proposal on how to implement this?

Cool,
Well, will have to figure out a way of implementation of this feature.

**Comment by smaranjitghose** [comment]
Any updates @Chaitanya31612 ?

**Comment by Chaitanya31612** [comment]
> Any updates @Chaitanya31612 ?

Actually @smaranjitghose, I am a bit busy nowadays, you may assign it to someone else if you want.

**Comment by Sakshi0401** [comment]
As a GSSOC'21 Participant I would like to contribute to this. could you please assign this to me?
@smaranjitghose

**Comment by smaranjitghose** [comment]
> As a GSSOC'21 Participant I would like to contribute to this. could you please assign this to me?
> @smaranjitghose

Sure. Could you please raise a new issue for this. So that it does not conflict when I assign you the points for GSSOC

**Comment by Sakshi0401** [comment]
> > As a GSSOC'21 Participant I would like to contribute to this. could you please assign this to me?
> > @smaranjitghose
> 
> Sure. Could you please raise a new issue for this. So that it does not conflict when I assign you the points for GSSOC

sure. Thank you.
