### ISSUE TITLE
REACT: Sketch Page Enhancements✨

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#431]
![image](https://user-images.githubusercontent.com/40017559/106631354-b292bb00-65a2-11eb-8413-0a4ad692970b.png)
Currently, the home page is a really simple functionality in the sketch page
we can add multiple shapes 
Different pen styles
custom images can be dropped on the text area.

**Comment by Deepak8717** [comment]
Hi, Can i take this sir, although i'm first timer .

**Comment by sanjay270899** [comment]
@smaranjitghose @anushbhatia Can I work on this?

I would Like to add the following two features:

1. Change Color
2. Change Width
