### ISSUE TITLE
REACT: Text Overflow Of Cards

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#432]
![image](https://user-images.githubusercontent.com/40017559/106631903-351b7a80-65a3-11eb-9764-ae618af0a214.png)
Adding top margin on this button so that the button has a decent distance between them.

**Comment by sanjay270899** [comment]
@anushbhatia I would Like to work on this.

**Comment by sanjay270899** [comment]
@anushbhatia Its fine or somewhat more down?

![image](https://user-images.githubusercontent.com/43892590/106638155-947c8900-65a9-11eb-9a2f-dfa99021a13c.png)
