### ISSUE TITLE
REACT: Remove our names from contributors🎉

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#433]
In the clan of contributors don't mention our names in it i.e Anush and Smaranjit
![image](https://user-images.githubusercontent.com/40017559/106632309-9d6a5c00-65a3-11eb-8871-fe040698933c.png)

**Comment by sanjay270899** [comment]
@anushbhatia Currently contributors name are coming by fetch through a API. Do you want to keep names static or fetching through API?

**Comment by sanjay270899** [comment]
Ok. I would Like to work on this.
