### ISSUE TITLE
REACT: Unifrom Navbar across all sections

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#438]
![image](https://user-images.githubusercontent.com/40017559/106656501-c816dd80-65c0-11eb-93dd-53fc1bc4f34e.png)
![image](https://user-images.githubusercontent.com/40017559/106656514-cc42fb00-65c0-11eb-888a-839308235507.png)
Keep only 3 tabs as editor specified

**Comment by sanjay270899** [comment]
@anushbhatia But we have made other links in navbar so to direct scroll to that particular section, then why are we removing them now?

**Comment by smaranjitghose** [comment]
> @anushbhatia But we have made other links in navbar so that user can direct scroll to particular section, then why are we removing them now?

We thought about it and came to the conclusion that we want the project to be "To the point with minimum B.S." If someone wants to come to the Editor, we get them there, no need to throw a bloated Navbar

In terms of UX, also it seemed weird to have two different navbars

I hope you understand

**Comment by sanjay270899** [comment]
@smaranjitghose @anushbhatia I have an idea. We can move those extra nav-links to other place. I have made a quick-links box. How is it?
![image](https://user-images.githubusercontent.com/43892590/106776625-41b6d600-666a-11eb-9d08-a107fb050fe1.png)

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia I have an idea. We can move those extra nav-links to other place. I have made a quick-links box. How is it?
> ![image](https://user-images.githubusercontent.com/43892590/106776625-41b6d600-666a-11eb-9d08-a107fb050fe1.png)

That makes sense!
We can go ahead with this.

I had one query. Once we implement this, don't you think having the "toTop" button would be useless (or repetitive) and should be removed?

@anushbhatia @sanjay270899

**Comment by smaranjitghose** [comment]
On the contrary, we can have the quick links box on the right and the "toTop" button towards the left

**Comment by sanjay270899** [comment]
@smaranjitghose I think, still `toTop` is usable, as through quick links we can go up till `about` section. What do you think?
