### ISSUE TITLE
REACT:Improve Navbar 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#439]
Adding a minimal Bootstrap or custom-designed navbar
![image](https://user-images.githubusercontent.com/40017559/106656716-11ffc380-65c1-11eb-8a0e-ac5a057d3c48.png)

**Comment by nehaparmar99** [comment]
I'd like to work on it

**Comment by nehaparmar99** [comment]
Is this fine?

<img width="1440" alt="Screenshot 2021-02-04 at 1 17 27 AM" src="https://user-images.githubusercontent.com/48972593/106800778-e9da9800-6686-11eb-8ee3-3f06dc1d4bfd.png">

**Comment by smaranjitghose** [comment]
> Is this fine?
> 
> <img alt="Screenshot 2021-02-04 at 1 17 27 AM" width="1440" src="https://user-images.githubusercontent.com/48972593/106800778-e9da9800-6686-11eb-8ee3-3f06dc1d4bfd.png">

Check the current changes ones please

**Comment by nehaparmar99** [comment]
> > Is this fine?
> > <img alt="Screenshot 2021-02-04 at 1 17 27 AM" width="1440" src="https://user-images.githubusercontent.com/48972593/106800778-e9da9800-6686-11eb-8ee3-3f06dc1d4bfd.png">
> 
> Check the current changes ones please

oh okay, i'll remove the additional links.

**Comment by nehaparmar99** [comment]
<img width="1440" alt="Screenshot 2021-02-04 at 2 13 48 AM" src="https://user-images.githubusercontent.com/48972593/106807027-ab48db80-668e-11eb-884f-514e04397213.png">
 This is okay? Or should I try something else?

**Comment by smaranjitghose** [comment]
> <img alt="Screenshot 2021-02-04 at 2 13 48 AM" width="1440" src="https://user-images.githubusercontent.com/48972593/106807027-ab48db80-668e-11eb-884f-514e04397213.png">
> 
> @anushbhatia This is okay? Or should I try something else?

Home, Editor, Sketch should be at the same side. UI/UX defacto standards😅

**Comment by nehaparmar99** [comment]
> > <img alt="Screenshot 2021-02-04 at 2 13 48 AM" width="1440" src="https://user-images.githubusercontent.com/48972593/106807027-ab48db80-668e-11eb-884f-514e04397213.png">
> > @anushbhatia This is okay? Or should I try something else?
> 
> Home, Editor, Sketch should be at the same side. UI/UX defacto standards😅

I'll shift home to the right then😅 Also the selected link changes it's color to red.Apart from this, any changes?Or should I make a pr?😅

**Comment by smaranjitghose** [comment]
> > > <img alt="Screenshot 2021-02-04 at 2 13 48 AM" width="1440" src="https://user-images.githubusercontent.com/48972593/106807027-ab48db80-668e-11eb-884f-514e04397213.png">
> > > @anushbhatia This is okay? Or should I try something else?
> > 
> > 
> > Home, Editor, Sketch should be at the same side. UI/UX defacto standards😅
> 
> I'll shift home to the right then😅 Also the selected link changes it's color to red.Apart from this, any changes?Or should I make a pr?😅

Make a PR, because at the end of the day I want your contribution to be a part of the project. If we keep on discussing in the issue, it will take ages for the perfect PR. Rather, on the PR itself, feedback can be given on an iterative basis ( and if required split into two PRs)
