### ISSUE TITLE
REACT: Check it Out button

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#440]
Make it functional and also align it possible.
![image](https://user-images.githubusercontent.com/40017559/106656913-54c19b80-65c1-11eb-9b49-51d97defe449.png)

**Comment by raman-thakur** [comment]
i would like to work on this am I??

**Comment by raman-thakur** [comment]
can i do this??

**Comment by raman-thakur** [comment]
can i do this?? @anushbhatia

**Comment by raman-thakur** [comment]
what this "check it out" button should do??

**Comment by smaranjitghose** [comment]
> what this "check it out" button should do??

Redirect to the Editor page

**Comment by raman-thakur** [comment]
okk i will do that!!

**Comment by raman-thakur** [comment]
I have fixed the issues in my forked local repository what next I need to do?? @smaranjitghose

**Comment by raman-thakur** [comment]
i have done this and requested a pull!! @smaranjitghose @anushbhatia
