### ISSUE TITLE
REACT: Home Page Responsiveness (Mobile View)

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#443]
![responsive](https://user-images.githubusercontent.com/46641503/106787688-06ba9f80-6676-11eb-8040-e5fd3b05cb0d.jpg)

**Comment by ashuvssut** [comment]
please assign me sir

**Comment by smaranjitghose** [comment]
> please assign me sir

Pull the recent changes too

**Comment by ashuvssut** [comment]
okay sir
