### ISSUE TITLE
create a 404 page and also set its route

### ISSUE THREAD

**Issue by ashuvssut** [smaranjitghose/doc2pen#452]
I want to create a nice **interactive** 404 page for our doc2pen webapp

I once created [this](http://blessnbliss.org/404.html) page. I want use that interactive particles to create the 404 page.

**Comment by smaranjitghose** [comment]
> I want to create a nice **interactive** 404 page for our doc2pen webapp
> 
> I once created [this](http://blessnbliss.org/404.html) page. I want use that interactive particles to create the 404 page.

@anushbhatia  please give your inputs w.r.t. to the UI you are planning for

**Comment by ashuvssut** [comment]
ok sir

**Comment by anushbhatia** [comment]
looks good to me but it would be great if you could add a component of document and pen to it

**Comment by ashuvssut** [comment]
![image](https://user-images.githubusercontent.com/60546840/107655221-39493700-6c38-11eb-8285-f759ed193dff.png)
