### ISSUE TITLE
REACT: No. of Contributions

### ISSUE THREAD

**Issue by sanjay270899** [smaranjitghose/doc2pen#458]
I want to add number of contributions by a contributor in `Clan of Contributors`.

Original
![image](https://user-images.githubusercontent.com/43892590/107181461-e8033280-6a00-11eb-913a-46000914dad7.png)

Updated
![image](https://user-images.githubusercontent.com/43892590/107181555-18e36780-6a01-11eb-90a6-5d77df440a3b.png)

**Comment by smaranjitghose** [comment]
> I want to add number of contributions by a contributor in `Clan of Contributors`.
> 
> Original
> ![image](https://user-images.githubusercontent.com/43892590/107181461-e8033280-6a00-11eb-913a-46000914dad7.png)
> 
> Updated
> ![image](https://user-images.githubusercontent.com/43892590/107181555-18e36780-6a01-11eb-90a6-5d77df440a3b.png)

Actually, I did think about this. On the plus side, we get to know which devs were more actively involved with the project but on the other side, quantizing contributions won't be a good idea for a long term. For example, if you gave a single commit (in a PR) and changed a lot of features while someone changed certain content over multiple PRs(2 I mean not beyond that) or a small bug fix, then the quantization of commits won't be fair

**Comment by sanjay270899** [comment]
Yes, your point is valid.
