### ISSUE TITLE
site is not responsive in mobile view

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#46]

**Comment by smaranjitghose** [comment]
Would you like to take up this issue? I would suggest giving different PRs for each of the pages. Also, note the css of the pages is quite messed up. Can have three separate css file for each of the pages?

**Comment by himanshujaidka** [comment]
yes assign this to me @smaranjitghose

**Comment by anushbhatia** [comment]
Please mention these in bugs issue
