### ISSUE TITLE
REACT: Add interactive feedback section in contact us form

### ISSUE THREAD

**Issue by Abhijay007** [smaranjitghose/doc2pen#461]
currently, when the user clicks on the emoji to send feedback then he/she not able to get what they have selected because they all look the same even after selection.

![before-contact form](https://user-images.githubusercontent.com/64387054/107252026-f8e09200-6a5a-11eb-8b68-80c1433dc8ac.gif)

I can make it interactive so that the user can see what he/she selected. 

![after contact us](https://user-images.githubusercontent.com/64387054/107254518-655c9080-6a5d-11eb-8588-8014e3aef6b5.gif)

**Comment by smaranjitghose** [comment]
> currently, when the user clicks on the emoji to send feedback then he/she not able to get what they have selected because they all look the same even after selection.
> 
> ![before-contact form](https://user-images.githubusercontent.com/64387054/107252026-f8e09200-6a5a-11eb-8b68-80c1433dc8ac.gif)
> 
> I can make it interactive so that the user can see what he/she selected.
> 
> ![after contact us](https://user-images.githubusercontent.com/64387054/107254518-655c9080-6a5d-11eb-8588-8014e3aef6b5.gif)

Assigned for 2 days
