### ISSUE TITLE
Home Page Top Section Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#464]
** Improve Mobile Responsiveness**

![mobile_repos](https://user-images.githubusercontent.com/46641503/107267069-68ab4880-6a6c-11eb-8d5c-1cb5cd5f474a.jpg)

**Comment by sanjay270899** [comment]
@smaranjitghose I would Like to work on this.

**Comment by sanjay270899** [comment]
@anushbhatia @smaranjitghose Can I also make Header responsive?

**Comment by smaranjitghose** [comment]
> @anushbhatia @smaranjitghose Can I also make Header responsive?

yup
