### ISSUE TITLE
Nav Bar Design Update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#465]
Custom NavBar using tailwind CSS

**Comment by Amit366** [comment]
@smaranjitghose can I work on this issue?

**Comment by Amit366** [comment]
@smaranjitghose sir how to run the website on my system?

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir how to run the website on my system?

😅.
@Amit366 this is a react project.
Please google how to do run and deploy react projects.

I expect you to have some idea about the codebase before claiming a PR.

**Comment by Amit366** [comment]
https://user-images.githubusercontent.com/60662775/107735608-20b74a80-6d26-11eb-9709-484c0575181b.mp4

**Comment by Amit366** [comment]
@smaranjitghose sir is this fine?

**Comment by sanjay270899** [comment]
@smaranjitghose Just curious. Why we are using tailwind?

**Comment by anushbhatia** [comment]
Nothing specific as of now. We are thinking of moving complete website to next +talwindcss

**Comment by smaranjitghose** [comment]
>  WhatsApp.Video.2021-02-12.at.11.31.09.AM.mp4

Ah..I expect some changes in the UI too , since the issue is about Custom Navbar

For now, just send the PR for this one so that we can verify that the tailwind transition is fine, later on, we can see to the UI improvment

**Comment by Amit366** [comment]
@smaranjitghose everything is fine now but only bug that is the logo and the nav items are not aligned in a line

**Comment by Amit366** [comment]
Can you help me out??

**Comment by smaranjitghose** [comment]
> Can you help me out??

Could you paste a snapshot of your code?

**Comment by Amit366** [comment]
![Screenshot (93)](https://user-images.githubusercontent.com/60662775/108505340-39eb6880-72dd-11eb-815c-9ad88e868378.png)

**Comment by Amit366** [comment]
@smaranjitghose why is this issue closed??

**Comment by anushbhatia** [comment]
The current navbar works fine as of now so we are not going ahead with tailwind one. align meant issue is there on Md branch for it.
