### ISSUE TITLE
note the footer in both ss

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#47]
![Screenshot (38)](https://user-images.githubusercontent.com/58654018/89797176-3dd94980-db48-11ea-8593-7d49070fe0fa.png)
![Screenshot (39)](https://user-images.githubusercontent.com/58654018/89797206-4762b180-db48-11ea-8329-4807633d0757.png)

**Comment by smaranjitghose** [comment]
@himanshujaidka Would you like to fix this? Create a common footer for all the pages?

**Comment by himanshujaidka** [comment]
ok assign this to me @smaranjitghose

**Comment by himanshujaidka** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/58654018/89863084-f514a580-dbc6-11ea-845b-f4e90535a71b.png)

**Comment by himanshujaidka** [comment]
@smaranjitghose tell me if this footer is ok so that I'll create Pr

**Comment by anushbhatia** [comment]
what language have you used for this

**Comment by himanshujaidka** [comment]
Html and css

**Comment by anushbhatia** [comment]
any framework to be specific?

**Comment by himanshujaidka** [comment]
I'll make PR pls refer that
