### ISSUE TITLE
Sketch Page Enhancements

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#474]
# Tasks:

- Format and prettify(I don't imply the extension) the menu/tool bar further with dedicated buttons named "Pen Color", "Pen Width", "Export"
- Increase the canvas size slightly for larger screens
- Have a floating docker on the canvas or maybe options in the menu/tool bar for usual shapes like square, rectangle, circle, ellipse, triangle, diamond, arrow like [this](https://excalidraw.com/)
- Opacity, Stroke, and Fill Settings for the shapes

## Some more specification(s):

- For the stroke style, we need an option for going back to the usual stroke style ( ___) from the other two
- Keep the opacity only for the fill color and not the boundary of the shapes
- For the Fill Color, try to add an option for selecting the color using color picker
- It would be great if you could add some descriptive icons(like Stroke Style, Stroke Width, Opacity, Fill Color, Stroke Color ) so that the menu bar is easy to understand

##### Take up one task at a time.

**Comment by sanjay270899** [comment]
@smaranjitghose I would Like to contribute on Point 3 i.e. shapes.

**Comment by sanjay270899** [comment]
@smaranjitghose small request. I have participant in all three WOCs i.e. DWOC, SWOC and MWOC. So it is possible that my last 2 merged PR can have MWOC labels?

**Comment by smaranjitghose** [comment]
> @smaranjitghose small request. I have participant in all three WOCs i.e. DWOC, SWOC and MWOC. So it is possible that my last 2 merged PR can have MWOC labels?

@sanjay270899 I can surely add the labels brother!. Just check and let me know if those PRs fall within MWOC contribution period.

**Comment by sanjay270899** [comment]
Yes

> > @smaranjitghose small request. I have participant in all three WOCs i.e. DWOC, SWOC and MWOC. So it is possible that my last 2 merged PR can have MWOC labels?
> 
> @sanjay270899 I can surely add the labels brother!. Just check and let me know if those PRs fall within MWOC contribution period.

**Comment by smaranjitghose** [comment]
> Yes
> 
> > > @smaranjitghose small request. I have participant in all three WOCs i.e. DWOC, SWOC and MWOC. So it is possible that my last 2 merged PR can have MWOC labels?
> > 
> > 
> > @sanjay270899 I can surely add the labels brother!. Just check and let me know if those PRs fall within MWOC contribution period.

Done. Check the leaderboard and let me know if there is any discprencies

**Comment by sanjay270899** [comment]
@smaranjitghose I would Like to contribute on Point 4 i.e. Opacity, Fill, and Stroke.

**Comment by smaranjitghose** [comment]
> @smaranjitghose I would Like to contribute on Point 4 i.e. Opacity, Fill, and Stroke.

Sure go ahead!
