### ISSUE TITLE
A well crafted Contribution Guidelines

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#475]
__NOTE__: DO NOT TAKE THIS ASSUMING IT TO BE A BEGINNER ISSUE THAT CAN BE DONE IN A COUPLE OF MINUTES

# REQUIREMENTS.

1. **Section A**: File Structure of the project

- Explain neatly

2.  **Section C**: How to get the Project?

- Install git
- Setup GitHub Account
- Fork 
- Clone
- Move inside the directory
- Set Upstream 
- Pull all the branches from upstream

3. **Section B**: How to set up the project?

-  Basic react stuff ( If anyone copies this line, I am going to mark the PR as spam😅)

4.  **Section C**: How to make changes and contribute to the project?

- Pull changes from Upstream
- Comment on an issue/Raise an issue
- Get it approved by the project maintainers
- Create a new feature branch (DO NOT name it MAIN or MASTER or anything with like `8904thfbn`)
- Do the changes
- Check the outcome
- Make a small clip or take screenshots
- Stage
- Commit
- Push to GitHub (Not to MAIN/MASTER)
- Make a PR

4. **Section D: PR Guidelines**:
- Add Appropriate Title
- Add Appropriate Description
- Screenshots/Clips

** Give an example of the above
- Rebase and Squash Commit if changes are suggested
- Do not comment back on the issue " Please check my PR. Maintainers will have a look as per their convenience"

# General Instructions:

- The above points are for reference. **Do not copy paste exactly!**

- Explain each of the commands with an appropriate description and a follow-up gif (perhaps showing the action) or an illustration

- Use codeblock for the commands

- Emojis are appreciated 

- All the gifs/screenshots/illustrations should be stored in `readme_assets/` with appropriate names

- *Only use Markdown. Refrain from using HTML tags inside Markdown*

**Comment by kanishkaa24** [comment]
Hey! Can I work on this issue?

**Comment by shristi99** [comment]
I want to work on this issue
