### ISSUE TITLE
Improve Website Performance

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#476]
Inspect the performance issues with [GTMetrics](https://gtmetrix.com/reports/doc2pen.smaranjitghose.codes/vjzDo943/) platform and suggest ways ( I mean PRs ofcourse) to improve it

**Comment by ashuvssut** [comment]
is this project using using apache web-server?

I want to add an efficient cache policy. https://gtmetrix.com/serve-static-assets-with-an-efficient-cache-policy.html

**Comment by smaranjitghose** [comment]
> is this project using using apache web-server?
> 
> I want to add an efficient cache policy. https://gtmetrix.com/serve-static-assets-with-an-efficient-cache-policy.html

To the best of my knowledge, we are not using apache and directly hosting on Netlify's servers

**Comment by ashuvssut** [comment]
so which one should I use? 

in this, https://gtmetrix.com/serve-static-assets-with-an-efficient-cache-policy.html,  there is info given how to add an efficient cache policy in  apache, nginx, and Microsoft IIS webservers.

**Comment by ashuvssut** [comment]
here, https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file, it says that we can make a `netlify.toml` specify each individual header rule to implement cache-control.

I have found the cache-control headers from this [stackoverflow answer](https://stackoverflow.com/questions/52308658/netlify-headers-cache-control-for-static-assets/#answer-52323443) for reference. Does this all look okay to you? if yes, then I will start working on it

**Comment by anushbhatia** [comment]
Sure you can add the toml file in this soon

**Comment by smaranjitghose** [comment]
can be done in parallel with #510
