### ISSUE TITLE
all js code is written in html files

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#48]
we need a separate js file for our project

**Comment by smaranjitghose** [comment]
> we need a separate js file for our project

@himanshujaidka  Sorry I couldn't get you. We have the JS files inside the assets subdirectory. Do you mean that?

**Comment by himanshujaidka** [comment]
no inside editor.html and in other Html files I found a little bit of javascript

**Comment by smaranjitghose** [comment]
> no inside editor.html and in other Html files I found a little bit of javascript

I am not sure which part you are referring to? The Google Analytics part? Either way, could you please give a PR for the same so that we can compare the optimization or improvement in readability/modularity of code with your suggestion
