### ISSUE TITLE
Hamburger button doesnt work

### ISSUE THREAD

**Issue by ashuvssut** [smaranjitghose/doc2pen#483]
![Doc2pen - Home](https://user-images.githubusercontent.com/60546840/107695019-e33eb880-6c64-11eb-829d-b2b65170363c.gif)

Hamburger onClick function is not present to expand navbar
I want to work on this issue

**Comment by sanjay270899** [comment]
@ashuvssut I have kept this intentionally, as someone is already updating nav-bar in Issue #465  

(As the nav-bar was making the Top Home Section height more than 100vh in mobile screen so I just hide the nav-links and added a hamburger icon, keeping in the mind that the one who is updating and making new nav-bar will fix this)

**Comment by ashuvssut** [comment]
hey @sanjay270899, the assigned contributor in that issue seems to be a newbie in React. He will take some time to resolve the issue. I think I can give a fix for this (consider it as temporary)
