### ISSUE TITLE
Text is not visible in dark theme

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#49]
# Description the change
text color should be changed in dark-theme

# Screenshots

**Comment by himanshujaidka** [comment]
![blacktext](https://user-images.githubusercontent.com/58654018/89806308-77b04d00-db54-11ea-9694-3be4cd2f6534.png)

**Comment by himanshujaidka** [comment]
pr #50

**Comment by smaranjitghose** [comment]
I would suggest you to separate the css for each of the pages for dark mode
