### ISSUE TITLE
import file function is not working

### ISSUE THREAD

**Issue by shristi99** [smaranjitghose/doc2pen#492]

**Comment by smaranjitghose** [comment]
> _No description provided._

Can you please provide a clip or a screenshot?

Or elaborate more on the error if possible

**Comment by shristi99** [comment]
I am telling that it's only able to import from a text file. 
We can try to import it from any doc and pdf file and give the options to a user to download in .pdf, .doc, .img extensions too.

**Comment by smaranjitghose** [comment]
> I am telling that it's only able to import from a text file.
> We can try to import it from any doc and pdf file and give the options to a user to download in .pdf, .doc, .img extensions too.

Sure, you can go ahead with the implementation for doc or pdf files

**Comment by ashuvssut** [comment]
I found some good packages from npmjs. I would like to give this a try. Please assign me this

**Comment by smaranjitghose** [comment]
> I found some good packages from npmjs. I would like to give this a try. Please assign me this

Sure give it a try

**Comment by ashuvssut** [comment]
I was working on it and I found that the packages I was using wont copy the styles of the page. I will just convert text to pdf 😑. So, I tried to find packages which can copy text with its styles but found none😐

**Comment by shristi99** [comment]
sir could you suggest something as I am also not getting that output from that packages.

**Comment by smaranjitghose** [comment]
> I was working on it and I found that the packages I was using (to generate the pdf) wont copy the styles of the page. It will just convert text to pdf 😑. So, I tried to find packages which can copy text with its styles but found none😐

A workaround can be convert it to png/jpeg, take that and convert to pdf

**Comment by ashuvssut** [comment]
PR: #532  will implement this feature
