### ISSUE TITLE
home styling

### ISSUE THREAD

**Issue by nishant23122000** [smaranjitghose/doc2pen#499]
As per me,we have to change some styling in home page . please grant this issue so that i can work on that

**Comment by smaranjitghose** [comment]
> As per me,we have to change some styling in home page . please grant this issue so that i can work on that

Can you be specific please?

**Comment by nishant23122000** [comment]
Check this design which i change,also I improve the responsive view of website

![Screenshot 2021-02-17 104936](https://user-images.githubusercontent.com/53515714/108160210-ac5a1e00-710e-11eb-9e71-fc23f851ff07.png)
![screenshot-localhost-3000-1613539450825](https://user-images.githubusercontent.com/53515714/108160214-ad8b4b00-710e-11eb-9e3f-5df8b870b4f4.png)

**Comment by anushbhatia** [comment]
> Check this design which i change,also I improve the responsive view of website
> 
> ![Screenshot 2021-02-17 104936](https://user-images.githubusercontent.com/53515714/108160210-ac5a1e00-710e-11eb-9e71-fc23f851ff07.png)
> ![screenshot-localhost-3000-1613539450825](https://user-images.githubusercontent.com/53515714/108160214-ad8b4b00-710e-11eb-9e3f-5df8b870b4f4.png)

Golden colour looks good but it doesn't blend with blue really well if you could find a good combination of blue and golden then we can go ahead with this approach

**Comment by vedant-jain03** [comment]
I have gone through the main website and I think the navbar should have some different styling and I have my own portfolio, and I have also worked on different websites so I think I can work on this issue.
Please assign me so that I can start working on this.

**Comment by smaranjitghose** [comment]
> I have gone through the main website and I think the navbar should have some different styling and I have my own portfolio, and I have also worked on different websites so I think I can work on this issue.
> Please assign me so that I can start working on this.

Could you please raise a new issue with an elaborate  description of the UI change you are proposing
