### ISSUE TITLE
Create a Web_Optimization.MD at the root level of the repo

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#510]
**Only take this issue once you have an understanding of how were optimizing SEO, overall speed, etc**

- Give the heading
- Add an illustration/image(preferably from `Unsplash` but do give a CC)/giphy. Make sure it is suitable
- In bullet points, describe the optimizations performed. Add Code blocks wherever required
- Emaphasis on file image size and formats is also appreciated
- Cite your reference for each point if possible. Use [1], [2], [3] in the bullet points and at the bottom list out the references under a heading references

### SAMPLE

```terminal
# How did we optimize our project so far?

![Some Appropriate Image/Illustration/GIF](https://link-to-a-media-item)

- Suggestion 1
- Suggestion 2
- Suggestion 3 [1] . Suggestion 3 continued [2]
``
Some code to corroborate or illustrate the point
``
- Suggestion 4
- Suggestion 5[3].
.
.
.
- Suggestion n

## References:

[1] [The name of the article/blog/report/video](https://link-to-the-reference) 
[2] [The name of the article/blog/report/video](https://link-to-the-reference) 
.
.
.
[3] [The name of the article/blog/report/video](https://link-to-the-reference) 

```

**Comment by ashuvssut** [comment]
i want to work on this
