### ISSUE TITLE
Improve 404 page UI

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#511]
### **Feel free to work as per your ideas. We do not have any specifications for this.**

- You can take inspirations from platforms like Dribble, Codepen, etc but **DO NOT COPY PASTE THE EXACT THING**
- Make sure the routing is not messed up
- Try out if the 404 functionality is working before giving the PR

The issue is self-explanatory given one has read the above points. Looking forward to your design tweaks!

**Comment by ashuvssut** [comment]
I want to work on this

**Comment by smaranjitghose** [comment]
> I want to work on this

Assigned for 3 days. The deadline can be extended if required.

**Comment by ashuvssut** [comment]
I just need 1 day more to finish off

**Comment by Aniket118** [comment]
I would like to work on this issue @smaranjitghose

**Comment by dollyjain51099** [comment]
I would like to work on this issue, @smaranjitghose kindly assign it to me!

**Comment by smaranjitghose** [comment]
@dollyjain51099 @Aniket118 We are making this an open-to-all issue, feel free to give PRs based upon your own design intuitions
