### ISSUE TITLE
Add Pagination functionality so that we can download our text as a sequence of multiple images

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#513]
[Reference](https://github.com/gokhalehemal11/Text-to-custom-Handwriting-Converter)

DO NOT COPY PASTE DIRECTLY. Rather, understand the code and try to re-implement for our case.

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by niteshsinha17** [comment]
@smaranjitghose I would like to implement this feature. I believe I can do it. Please assign it to me.
