### ISSUE TITLE
Download as PDF option

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#514]
[Reference](https://github.com/gokhalehemal11/Text-to-custom-Handwriting-Converter)

DO NOT COPY PASTE DIRECTLY. Rather, understand the code and try to re-implement for our case.

**Comment by Bhavik-Ardeshna** [comment]
Hello @smaranjitghose  I want to work on this issue for GSSoC'21
Plz assign issue to me

**Comment by ashuvssut** [comment]
> Hello @smaranjitghose I want to work on this issue for GSSoC'21
> Plz assign issue to me

Hello @Bhavik-Ardeshna, I also asked sir if my current PRs will count towards GSSOC or not... but sir replied that GSSOC contributions will be counted only after GSSOC starts. So for solving issues, sir would not wait for March😅. So, if you want to contribute now -- its great!, else its completely fine to give your PRs when GSSOC starts.😄

Btw, bro, I have also participated in GSSOC😁

**Comment by ashuvssut** [comment]
> Hello @smaranjitghose I want to work on this issue for GSSoC'21
> Plz assign issue to me

Hello @Bhavik-Ardeshna, I also asked sir if my current PRs will count towards GSSOC or not... but sir replied that GSSOC contributions will be counted only after GSSOC starts. So for solving issues, sir would not wait for March😅. So, if you want to contribute now -- its great!, else its completely fine to give your PRs when GSSOC starts.😄

Btw, bro, I have also participated in GSSOC😁

looking forward for your contribution in doc2pen brother!

**Comment by Bhavik-Ardeshna** [comment]
Sure , our main aim is learning....I would love to contribute in doc2open
