### ISSUE TITLE
Contribute custom fonts

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#516]
## Some Specifications:

- We would be using the free tier of Caligraphr for this.

- [Guide to use it](https://www.youtube.com/watch?v=DNfrcJldEVI)

- If you are not comfortable with Hindi(the language of the above video), either play the video on mute or search on Youtube with similar titles.  It won't be much of a challenge rather something really interesting especially for the ones with a creative outlook.

- Be cautious of the "dots" in each tile of the template while you fit your letters

- Double-check the special characters ( `#`,`$`,`%`,`^`,`&`,`*`,`(`,`)`,`-`,`_`,`+`,`=`,`{`,`}`,`[`,`]`,`:`,`;`,`"`,`'`,`<`,`>`,`?`, `/`,`~`,`.`,`,`,`` ` ``). These tend to mess up the font rendering process to a great extent.

- True Type format is preferred

## Note:

- **This issue solely intended for custom fonts. Do not give anything that is already available online**
- This is a non-profit open-source project. All the contributors would be accredited in the readme for their respective fonts.  
- You can take your friends' handwritings to make fonts as well provided you have their consent and acknowledge that in the PR.

**Comment by Mukta-Sawant** [comment]
I would like to work on this issue, please assign it to me.

**Comment by Mukta-Sawant** [comment]
@smaranjitghose Can I work on this issue? Please assign it to me.

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by stuti-ui** [comment]
Hi, Can you please assign this issue to me?

**Comment by smaranjitghose** [comment]
Do read the Requirements above carefully before giving a PR

**Comment by chanchalap06** [comment]
Can I work on this issue

**Comment by Nishayadav-bit** [comment]
Hey ! Can you please assign this issue to me ?

**Comment by mansijain980** [comment]
@smaranjitghose sir , I worked on cam scanner like app in which i changed the hand writing of one person to another and make a pdf of that . 
Please assign it to me . 
AS i have already worked on it .

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir , I worked on cam scanner like app in which i changed the hand writing of one person to another and make a pdf of that .
> Please assign it to me .
> AS i have already worked on it .

Please read the issue description carefully. Your idea does not seem to fall in line with that. However, you can raise an issue for it separately

**Comment by Mukta-Sawant** [comment]
@smaranjitghose Can you please assign this issue to me under GSSOC'21?

**Comment by chanchalap06** [comment]
@smaranjitghose Do we have to just submit the .ttf file?  I understood how to make the font but I'm confused about how to submit it

**Comment by Rayman-Sodhi** [comment]
Hi, can you please assign me this issue under the label GSSOC'21

**Comment by smaranjitghose** [comment]
Each of you have 1 week from the time of your assignment to complete your PR

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by hritikgupta92** [comment]
I would also like to work on this issue.Please assign this to me

**Comment by Rayman-Sodhi** [comment]
Hi, I was working on this issue, but I see it has been closed, so should I complete making the font or not?

**Comment by smaranjitghose** [comment]
> Hi, I was working on this issue, but I see it has been closed, so should I complete making the font or not?

Don't worry this is open

**Comment by hritikgupta92** [comment]
@smaranjitghose  please check #737

**Comment by Rayman-Sodhi** [comment]
@smaranjitghose  Kindly check #738

**Comment by hritikgupta92** [comment]
@smaranjitghose  please check #742

**Comment by Ankita297** [comment]
Can i work on this @smaranjitghose ?

**Comment by Ankita297** [comment]
@smaranjitghose  ?

**Comment by Ankita297** [comment]
Can i work on this @smaranjitghose ?

**Comment by sharvariiii** [comment]
Can I also be part of this .Would love to contribute my bit as GSSOC participant 21.

**Comment by anushbhatia** [comment]
Sure
