### ISSUE TITLE
Dynamic Favicon

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#518]
**Your creativity is the upper limit here**. 
- However, do not change the favicon for every mouse click 🙏. 
- 404 page can have a different favicon
- Dark mode and light modes can have different favicons

References:

- [GeeksforGeeks article](https://www.geeksforgeeks.org/how-to-change-favicon-dynamically/)
- [Medium Blog](https://medium.com/@alperen.talaslioglu/building-dynamic-favicon-with-javascript-223ad7999661)

**Comment by Harshal0902** [comment]
@smaranjitghose can you please assign this issue to me?
I would like to work on this issue.

**Comment by Harshal0902** [comment]
@anushbhatia, Shall I add a common favicon to the website, or different favicon for different webpages?

**Comment by anushbhatia** [comment]
Common as of now
