### ISSUE TITLE
Dynamic Page Titles

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#519]
[Reference](https://medium.com/@alperen.talaslioglu/changing-page-title-dynamically-when-user-changes-tab-5d372554377c)

The above reference is well detailed. Please go through it carefully if you wish to contribute to this.

**Comment by smriti1313** [comment]
Hi, I am an DWoC participant who would like to contribute in this. Can you tell me the scenarios when should the title change?
Like:
1. When user switches the tab.
2. when multiple docpen tabs are open.

any other case?

**Comment by anushbhatia** [comment]
Work on 1st on only.

**Comment by smaranjitghose** [comment]
@smriti1313 Assigned for 2 days

**Comment by ashuvssut** [comment]
If by any chance, Assignee fails to submit PR, I would like to work on this issue

**Comment by smriti1313** [comment]
Hi, sorry i could not do it in 2 days. Please give the other person the chance.
Thank you

**Comment by ashuvssut** [comment]
@smaranjitghose , @anushbhatia , what do you want in attention message on the tab title?

**Comment by smaranjitghose** [comment]
> @smaranjitghose , @anushbhatia , what do you want in attention message on the tab title?

Simple, if the user opens another tab then there should be a message saying "Come Back" in the title. Check the reference

**Comment by ashuvssut** [comment]
please assign me this issue
