### ISSUE TITLE
Text File remove from textarea

### ISSUE THREAD

**Issue by nishant23122000** [smaranjitghose/doc2pen#521]
When we upload new TXT file then it's work fine but when we change font color,change sheet etc after file upload then the current file removed autometicly . 
As per me this is bad UX.Becasue there might be case where user want to change some parameter after he upload file.

So we sould persist the file if user made any change in any parameter

**Comment by asimaries** [comment]
I  would like to work on this

**Comment by nishant23122000** [comment]
> I would like to work on this

I already did it.i'm just waiting for mentor response
