### ISSUE TITLE
Sketch: Undo & Redo

### ISSUE THREAD

**Issue by sanjay270899** [smaranjitghose/doc2pen#531]
Option to undo and redo the changes in Sketch.

**Comment by sanjay270899** [comment]
@smaranjitghose @anushbhatia I would Like to work on this.

**Comment by ashuvssut** [comment]
@sanjay270899 Actually I wanted to implement a erase feature.

can you write your code such that:---
for example you have drawn 4 different lines and then You can remove the 2th line by just clicking on that line. 

like when `isDrawing==true` , in `handleMouseMove()` function, you can add some lines of code that stores the coordinates of the point being drawn
You will be doing this for all lines.

then an array will be created like
```js

drawnLines=[
    [{x: 2, y:3}, {x: 3, y:3}, {x: 4, y:3}, {x: 5, y:3}.................],                //drawnLine1 coordinates
    [{x: 2, y:4}, {x: 3, y:5}, {x: 4, y:6}, {x: 5, y:7}.................],                //drawnLine2 coordinates
    [{x: 2, y:6}, {x: 3, y:7}, {x: 4, y:8}, {x: 5, y:9}.................],                //drawnLine3 coordinates
    [{x: 1, y:3}, {x: 2, y:3}, {x: 3, y:3}, {x: 4, y:3}.................],                //drawnLine4 coordinates
]
```

after that I can create a function `Erase()` in `onMouseDown()` function that will search for that point's coordinates that is being clicked(to erase a whole line) in all line arrays present in `drawnLines` array. and the coordinates present the array(representing a drawnLine) will be again given a transparent/white color stroke to erase.

**Comment by sanjay270899** [comment]
> @sanjay270899 Actually I wanted to implement a erase feature.
> 
> can you write your code such that:---
> for example you have drawn 4 different lines and then You can remove the 2nd line by just clicking on that line.
> 
> > **EDIT**: I just realized that the logic given below will only erase lines and not shapes 😥. Any suggestions will be really helpful
> 
> like when `isDrawing==true` , in `handleMouseMove()` function, you can add some lines of code that stores the coordinates of the points being drawn
> You will be doing this for all lines.
> 
> then an array will be created like
> 
> ```js
> drawnLines=[
>     [{x: 2, y:3}, {x: 3, y:3}, {x: 4, y:3}, {x: 5, y:3}.................],     //drawnLine1 coordinates
>     [{x: 2, y:4}, {x: 3, y:5}, {x: 4, y:6}, {x: 5, y:7}.................],     //drawnLine2 coordinates
>     [{x: 2, y:6}, {x: 3, y:7}, {x: 4, y:8}, {x: 5, y:9}.................],     //drawnLine3 coordinates
>     [{x: 1, y:3}, {x: 2, y:3}, {x: 3, y:3}, {x: 4, y:3}.................],     //drawnLine4 coordinates
> ]
> ```
> 
> after that I can create a function `Erase()` in `onMouseDown()` function that will search for that point's coordinates that is being clicked(to erase a whole line) in all line arrays present in `drawnLines` array. and the coordinates present in the array(representing a drawnLine) will be again given a transparent/white color stroke to erase.

I will look into it.
