### ISSUE TITLE
Adding an erase feature in Sketch

### ISSUE THREAD

**Issue by shruthii625** [smaranjitghose/doc2pen#535]
1. An eraser would provide a quick way to erase the mistakes rather than the user having to delete the entire drawing.
2. An eraser would let users erase small portions of the shapes and let them make more dynamic drawings. They wouldn't have to stick to just the basic shapes provided.

**Comment by shruthii625** [comment]
@smaranjitghose @anushbhatia  
I'd like to work on this as GSSOC mentee.

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia
> I'd like to work on this as a GSSOC mentee.

Assigned for 4 days

**Comment by shruthii625** [comment]
> > @smaranjitghose @anushbhatia
> > I'd like to work on this as a GSSOC mentee.
> 
> Assigned for 4 days

I've added the eraser. Let me know if the eraser needs to be enhanced in any other way!
