### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#54]
- [ ] Responsiveness
- [ ]  Card Structure

**Comment by arnoob16** [comment]
I can work on the responsiveness of the project.

**Comment by rutujadhanawade** [comment]
Will you please explain what do u mean by card structure? I would like to work on this issue.

**Comment by debanshu08** [comment]
I can work on Responsiveness of the project.

**Comment by anushbhatia** [comment]
Editor page is not responsive as canvas is called from the js function.

**Comment by anushbhatia** [comment]
Home Page has cards that can be improved that are not looking good.

**Comment by rutujadhanawade** [comment]
I can work on improving card structure.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by smaranjitghose** [comment]
> Can I work on this issue?

@srishtij2000  Can you please point out the bugs you wish to fix

**Comment by srishtij2000** [comment]
I can work on improving the card structure

**Comment by smaranjitghose** [comment]
> I can work on improving the card structure

It's already assigned to @rutujadhanawade for 2 more days. After that, you can contribute

**Comment by srishtij2000** [comment]
Okay
