### ISSUE TITLE
Type Error produced due to scroll to top button

### ISSUE THREAD

**Issue by niteshsinha17** [smaranjitghose/doc2pen#543]
### Steps to produce

1. Go to home page.
2. Scroll down a little bit and make sure ``scroll to top`` button is visible on the page.
3. Change page by clicking on ``Editor``. 
Now, you will be able to see this error on the page.
![WhatsApp Image 2021-02-21 at 9 51 17 PM](https://user-images.githubusercontent.com/42765292/108631332-7a8ae380-748f-11eb-81a9-c6f6b3fc7915.jpeg)

**Comment by niteshsinha17** [comment]
I have participated in GGSOC and I have found this Issue. Can you please assign this issue to me. I would like to solve this.

**Comment by ashuvssut** [comment]
@smaranjitghose, I have fixed this today.

If assigned, I will submit PR today only😁😁

**Comment by ashuvssut** [comment]
@smaranjitghose, I fixed this today.

If assigned, I will submit PR today only😁😁

**Comment by niteshsinha17** [comment]
@ashuvssut Actually I had also solved this Issue when I opened this. I was waiting for someone to reply.

**Comment by ashuvssut** [comment]
@niteshsinha17 nice! You can submit your PR now. Keep in mind to link this issue in ur PR!

BTW I have also participated for GSSoC

Looking forward for your contribution to doc2pen brother!

**Comment by ashuvssut** [comment]
@niteshsinha17 Your GSSoC contribution will be counted only after GSSoC event starts.

For now just get comfortable with doc2pen codebase by resolving opened issues!

**Comment by niteshsinha17** [comment]
> @niteshsinha17 Your GSSoC contribution will be counted only after GSSoC event starts.
> 
> For now just get comfortable with doc2pen codebase by resolving opened issues!

I have no program with the count. Contribution is more important for me whether it is today or tomorrow. Thanks
