### ISSUE TITLE
Add redux

### ISSUE THREAD

**Issue by niteshsinha17** [smaranjitghose/doc2pen#544]
This is a suggestion to use redux to manage state as redux can handle state more efficiently.
We can add it now or we can add it in future. It will be great if we add it in ``package.json`` for now and we can open some small issues to manage state through redux for some particular components. 

What do you think?

**Comment by ashuvssut** [comment]
for state management we are using React Context Api

**Comment by anushbhatia** [comment]
For what feature do we need redux. Which state management module will you enhance with it.

**Comment by niteshsinha17** [comment]
@anushbhatia 
As I mentioned in the Issue that it's a suggestion. Also as the project will grow complexities will also increase so I think redux can handle those complexities very easily.  Apologies for the late reply.

**Comment by smaranjitghose** [comment]
We can go for this in a later stage of the project as we have plans to shift to next
