### ISSUE TITLE
Sketch: Labels on Hover

### ISSUE THREAD

**Issue by sanjay270899** [smaranjitghose/doc2pen#556]
Adding Labels on Hover will help users to get to know about the feature.

![image](https://user-images.githubusercontent.com/43892590/109044668-ae1c7680-76f8-11eb-8098-0ff144cc1a0a.png)

**Comment by smaranjitghose** [comment]
> 
> 
> Adding Labels on Hover will help users to get to know about the feature.
> 
> ![image](https://user-images.githubusercontent.com/43892590/109044668-ae1c7680-76f8-11eb-8098-0ff144cc1a0a.png)

## Additional Suggestion:
Try to experiment with some colorful flaticons to replace the current ones. [Example](https://www.flaticon.com/search?search-type=icons&word=pencil)

**Comment by sanjay270899** [comment]
@smaranjitghose I have added Labels.

For icons, can you elaborate more?
(Do I have to add colorful icons?, If so, then maybe for dark mode, we have to use different color icons)

**Comment by sanjay270899** [comment]
@smaranjitghose I spend more than 1 hour. But didn't able to find perfect icons.

By chance if I get a nice icon, then finding similar icon for rest other shapes is very difficult.

**Comment by Riya764** [comment]
Can I work on this as part of GSSOC'21 ?

**Comment by sanjay270899** [comment]
@Riya764 Label Part is over. You can work on finding new good looking icons.

**Comment by smaranjitghose** [comment]
> @Riya764 Label Part is over. You can work on finding new good looking icons.

In case you do so, raise a new issue please
