### ISSUE TITLE
Implement eraser using clearRect()

### ISSUE THREAD

**Issue by shruthii625** [smaranjitghose/doc2pen#560]

**Comment by shruthii625** [comment]
@smaranjitghose @anushbhatia 
as @sanjay270899 had mentioned, using clearRect() does seem like a better solution as the previous solution doesn't work for all canvas backgrounds. I'd like to implement the eraser using clearRect(). Can you assign it to me?

**Comment by smaranjitghose** [comment]
Closed due to inactivity
