### ISSUE TITLE
Few issues with the font styling

### ISSUE THREAD

**Issue by akshitadixit** [smaranjitghose/doc2pen#565]
1. As can be seen in the image below the capital A just looks like a resized version of the small a.

![image](https://user-images.githubusercontent.com/56997545/109807597-1f55af80-7c4c-11eb-99bd-a986efb8f34b.png)

2. To make the handwriting look as possibly close to real life as it can be, doc2pen should detect all caps letters that are placed together to not change into cursive as shown in the image below. 

![image](https://user-images.githubusercontent.com/56997545/109808082-b458a880-7c4c-11eb-8df1-2c5ec41787c1.png)

**Comment by smaranjitghose** [comment]
> 1. As can be seen in the image below the capital A just looks like a resized version of the small a.
> 
> ![image](https://user-images.githubusercontent.com/56997545/109807597-1f55af80-7c4c-11eb-99bd-a986efb8f34b.png)
> 
> 1. To make the handwriting look as possibly close to real life as it can be, doc2pen should detect all caps letters that are placed together to not change into cursive as shown in the image below.
> 
> ![image](https://user-images.githubusercontent.com/56997545/109808082-b458a880-7c4c-11eb-8df1-2c5ec41787c1.png)

I agree.

We are planning to make custom fonts as a workaround for this as well. Would you be interested to contribute to that as well?

**Comment by akshitadixit** [comment]
Yes definitely. Kindly guide me around.

**Comment by smaranjitghose** [comment]
@akshitadixit could you please check out #516

**Comment by akshitadixit** [comment]
Yes understood, thank you. Working on this.

**Comment by akshitadixit** [comment]
@smaranjitghose could u please confirm that all I submit in the PR is a ttf file?

**Comment by smaranjitghose** [comment]
> @smaranjitghose could u please confirm that all I submit in the PR is a ttf file?

Yup

**Comment by akshitadixit** [comment]
It's almost done @mpriti23 thank you for the help :)

**Comment by smaranjitghose** [comment]
> If the problem is not yet resolved I would really like to contribute to this to resolve the issues with capital letters. If done , I can also go for customization.

Irrespective of this issue, feel free to contribute to #516
