### ISSUE TITLE
[GSSOC'21] Option for multicolor in sketch.

### ISSUE THREAD

**Issue by Sakshi0401** [smaranjitghose/doc2pen#575]
@smaranjitghose There should be an option for multicolor. As a GSSOC'21 participant I would like to work upon this issue. Could you please assign this to me?

**Comment by av-0901** [comment]
I can do this work. I am a GSSoC participant. Kindly assign me this

**Comment by Sakshi0401** [comment]
@smaranjitghose How many color options should be there? Shall I consider Red, Green, Blue Yellow for now

**Comment by smaranjitghose** [comment]
> @smaranjitghose How many color options should be there? Shall I consider Red, Green, Blue Yellow for now

Yes.
Black, Blue, Red, Green

**Comment by Sakshi0401** [comment]
> > @smaranjitghose How many color options should be there? Shall I consider Red, Green, Blue Yellow for now
> 
> Yes.
> Black, Blue, Red, Green

Okay Thanks

**Comment by Sakshi0401** [comment]
Hey @smaranjitghose  I have done all the necessary changes. Let me know if there are any further modifications required.

![image](https://user-images.githubusercontent.com/64726139/111027061-deac2200-8413-11eb-8754-401c8e6cabb9.png)

**Comment by smaranjitghose** [comment]
Communicated in the respective issue
