### ISSUE TITLE
Adding a Testimonials section for a quick impression.

### ISSUE THREAD

**Issue by shalmoly79** [smaranjitghose/doc2pen#576]
Hello doc2pen, I am a GSSOC'21 participant. There is a common proverb that says "You only get one chance to make a first impression.". A testimonials section on how users got benefitted using doc2pen will create further reach, add legitimacy to this website and will help attracting target audiences. If you find this issue helpful, please grant me the chance to contribute to this awesome project. Thanks in advance.

**Comment by Priyanka7011** [comment]
Hii I am a GSSOC 2021 participant.
I would love to work on this issue.
Please assign me .
Thank You !

**Comment by smaranjitghose** [comment]
We can come this towards the end of the program
