### ISSUE TITLE
Change the logo design

### ISSUE THREAD

**Issue by neha-baisane** [smaranjitghose/doc2pen#578]
The current logo is quite unattractive . As a GSSOC'21 participant I would like to change the logo so that user will get idea what exactly the we app is all about by just looking at the logo.

**Comment by Priyanka7011** [comment]
hii, I am a GSSOC participant.
I have good experience in graphic designing . I can design a new logo for the website.

Can you please assign me this.

Thank You

**Comment by chanchalap06** [comment]
I can animate the logo if any of the above people design it. I am a GSSOC participant, please assign this to me

**Comment by Priyanka7011** [comment]
Thank you I will start working on it !!

**Comment by chanchalap06** [comment]
> Thank you I will start working on it !!

can you let me know when you're done?

**Comment by smaranjitghose** [comment]
@neha-baisane I do agree.
By LOGO do you mean the favicon only or the image in the top section?

@Priyanka7011 @chanchalap06 @neha-baisane All three of you can independently give PRs for the LOGO. We would merge one or all of them based upon the level of improvement and conformity to the goals of the project.

Also, we need some contributions w.r.t. project banner image, project card (github repo), contribution guidelines. All of these are design-related issues. Feel free to raise them and let us know if you are interested in working on them,

**Comment by Priyanka7011** [comment]
> > Thank you I will start working on it !!
> 
> can you let me know when you're done?

Yes sure ! I will let you know when I am done with the logo design .

**Comment by Priyanka7011** [comment]
> @neha-baisane I do agree.
> By LOGO do you mean the favicon only or the image in the top section?
> 
> @Priyanka7011 @chanchalap06 @neha-baisane All three of you can independently give PRs for the LOGO. We would merge one or all of them based upon the level of improvement and conformity to the goals of the project.
> 
> Also, we need some contributions w.r.t. project banner image, project card (github repo), contribution guidelines. All of these are design-related issues. Feel free to raise them and let us know if you are interested in working on them,

I am good at making digital illustrations. So if you need illustrations as design element .I will be more than happy to contribute for it. 
Thank You

**Comment by chanchalap06** [comment]
I want to animate the logo not design it, I am not experienced in designing so I am willing to work on any logo the others design

**Comment by neha-baisane** [comment]
@smaranjitghose I meant to change the favicon. Thanks for assigning the task.

**Comment by neha-baisane** [comment]
> > @neha-baisane I do agree.
> > By LOGO do you mean the favicon only or the image in the top section?
> > @Priyanka7011 @chanchalap06 @neha-baisane All three of you can independently give PRs for the LOGO. We would merge one or all of them based upon the level of improvement and conformity to the goals of the project.
> > Also, we need some contributions w.r.t. project banner image, project card (github repo), contribution guidelines. All of these are design-related issues. Feel free to raise them and let us know if you are interested in working on them,
> 
> I am good at making digital illustrations. So if you need illustrations as design element .I will be more than happy to contribute for it.
> Thank You

Agreed

**Comment by neha-baisane** [comment]
> @neha-baisane I do agree.
> By LOGO do you mean the favicon only or the image in the top section?
> 
> @Priyanka7011 @chanchalap06 @neha-baisane All three of you can independently give PRs for the LOGO. We would merge one or all of them based upon the level of improvement and conformity to the goals of the project.
> 
> Also, we need some contributions w.r.t. project banner image, project card (github repo), contribution guidelines. All of these are design-related issues. Feel free to raise them and let us know if you are interested in working on them,

Agreed

**Comment by smaranjitghose** [comment]
> I want to animate the logo not design it, I am not experienced in designing so I am willing to work on any logo the others design

Cool

**Comment by preetiahuja18** [comment]
_I want to design the logo. I have done designing  so please assign this to me under GSSOC'21 participant. and I wiil surely give my best.._

**Comment by smaranjitghose** [comment]
> _I want to design the logo. I have done designing so please assign this to me under GSSOC'21 participant. and I wiil surely give my best.._
> ![doc2pen](https://user-images.githubusercontent.com/72223546/110848354-01cfb800-82d4-11eb-873c-dd54b8367caf.jpg)
> please give feedback for this logo.. @smaranjitghose

@anushbhatia

**Comment by chanchalap06** [comment]
![Comp 6_1](https://user-images.githubusercontent.com/69527629/111021206-c7a80880-83f0-11eb-9c4e-8389d0b07a24.gif)
I made this, please provide feedback

**Comment by chanchalap06** [comment]
![Comp 7](https://user-images.githubusercontent.com/69527629/111023588-eb267f80-83ff-11eb-9e05-a2b390fc9c24.gif)
![logo](https://user-images.githubusercontent.com/69527629/111023593-f11c6080-83ff-11eb-89b0-6bebb89875cc.gif)
I made these two, please provide feedback

**Comment by preetiahuja18** [comment]
> _I want to design the logo. I have done designing so please assign this to me under GSSOC'21 participant. and I wiil surely give my best.._
> ![doc2pen](https://user-images.githubusercontent.com/72223546/110848354-01cfb800-82d4-11eb-873c-dd54b8367caf.jpg)
> please give feedback for this logo.. @smaranjitghose

please give feedback @anushbhatia

**Comment by anushbhatia** [comment]
> > _I want to design the logo. I have done designing so please assign this to me under GSSOC'21 participant. and I wiil surely give my best.._
> > ![doc2pen](https://user-images.githubusercontent.com/72223546/110848354-01cfb800-82d4-11eb-873c-dd54b8367caf.jpg)
> > please give feedback for this logo.. @smaranjitghose
> 
> @anushbhatia

This looks more like a person working office and using wifi. doesn't seem to relate your app in any case.

**Comment by anushbhatia** [comment]
> ![Comp 7](https://user-images.githubusercontent.com/69527629/111023588-eb267f80-83ff-11eb-9e05-a2b390fc9c24.gif)
> ![logo](https://user-images.githubusercontent.com/69527629/111023593-f11c6080-83ff-11eb-89b0-6bebb89875cc.gif)
> I made these two, please provide feedback

This looks good to me but the logo is not that catchy thou the animations are pretty dope. I will attach some samples down so that you can look through them.

**Comment by anushbhatia** [comment]
https://dribbble.com/shots/14396329-Document-Logo
![ezgif com-gif-maker-01](https://user-images.githubusercontent.com/40017559/111078769-29659100-851d-11eb-8761-4235cba60b1d.png)

**Comment by smaranjitghose** [comment]
> ![Comp 7](https://user-images.githubusercontent.com/69527629/111023588-eb267f80-83ff-11eb-9e05-a2b390fc9c24.gif)
> ![logo](https://user-images.githubusercontent.com/69527629/111023593-f11c6080-83ff-11eb-89b0-6bebb89875cc.gif)
> I made these two, please provide feedback

I really appreciate the efforts behind this. But the animation is way too much. perhaps just writing doc2pen on the book works and we can let go of the background and border animations

**Comment by smaranjitghose** [comment]
@all checkout the recent issues raised w.r.t. adding icons to the sketch page. I believe most of your skills would serve as an asset to those

**Comment by chanchalap06** [comment]
![final](https://user-images.githubusercontent.com/69527629/111089017-eec91c00-854f-11eb-9460-8c2ecafa4aad.gif)
@smaranjitghose I removed the border and the background animation

**Comment by smaranjitghose** [comment]
> ![final](https://user-images.githubusercontent.com/69527629/111089017-eec91c00-854f-11eb-9460-8c2ecafa4aad.gif)
> @smaranjitghose I removed the border and the background animation

Much better!
You can change the background to a lighter shade of sea blue or gray ( Experiment a bit). The black one is distracting

**Comment by chanchalap06** [comment]
@smaranjitghose Okay, I'll change that

**Comment by vedikaag99** [comment]
@smaranjitghose @anushbhatia can I also give this issue a try?

**Comment by anushbhatia** [comment]
sure

**Comment by vedikaag99** [comment]
![Add a heading](https://user-images.githubusercontent.com/67699840/111122035-771ce080-8593-11eb-8881-06bff8341da3.png)
Please review. @anushbhatia @smaranjitghose

**Comment by neha-baisane** [comment]
is it alright to do the task before hand even before assigning it to a particular participant?

**Comment by chanchalap06** [comment]
@smaranjitghose changed the background to a gradient of grey
![grey](https://user-images.githubusercontent.com/69527629/111139886-ae958800-85a7-11eb-94ee-124e1497844e.gif)

**Comment by anushbhatia** [comment]
@priyank and @neha-baisane any updates

**Comment by anushbhatia** [comment]
> @smaranjitghose changed the background to a gradient of grey
> ![grey](https://user-images.githubusercontent.com/69527629/111139886-ae958800-85a7-11eb-94ee-124e1497844e.gif)

this looks good to me generate the SVG for the file and add that to the project

**Comment by Priyanka7011** [comment]
![logoDesigns](https://user-images.githubusercontent.com/54627940/111530140-f4f60d00-8788-11eb-8bab-e906ea842c17.png)
Sorry for responding late .

**Comment by smaranjitghose** [comment]
@Priyanka7011 This won't look good for smaller sizes

**Comment by smaranjitghose** [comment]
Closed due to inactivity
