### ISSUE TITLE
Improving Documentation (README.md)

### ISSUE THREAD

**Issue by Priyanshu-U** [smaranjitghose/doc2pen#579]
I would like to improve the structure, formatting, and basic grammar of the documentation (README.md). Could you please assign it to me under the GSSoC'21 program?

**Comment by preetiahuja18** [comment]
Can I work on this issue? @smaranjitghose . Please assign this issue to me under GSSOC'21 program.  :)

**Comment by pranavvdesai** [comment]
i would like to work on this issue. i promise to give my best

**Comment by smaranjitghose** [comment]
> I would like to improve the structure, formatting, and basic grammar of the documentation (README.md). Could you please assign it to me under the GSSoC'21 program?

Assigned for 1 day
