### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#58]
Minimal and Simple Nav Bar with white and dark mode toggle button present as well as
home 
editor 
contact 
For inspiration refer [this](https://demos.creative-tim.com/material-kit/index.html?_ga=2.202989457.1035946558.1597326347-1708666551.1597326347)

**Comment by varunvj1** [comment]
Dark mode toggle button present in the navbar?

**Comment by smaranjitghose** [comment]
> Dark mode toggle button present in the navbar?

Absolutely!

**Comment by varunvj1** [comment]
Please review my PR. Should I edit it and add the button in that?

**Comment by debanshu08** [comment]
I would like to work on this.

**Comment by AshutoshDash1999** [comment]
@anushbhatia I would like to work on this if possible.

**Comment by varunvj1** [comment]
I'm already working on this.

**Comment by varunvj1** [comment]
> Minimal and Simple Nav Bar with white and dark mode toggle button present as well as
> home
> editor
> contact
> For inspiration refer [this](https://demos.creative-tim.com/material-kit/index.html?_ga=2.202989457.1035946558.1597326347-1708666551.1597326347)


The dark mode toggle button is for the editor page or for the whole website?

**Comment by smaranjitghose** [comment]
> > Minimal and Simple Nav Bar with white and dark mode toggle button present as well as
> > home
> > editor
> > contact
> > For inspiration refer [this](https://demos.creative-tim.com/material-kit/index.html?_ga=2.202989457.1035946558.1597326347-1708666551.1597326347)
> 
> The dark mode toggle button is for the editor page or for the whole website?

The Entire  Website

**Comment by divanshurox** [comment]
Hey can I work on this issue??
