### ISSUE TITLE
'generating pdf...🔄🔄' notification

### ISSUE THREAD

**Issue by ashuvssut** [smaranjitghose/doc2pen#580]
Currently the PDF takes about 5-6secs to generate.

For that small interval a popup must come up saying
"Generating PDF. please wait..."

I am a GSSOC particpant. I want to work on this.

**Comment by Ritu7683** [comment]
I would like to work on this issue. Kindly assign this to me. I am a  GSSOC'21 particpant.

**Comment by smaranjitghose** [comment]
> I would like to work on this issue. Kindly assign this to me. I am a GSSOC'21 particpant.

Keep in mind, the participant who raises the issue would be assigned it by default, only for issues raised by mentors we can consider others with equal preference.

If @ashuvssut fails to complete this, it will be assigned to you
