### ISSUE TITLE
Improve the About_title.

### ISSUE THREAD

**Issue by padmajabhol** [smaranjitghose/doc2pen#584]
![Screenshot (16)](https://user-images.githubusercontent.com/75530516/110761575-e635c480-8275-11eb-94fe-d71af18400cd.png)
I want to add effects to this particular section.

**Comment by anushbhatia** [comment]
How would you do so?

**Comment by padmajabhol** [comment]
> How would you do so? 

By making the font size bolder and better, maybe I can make the changes and attack a ss before you decide to assign it to me. Also if there's anything that needs to be done in the frontend part, I d love to contribute.

**Comment by smaranjitghose** [comment]
> > How would you do so?
> 
> By making the font size bolder and better, maybe I can make the changes and attack a ss before you decide to assign it to me. Also if there's anything that needs to be done in the frontend part, I d love to contribute.

If you are doing the changes, raise a PR directly. We would directly review it. Asking you to do the changes and just saying no based on a screenshot would not be fair imho.

We have a lot of improvements to the frontend left out. Do check out the issues raised last month and comment on the ones you would like to contribute. In case you fail to find them, tag me or @anushbhatia here or use the discord channel

**Comment by padmajabhol** [comment]
Thanks, I m working on it.

**Comment by Lza-etc** [comment]
Would you mind if  I too contribute in this section

**Comment by smaranjitghose** [comment]
I believe this is completed @padmajabhol.
Closing it
