### ISSUE TITLE
Add drawing options on editor page

### ISSUE THREAD

**Issue by atharva1608** [smaranjitghose/doc2pen#585]
While writing on the page suppose there is a need to draw a line or any shape somewhere then there should be an option to do so.
As a participant in GSSoC'21 I would like to contribute to this project.

**Comment by smaranjitghose** [comment]
> While writing on the page suppose there is a need to draw a line or any shape somewhere then there should be an option to do so.
> As a participant in GSSoC'21 I would like to contribute to this project.

Assigned for 4 days.

**Comment by rk05-lenavo** [comment]
I'm the Participant of GSSOC'21. Please assign me this issue.I would love to work on this.

**Comment by smaranjitghose** [comment]
@rk05-lenavo you have 3 days for the initial PR

**Comment by rk05-lenavo** [comment]
@smaranjitghose I made the drawing option. Please view it. If it seems okay to you  please issue me the PR.
