### ISSUE TITLE
Add live preview feature.

### ISSUE THREAD

**Issue by Priyankcoder** [smaranjitghose/doc2pen#586]
Hii :wave: @smaranjitghose, It would be great for users if they can see the live preview of pdf or image adjacent to the editor. That will help the user to decide the right font-size quickly. Currently, the user can't estimate the right font-size due to the inconsistency between the page and font-size ratio in the writing editor and the generated pdf/png.

**Comment by Priyankcoder** [comment]
Please assign this to me, I would like to work on this feature as a GSSOC 21 participant.

**Comment by smaranjitghose** [comment]
> Hii 👋 @smaranjitghose, It would be great for users if they can see the live preview of pdf or image adjacent to the editor. That will help the user to decide the right font-size quickly. Currently, the user can't estimate the right font-size due to the inconsistency between the page and font-size ratio in the writing editor and the generated pdf/png.

Assigned for 4 days.

**Comment by Priyankcoder** [comment]
@smaranjitghose Would you mind labelling this issue with GSSOC 21? I think that is the way my PR will be considered for the same.

**Comment by smaranjitghose** [comment]
> @smaranjitghose Would you mind labelling this issue with GSSOC 21? I think that is the way my PR will be considered for the same.

Sure. However, the PRs are counted based upon the labels in the PR itself. Make sure you don't miss out on that

**Comment by Priyankcoder** [comment]
> > @smaranjitghose Would you mind labelling this issue with GSSOC 21? I think that is the way my PR will be considered for the same.
> 
> Sure. However, the PRs are counted based upon the labels in the PR itself. Make sure you don't miss out on that

Yeah sure, thanks for reminding me. Also, I checked it again and it is mandatory to label issues with gssoc21 and level. It has been stated in the MOM for the 9 March meeting. Would you mind labeling the issue with the level as well?

**Comment by smaranjitghose** [comment]
> > > @smaranjitghose Would you mind labelling this issue with GSSOC 21? I think that is the way my PR will be considered for the same.
> > 
> > 
> > Sure. However, the PRs are counted based upon the labels in the PR itself. Make sure you don't miss out on that
> 
> Yeah sure, thanks for reminding me. Also, I checked it again and it is mandatory to label issues with gssoc21 and level. It has been stated in the MOM for the 9 March meeting. Would you mind labeling the issue with the level as well?

Already done

**Comment by smaranjitghose** [comment]
Closed due to inactivity
