### ISSUE TITLE
We can change the hand writing of one person to another and also can change the color of pages.

### ISSUE THREAD

**Issue by mansijain980** [smaranjitghose/doc2pen#587]
As a replica of cam scanner.

**Comment by smaranjitghose** [comment]
Sure. Go ahead and give it a try

**Comment by smaranjitghose** [comment]
@mansijain980 . Maximum of 7 days for this issue(5 more days left)

**Comment by mansijain980** [comment]
@smaranjitghose yes sir , sure , i have started work on it . i will commit PR within 5 days .
Thanks

**Comment by smaranjitghose** [comment]
Closed due to inactivity
