### ISSUE TITLE
Improve misleading UI (Contact Page) - Heading Looks Like a Button

### ISSUE THREAD

**Issue by N-Shar-ma** [smaranjitghose/doc2pen#588]
## Heading Looks Like a Button
The header of the page (which says Get in Touch) is currently styled to look like a button, which can be confusing for a user.
The pill shape is typically associated with a button, but since this is not a button, I believe changing it's styling would improve the user interface.

### How it looks now:

![image](https://user-images.githubusercontent.com/68962290/110827283-c4731800-824a-11eb-95f8-8fada212a14b.png)

### How I propose it should look:

![image](https://user-images.githubusercontent.com/68962290/110827197-b1604800-824a-11eb-8c99-ce59cd4b020c.png)

## GSSoC'21
If you approve of this UI change that I'm proposing, I'll be very happy to work on it and submit a pull request under the GSSoC'21 program.

**Comment by smaranjitghose** [comment]
> ## Heading Looks Like a Button
> The header of the page (which says Get in Touch) is currently styled to look like a button, which can be confusing for a user.
> The pill shape is typically associated with a button, but since this is not a button, I believe changing it's styling would improve the user interface.
> 
> ### How it looks now:
> ![image](https://user-images.githubusercontent.com/68962290/110827283-c4731800-824a-11eb-95f8-8fada212a14b.png)
> 
> ### How I propose it should look:
> ![image](https://user-images.githubusercontent.com/68962290/110827197-b1604800-824a-11eb-8c99-ce59cd4b020c.png)
> 
> ## GSSoC'21
> If you approve of this UI change that I'm proposing, I'll be very happy to work on it and submit a pull request under the GSSoC'21 program.

Shift the contact form to this page as well

**Comment by N-Shar-ma** [comment]
@smaranjitghose Sir the contact form is already a part of this Contact page. Here's a screenshot of the same:

![image](https://user-images.githubusercontent.com/68962290/110845953-0fe3f100-8260-11eb-83ef-14b85366dc22.png)
