### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [smaranjitghose/doc2pen#589]
Hey!
I would like to add the following in the contributing.md -

1. Difference between GIT and GITHUB
2. How to clone,fork repository
3. How to create a branch and then use git push to push to repo
4. Create a PR
5. Squash commits in a single issue into one
6. Updating the forked and local repo as the updations are made in the upstream

**Comment by smaranjitghose** [comment]
Present [here](https://github.com/smaranjitghose/doc2pen/blob/master/ContributionGuidelines.md)
