### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#59]
# Suggested Sections

- [ ] Topmost illustration
- [ ] Project Maintainers: Name,Picture,LinkedIn,GitHub
- [ ] Project Contributors: Name,Picture, LinkedIn
- [ ] Info about open source, code of conduct,  checkout and star on GitHub
- [ ] Support Us Section [ Patreon + Buy Me a coffee]...Remove the floating icon

**Comment by himanshujaidka** [comment]
please assign this issue to me

**Comment by AshutoshDash1999** [comment]
@anushbhatia I want to work on this issue

**Comment by arnoob16** [comment]
I would like to work on this.

**Comment by debanshu08** [comment]
I would like to work on the Project Maintainers section.

**Comment by raksha009** [comment]
Hi, I would like to work on this issue

**Comment by raksha009** [comment]
Hi, I would like to work on this issue. Plz assign this to me.

**Comment by smaranjitghose** [comment]
@AshutoshDash1999 : Project Maintainer Section
@raksha009 : Contributors Section
@arnoob16: Section about License, Code of Conduct
@debanshu08: Final Section on Sponsorship

Does it this sound good?

** Take inspirations from other major open-source projects

**Comment by AshutoshDash1999** [comment]
@smaranjitghose Project Maintainer section already has name with github and linkedin. Do we have to develop a different style for that part?

**Comment by smaranjitghose** [comment]
> @smaranjitghose Project Maintainer section already has name with github and linkedin. Do we have to develop a different style for that part?

Ya, We would like to change the UI

**Comment by AshutoshDash1999** [comment]
@smaranjitghose please check updated Project Maintainer section of contact.html and contact.css

**Comment by smaranjitghose** [comment]
> @smaranjitghose please check updated Project Maintainer section of contact.html and contact.css

Sorry, I didn't get you

**Comment by AshutoshDash1999** [comment]
> Sorry, I didn't get you
i have submitted a PR for project maintainer section

**Comment by AshutoshDash1999** [comment]
@smaranjitghose Let me know, how does it look?
![Screencast from 15-08-20 09 09 59 AM IST](https://user-images.githubusercontent.com/46455250/90324284-47204700-df8a-11ea-9619-9992c152c0b9.gif)

**Comment by AshutoshDash1999** [comment]
@anushbhatia I have submitted a PR #75 , but I don't know why an error  is showing. I tried to google it but unable to find any solution.

**Comment by ankitapuri** [comment]
I would like to work on this issue.

**Comment by yogi1408** [comment]
I would like to work on this issue.

**Comment by anushbhatia** [comment]
2 days to go any updates?

**Comment by smaranjitghose** [comment]
> I would like to work on this issue.

The tasks are assigned for 3 more days(including today), after that it would be reassigned. And please specify which subtask you want to do

**Comment by ankitapuri** [comment]
contributor's section

**Comment by raksha009** [comment]
> 2 days to go any updates?

Yeah ... Working on it.. and its taking a bit time. Also, plz start the contribution time from 16 th and give us a little more time plz.

**Comment by raksha009** [comment]
> > I would like to work on this issue.
> 
> The tasks are assigned for 3 more days(including today), after that it would be reassigned. And please specify which subtask you want to d

> > I would like to work on this issue.
> 
> The tasks are assigned for 3 more days(including today), after that it would be reassigned. And please specify which subtask you want to do
The contribution period started today . Plz give a little more time

**Comment by raksha009** [comment]
> > I would like to work on this issue.
> 
> The tasks are assigned for 3 more days(including today), after that it would be reassigned. And please specify which subtask you want to do

The contribution period started today. Plz give little more time.

**Comment by AshutoshDash1999** [comment]
@anushbhatia can you please specify what type of effect you want in project maintainer's section?

**Comment by smaranjitghose** [comment]
> @anushbhatia can you please specify what type of effect you want in project maintainer's section?

Although I would suggest you explore and suggest effects yourself and eventually get feedback, for the cards in the project maintainer section try to emulate [this](https://www.bluleadz.com/about-us) and for the effect on hover try to emulate [this](https://girlscriptboilerplate.netlify.app/team.html)

**Comment by AshutoshDash1999** [comment]
i'm thinking of applying this effect. what do you think?
![Screencast from 18-08-20 09 01 01 PM IST](https://user-images.githubusercontent.com/46455250/90534734-b6b75180-e197-11ea-8044-80af886fee44.gif)

**Comment by anushbhatia** [comment]
this looks good to me

**Comment by smaranjitghose** [comment]
@ankitapuri Would you like to propose some changes to the contributor's section. Have a look at @raksha009's PR, her work and my suggestions there

**Comment by ankitapuri** [comment]
@smaranjitghose surely I'll look into it

**Comment by raksha009** [comment]
Can I work on "Project Contributors: Name,Picture, LinkedIn" issue @smaranjitghose 
Also, from where to collect the picture and linkedin handle if its not mentioned in their github profile !?

**Comment by ankitapuri** [comment]
according to me the contributor section is fine which is done by @raksha009

**Comment by anushbhatia** [comment]
If anyone wants to add the names of people from the contributor's direct to the page using GitHub API u can follow that.
If interested ping me on slack.

**Comment by raksha009** [comment]
I have no idea about how github APIs work.. So, would It be feasible if I manually add all the contributors there!? 
Or is there any online resource from where I could get an idea about adding names of people from contributor's direct to the page!?

**Comment by smaranjitghose** [comment]
> I have no idea about how github APIs work.. So, would It be feasible if I manually add all the contributors there!?
> Or is there any online resource from where I could get an idea about adding names of people from contributor's direct to the page!?

Ya that works for now. Later I'll guide you with the GitHub API

**Comment by anushbhatia** [comment]
Any Update Guys?
