### ISSUE TITLE
[GSSOC'21 ] Improve the UI of the experience form in the contact page

### ISSUE THREAD

**Issue by Tanya933** [smaranjitghose/doc2pen#592]
I would like to improve the UI of the experience form in the contact page .

**Comment by Fpj-11** [comment]
I would like to work on this issue.

**Comment by prajakta2809** [comment]
i would like to work on this

**Comment by smaranjitghose** [comment]
> I would like to improve the UI of the experience form in the contact page .

Assigned for 3 days

**Comment by smaranjitghose** [comment]
After 1 more day, @Fpj-11 can take over
