### ISSUE TITLE
Reformatting the Steps Layout 

### ISSUE THREAD

**Issue by anhushree** [smaranjitghose/doc2pen#595]
Problem:
The alignment of the Steps layout on the Home page is not visually appealing 

![Doc2penStep](https://user-images.githubusercontent.com/56672958/110898458-49cafb00-8325-11eb-8942-7c1bffd4af57.PNG)

Solution :
The paragraphs under each Step can be aligned left/right with respect to the positioning of the illustrations.

**Comment by anhushree** [comment]
I would like to take upon this issue @smaranjitghose

**Comment by anhushree** [comment]
@smaranjitghose Will, you be tagging any labels? (I'm a GSSoC'21 Participant)

**Comment by smaranjitghose** [comment]
> @smaranjitghose Will, you be tagging any labels? (I'm a GSSoC'21 Participant)

yup
