### ISSUE TITLE
Adding effects to cards of "Open Source Programs we are a part of"

### ISSUE THREAD

**Issue by ankitaugale23** [smaranjitghose/doc2pen#596]
Right now, cards here are looking really great but I think they would look better if we will make them to take less space. 
I can enhance the hover effects like when the person will hover onto the card it will increase it's size and will show the information and read more button while as normally the cards will only show Event logo and Event name.
If the mentors and project managers are ok with doing so I would like to work on this issue.
Let me know @anushbhatia

**Comment by smaranjitghose** [comment]
> Right now, cards here are looking really great but I think they would look better if we will make them to take less space.
> I can enhance the hover effects like when the person will hover onto the card it will increase it's size and will show the information and read more button while as normally the cards will only show Event logo and Event name.
> If the mentors and project managers are ok with doing so I would like to work on this issue.
> Let me know @anushbhatia

Sure @ankitaugale23 . Please go ahead and give a PR. We will review it accordingly 😊

**Comment by smaranjitghose** [comment]
> Right now, cards here are looking really great but I think they would look better if we will make them to take less space.
> I can enhance the hover effects like when the person will hover onto the card it will increase it's size and will show the information and read more button while as normally the cards will only show Event logo and Event name.
> If the mentors and project managers are ok with doing so I would like to work on this issue.
> Let me know @anushbhatia

Assigned for 3 days. If required we can extend the deadline for the initial PR

**Comment by Rishikakanojia** [comment]
I would like to work on this issue. Pease assign me this

**Comment by ankitaugale23** [comment]
Sure Thanks for assigning it to me. I will complete my task and make a PR by 16th march. Is it okay? @smaranjitghose

**Comment by sharvariiii** [comment]
Heyy..I can fix this issue. As a beginner I am figuring out. Please let me know if I can contribute to it or it is closed?

**Comment by anushbhatia** [comment]
Sure @sharvariiii

**Comment by smaranjitghose** [comment]
> Sure @sharvariiii

Assigned for 3 days, after which the issue shall be closed

**Comment by sharvariiii** [comment]
Can you please guide me what changes are required from my side because "the person will hover onto the card it will increase it's size and will show the information and read more button " this feature is already there. Also #758 has assigned to someone else so that person is working on that issue which is similar to this one. Will be waiting for your response.

**Comment by smaranjitghose** [comment]
This was supposed to be a UI enhancement issue where you were expected to suggest improvements. Otherwise, the maintainers themselves would have stated the requirements
