### ISSUE TITLE
add effects in the navigation bar and front page picture

### ISSUE THREAD

**Issue by Smriti129** [smaranjitghose/doc2pen#597]
![Screenshot (250)](https://user-images.githubusercontent.com/76429418/110958289-90931200-8372-11eb-9f9d-32e860a4b4fe.png)
I think there should be some changes in the top picture of the webpage and the about,team and support us rows. It would look much better is they are visible to the viewers and are systematically arrange. 
Please sign me this task.

**Comment by smaranjitghose** [comment]
> ![Screenshot (250)](https://user-images.githubusercontent.com/76429418/110958289-90931200-8372-11eb-9f9d-32e860a4b4fe.png)
> I think there should be some changes in the top picture of the webpage and the about,team and support us rows. It would look much better is they are visible to the viewers and are systematically arrange.
> Please sign me this task.

Could you attach a screenshot with a rough sketch of your suggested changes or elaborate more or perhaps raise a PR so that we can review this more effectively and give feedback

**Comment by Smriti129** [comment]
okay sure! I will raise a PR .

**Comment by rk05-lenavo** [comment]
I'm the Participant of GSSOC'21. Please assign me this issue.I would love to work on this.

**Comment by smaranjitghose** [comment]
> ![Screenshot (250)](https://user-images.githubusercontent.com/76429418/110958289-90931200-8372-11eb-9f9d-32e860a4b4fe.png)
> I think there should be some changes in the top picture of the webpage and the about,team and support us rows. It would look much better is they are visible to the viewers and are systematically arrange.
> Please sign me this task.

2 more days for this. After that @rk05-lenavo can take over

**Comment by Smriti129** [comment]
> > ![Screenshot (250)](https://user-images.githubusercontent.com/76429418/110958289-90931200-8372-11eb-9f9d-32e860a4b4fe.png)
> > I think there should be some changes in the top picture of the webpage and the about,team and support us rows. It would look much better is they are visible to the viewers and are systematically arrange.
> > Please sign me this task.
> 
> Could you attach a screenshot with a rough sketch of your suggested changes or elaborate more or perhaps raise a PR so that we can review this more effectively and give feedback

Can I add a logo of DOC2PEN with different style? You can use it for the new webpage if you like.

**Comment by Smriti129** [comment]
![WhatsApp Image 2021-03-15 at 21 46 29](https://user-images.githubusercontent.com/76429418/111185440-f8966200-85d7-11eb-9597-f52c4467d294.jpeg)
This is the basic idea that I have in my mind. There are some things that I want to change (if you allow):-
1. The logo of doc2pen is very simple...we can something creative.
2. All the dropdowns will be visible on hover in the navigation bar.
3. The pic "type documents in your handwriting", the handwriting part is not so visible, so we can add something catchy caption.

I had almost made this section of the page, but if you want me to add or change something I will do it.
Please give your feedback about this idea @smaranjitghose !

**Comment by smaranjitghose** [comment]
@Smriti129 as far as the Nav Bar is concerned, I would like to keep it unchanged at least for the first phase of the program (It took a lot of time to reach there😅)

As far as the Home Page (To be specific the About Section) goes, yes we do need a revamp

Initially the project started out as my pet project to convert text into handwritten assignments. Hence the current descriptions are similar to that.

However, we now evolving with other features like Sketch, MediaManip, etc. So we do need to revamp the pitch.

(ofcourse the corresponding illustrations too)

**Comment by smaranjitghose** [comment]
If you have decent content writing skills, you can improve the readme and contributing guidelines as well

**Comment by Smriti129** [comment]
Okay, I understand that. 
But I am a little bit concern about the About, Team and Support section, because they look like "odd ones out". So if you want to revamp that section where do you want to display it, if not in the navigation bar?   
@smaranjitghose

**Comment by Smriti129** [comment]
> If you have decent content writing skills, you can improve the readme and contributing guidelines as well

Yes, sure I can do that. Please do tell if you want any particular type of changes in this.

**Comment by anushbhatia** [comment]
> Okay, I understand that.
> But I am a little bit concern about the About, Team and Support section, because they look like "odd ones out". So if you want to revamp that section where do you want to display it, if not in the navigation bar?
> @smaranjitghose

if you want to go ahead with revamping it we can add an option of dropdown for the home page and there you do internal navigation. We don't want multiple pages as that confuses user to find the tab for the editor(which is the main purpose).

**Comment by Smriti129** [comment]
Okay.
