### ISSUE TITLE
[GSSOC]: need proper alignment to map

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#598]
![Screenshot (164)](https://user-images.githubusercontent.com/58654018/110978596-97794f00-8389-11eb-8351-c2e437297cef.png)
On the right side, there should be a margin, pls assign this to me

**Comment by ashuvssut** [comment]
![image](https://user-images.githubusercontent.com/60546840/111025132-335d8780-8397-11eb-9d93-93e0ddd5845e.png)

I think adding a right-margin will reduce the viewing area of the map.

_this screen width (1024px) is of "iPad pro" device_

**Comment by himanshujaidka** [comment]
working
