### ISSUE TITLE
Add new page options to the Editor Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#599]
## What we are looking forward to!

- 2 new ruled pages
- 2 new pages with margins
- 2 Diary pages 

## Some specifications:

- **Our current ruled pages are too much zoomed in and need to be replaced**

- In case you are wondering what type of pages are possible, [check this](https://www.google.com/search?q=printable+notebook+pages&tbm=isch&bih=722&biw=1536&hl=en&sa=X&ved=2ahUKEwjaodu0pO_uAhVMcX0KHUdSDjIQrNwCKAB6BQgBEK4C)

- I expect you to provide scanned images of the pages or a high-resolution one if that is not possible. If you are planning to open the images from the Google Search link given above, please understand that all such PRs would not be considered.

- Please understand that this is not merely an issue of adding new images, the code has to be updated simultaneously so that we can use the pages

- Please follow the project's asset organization.

## General PR Guidelines:

- The title of the PR is short and meaningful
- You refer to the respective issue in the PR description ``Resolves # issue_number``
- Attach screenshot(s)/clip of the result of your changes
- (In bullet points) describe your changes

**Comment by theBeginner86** [comment]
May I work on this issue as I am a participant of GSSOC'21?

**Comment by shreyanema33** [comment]
I got your issue, may I work?

**Comment by smaranjitghose** [comment]
@shreyanema33 @theBeginner86 Work independently. Assigned for 2 days

**Comment by rk05-lenavo** [comment]
I'm the Participant of GSSOC'21. Please assign me this issue.I would love to work on this.

**Comment by smaranjitghose** [comment]
> I'm the Participant of GSSOC'21. Please assign me this issue.I would love to work on this.

Assigned for 2 days

**Comment by Rishikakanojia** [comment]
Please assign me this issue.

**Comment by Aditi-03** [comment]
I'm the Participant of GSSOC'21. Please assign me this issue. I will try my best to fix it.

**Comment by smaranjitghose** [comment]
Each of you have 3 days from the day you are being assigned since this is a fairly simple issue

**Comment by sardonicankita** [comment]
Hi is this iszue still available? Can u please assign me this?

**Comment by smaranjitghose** [comment]
> Hi is this iszue still available? Can u please assign me this?

Yes

**Comment by sardonicankita** [comment]
So am I assigned this issue cause I havent received that assigned notification?

**Comment by Furquan712** [comment]
I would like to work on this , Will you assignee me
