### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#60]
- [ ] Side by Side Windows for screen you write and the output [for example](https://12hoy26budd28l29v3kl2fq1-wpengine.netdna-ssl.com/wp-content/uploads/2017/03/AOG-on-Overleaf-1b.png)
- [ ] Drop Down Menu for different fonts
- [ ] Menu Bars kind of structure [on top](https://saurabhdaware.github.io/text-to-handwriting).
- [ ] Better Buttons so that it looks more intriguing. [refer this](https://demos.creative-tim.com/material-kit/index.html) using [this](https://materializecss.com/buttons.html)

**Comment by arnoob16** [comment]
I can work on dropdowns and buttons. Can I use some other animated buttons made with pure css?
Also, What do you mean by Menu Bars. I don't see any menu bar in that page, except the dark mode toggle.

**Comment by anushbhatia** [comment]
Menu bar is like a layout present below the nav bar like kind of structure it should be like Microsoft word where we get edit options on top. That will be menu bar.

**Comment by goelradhika** [comment]
@anushbhatia  @smaranjitghose  sir, I want to do - 
## Side by Side Windows for screen you write and the output

**Comment by Aniruddhmuley2001** [comment]
I would like to work on responsiveness of the page and side by side windows issue.

**Comment by anushbhatia** [comment]
ping me on slack i will explain the layout if you have a issue,

**Comment by EkjotKaur** [comment]
I would like to work on Better Buttons so that it looks more intriguing.

**Comment by anushbhatia** [comment]
let @Aniruddhmuley2001 change the layout then will assign u this

**Comment by EkjotKaur** [comment]
Can you tell me what next I have to do @anushbhatia @smaranjitghose.

**Comment by smaranjitghose** [comment]
> Can you tell me what next I have to do @anushbhatia @smaranjitghose.

- Can you please do the side by side (input + output) layout that @Aniruddhmuley2001 was doing
- Please remove the dark mode from the Editor Page as well. Once the entire UI is complete for light mode and other pages are done, we shall proceed to it
