### ISSUE TITLE
Custom ScrollBar for the pages.

### ISSUE THREAD

**Issue by shreyanema33** [smaranjitghose/doc2pen#601]
Having a scrollbar in the pages itself would make it easier to preview the changes of fonts, style, color in various parts of the page.

**Comment by smaranjitghose** [comment]
> Having a scrollbar in the pages itself would make it easier to preview the changes of fonts, style, color in various parts of the page.

Assigned for 3 days

**Comment by rk05-lenavo** [comment]
I'm the Participant of GSSOC'21. Please assign me this issue.I would love to work on this.

**Comment by Suvojit-roy** [comment]
Please do assign me this one, i have looked into the project and eagerly waiting to contribute to it.
I am a participant of GSSOC'21
