### ISSUE TITLE
Adding help button in navbar

### ISSUE THREAD

**Issue by kumarishalini6** [smaranjitghose/doc2pen#606]
I guess there should be a help button where the steps should be written , because About  is not to help the  people ,
to help people there must be help button  and i guess there is difference between about and help.
i am participate of GSSoC'21 i want to add help button in navbar, can you please assign me.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.
I have made these type of projects ... so i can easily solve this issue.

**Comment by Pallavi-02** [comment]
l'm GSSoC'21 participant, I have a bit good hand in html and css. So, I would like to contribute in this project.  Please assign this issue to me. I can solve this easily.

**Comment by smaranjitghose** [comment]
The Home Page is really self explantory. Anyone who has used a word processor like MS Word or Google Docs can use it
