### ISSUE TITLE
Making the Website Responsive

### ISSUE THREAD

**Issue by Tanu-priya-Roy** [smaranjitghose/doc2pen#608]
A responsive website is user-friendly and so accessible and used by many users. I would like to make the website responsive as a part of GSSOC'21. Please assign me this task.

**Comment by Aditi404** [comment]
Hello sir,
I'am very interested in making a website attractive and responsive. I would love to work on this project please assign me this project @Tanu-priya-Roy  @shreyakapoor08

**Comment by smaranjitghose** [comment]
@Tanu-priya-Roy @Aditi404  (without conflicting with each other) raise individual issues to fix the regions of the website which you feel are not mobile responsive (or perhaps not working as expected on different screen sizes)

**Comment by Tanu-priya-Roy** [comment]
Okay Sir will do it.

**Comment by Aditi404** [comment]
Okay Sir I will definitely do it.
