### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#61]
- [ ] Export Options:  jpg, png,pdf,docx
- [ ] Adding Custom Fonts
- [x] Various Page Options like lined blank etc.
- [x] Different Pen Color
- [ ] Text Size variation while writing
- [ ] Custom Alignments so that i can place my text anywhere
- [ ] Excalidraw Integration
- [ ] Google Drive Integration
- [ ] Chat Option using socket.io 
- [x] Input Text Limit(no. of words that can be given as input)
- [ ] Translator [Beta]

**Comment by himanshujaidka** [comment]
I want to work on different pen colour

**Comment by himanshujaidka** [comment]
and also wants to work on the input text limit

**Comment by anushbhatia** [comment]
Sure @himanshujaidka

**Comment by raksha009** [comment]
Hi, I would like to work on adding custom fonts.

**Comment by smaranjitghose** [comment]
> Hi, I would like to work on adding custom fonts.

Whenever you give a PR for this, please note that the fonts should be as close to human handwriting as possible. @anushbhatia would teach you how to actually collect people's handwriting and convert them into fonts. We need 10 in total for now. You can contact him over slack for this

**Comment by himanshujaidka** [comment]
please add some fonts of bad handwriting @raksha009

**Comment by ymaheshwari1** [comment]
Hi, I want to work on a chat option using socket.io.

**Comment by anushbhatia** [comment]
go on @ymaheshwari1

**Comment by EkjotKaur** [comment]
Hi, I would like to work on Various Page Options like lined blank etc.

**Comment by AyushSatyam** [comment]
I would like to work on Google drive integration

**Comment by anushbhatia** [comment]
Export Options: jpg, png,pdf,docx
 Adding Custom Fonts adding 5 atleast @raksha009 (pm on slack for making them)
 Various Page Options like lined blank etc. @EkjotKaur 
 Different Pen Color(black,blue,red,green) @himanshujaidka 
 Text Size variation while writing 
 Custom Alignments so that i can place my text anywhere
 Excalidraw Integration
 Google Drive Integration @AyushSatyam 
 Chat Option using socket.io @ymaheshwari1 
 Input Text Limit(10000 words on a single page) @himanshujaidka 
 Translator [Beta]

**Comment by himanshujaidka** [comment]
@anushbhatia could I use backend for characters limit?

**Comment by himanshujaidka** [comment]
node.js?

**Comment by himanshujaidka** [comment]
see pr #83 feature 10 solved

**Comment by Deshmukh-Omkar** [comment]
Please assign me on Feature 1: Export options

**Comment by smaranjitghose** [comment]
> see pr #83 feature 10 solved

Please understand for every comment you put we get a notification. Once you give a PR be patient, it will be reviewed soon. Do not mention it again in the issue and use the slack channel for discussion

**Comment by smaranjitghose** [comment]
# Reminders: 

@ymaheshwari1  - 4 more days
@AyushSatyam  - 4 more days
@EkjotKaur - 2 more days
@himanshujaidka - 2 more days
@raksha009 - 3 more days

**Comment by himanshujaidka** [comment]
@smaranjitghose I am trying to apply the dropdown button but the button is not working on-site, so what I do?

**Comment by Bhavya-Sehgal** [comment]
Hi, I would like to work on adding custom fonts.

**Comment by smaranjitghose** [comment]
> Hi, I would like to work on adding custom fonts.

@Bhavya-Sehgal Please get in touch with @anushbhatia for learning how to collect handwritings and convert them into fonts using pentool

**Comment by himanshujaidka** [comment]
@smaranjitghose which feature you assigned me?

**Comment by himanshujaidka** [comment]
> * [ ]  Export Options:  jpg, png,pdf,docx
> * [ ]  Adding Custom Fonts
> * [x]  Various Page Options like lined blank etc.
> * [x]  Different Pen Color
> * [ ]  Text Size variation while writing
> * [ ]  Custom Alignments so that i can place my text anywhere
> * [ ]  Excalidraw Integration
> * [ ]  Google Drive Integration
> * [ ]  Chat Option using socket.io
> * [ ]  Input Text Limit(no. of words that can be given as input)
> * [ ]  Translator [Beta]

we have to add a pen tip feature and pencil mode feature to
