### ISSUE TITLE
[GSSOC'21] Issue in importing file to the website.

### ISSUE THREAD

**Issue by Rishab-j** [smaranjitghose/doc2pen#610]
I would like to show a popup or message that tells the user about not able to import the document.

**Comment by smaranjitghose** [comment]
> I would like to show a popup or message that tells the user about not able to import the document.

You mean if a small pop up to show a warning if a person tries to import something weird like a gif?

**Comment by Rishab-j** [comment]
Yes, we can show a modal informing the user about the error

**Comment by smaranjitghose** [comment]
> Yes, we can show a modal informing the user about the error

Assigned for 3 days

**Comment by smaranjitghose** [comment]
Closed due to inactivity
