### ISSUE TITLE
Improve the Contact page 

### ISSUE THREAD

**Issue by malavikarajeshvikraman** [smaranjitghose/doc2pen#612]
Hi! I am Malavika , a GSSOC'21 Participant .
I would like to beautify the contact us page . Reduce the size of map and increase the contact form . And make small changes to improve the UI of the app. 
Kindly assign this task to me.

**Comment by smaranjitghose** [comment]
> Hi! I am Malavika , a GSSOC'21 Participant .
> I would like to beautify the contact us page . Reduce the size of map and increase the contact form . And make small changes to improve the UI of the app.
> Kindly assign this task to me.

Assigned for 3 days

**Comment by smaranjitghose** [comment]
Duplicate #592

**Comment by malavikarajeshvikraman** [comment]
@smaranjitghose  So it is not assigned to me right ?

**Comment by smaranjitghose** [comment]
> @smaranjitghose So it is not assigned to me right ?

No
