### ISSUE TITLE
Add How to Use  Section  in Side Nav 

### ISSUE THREAD

**Issue by malavikarajeshvikraman** [smaranjitghose/doc2pen#613]
Hi! I am Malavika , a GSSOC'21 Participant .
I would like to  add how to use section  to sidenav in homepage . Maybe add a heading "How to use too " above the steps to make it clear to the user.
Kindly assign this task to me.

**Comment by smaranjitghose** [comment]
This project is primarily meant to be used on larger screens like PC or MaC
