### ISSUE TITLE
feature: Login/Signup API

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#619]
It would be great if the backend will be introduced to this project, to access the premium features user needs to signup and it will help us to track the audience and also maintain a connection with the users.

**Comment by EkjotKaur** [comment]
I would like to work on frontend part of Sign and login. Please assign me this issue @smaranjitghose  @anushbhatia @himanshujaidka 
[GSSOC'21]

**Comment by himanshujaidka** [comment]
> I would like to work on frontend part of Sign and login. Please assign me this issue @smaranjitghose @anushbhatia @himanshujaidka
> [GSSOC'21]

wait for the mentors to approve this feature request

**Comment by Pointdexter99** [comment]
Can we integrate social media auths in this as login/signup feature..?? If yes.. Which one's preferably.

**Comment by smaranjitghose** [comment]
We want to keep the app without any promotions or sign-up. So that students can come, get their job done, and leave. No strings attached
