### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#62]
Add various meta tage required for it boost up  the rating using lighthouse,pageinsights and gt metrix

**Comment by imPGupta** [comment]
I want to work on this issue but need some help.

**Comment by smaranjitghose** [comment]
> I want to work on this issue but need some help.

Sure, ping us in the common workspace. We would help you out. Please comment the entire SEO work you do elaborately

**Comment by imsahil007** [comment]
Any updates on this @imPGupta ?

**Comment by imPGupta** [comment]
Yes @imsahil007 . Added few meta tags by using open graph. Sorry, for too late to reply due to some network and electricity issues.

**Comment by smaranjitghose** [comment]
> @imPGupta Can we work on this issue together?

Go ahead and give a PR if you have any changes to propose
