### ISSUE TITLE
Navbar Hamburger design for smaller  devices

### ISSUE THREAD

**Issue by Avishake007** [smaranjitghose/doc2pen#620]
I want to work on this project.
@smaranjitghose and @anushbhatia  please assign me for this project.
I am  a participant of GSSOC'21 and want to contribute on this project

**Comment by smaranjitghose** [comment]
> I want to work on this project.
> @smaranjitghose and @anushbhatia please assign me for this project.
> I am a participant of GSSOC'21 and want to contribute on this project

Assigned for 4 days

**Comment by Avishake007** [comment]
When we click on the hamburger icon it will be converted from 
![humburger(1)](https://user-images.githubusercontent.com/56298861/111102810-fd74fa80-8572-11eb-8459-100b5e0a97e1.PNG)

to

![humburger(2)](https://user-images.githubusercontent.com/56298861/111102831-0665cc00-8573-11eb-9d2a-b45309fbfdb0.PNG)
(ignore the color)
@smaranjitghose this is my plan

**Comment by anushbhatia** [comment]
Sure you can go ahead with this.

**Comment by smaranjitghose** [comment]
> When we click on the hamburger icon it will be converted from
> ![humburger(1)](https://user-images.githubusercontent.com/56298861/111102810-fd74fa80-8572-11eb-8459-100b5e0a97e1.PNG)
> 
> to
> 
> ![humburger(2)](https://user-images.githubusercontent.com/56298861/111102831-0665cc00-8573-11eb-9d2a-b45309fbfdb0.PNG)
> (ignore the color)
> @smaranjitghose this is my plan

Avoid the red color. Make sure that the color scheme is consistent throughout. Other than that, do give a PR within 2 days
