### ISSUE TITLE
Add CSS animation to steps section

### ISSUE THREAD

**Issue by rray14** [smaranjitghose/doc2pen#622]
Hi I'm a participant of GSSoC'21
I can contribute by using CSS animations to add visual transition to the Steps section
Please assign me this task
Thank you!

**Comment by haarsh01** [comment]
Hello I am 'a participant of GSSoC'21
I can contribute to this issue. 
Please assign me this task
Thank you!

**Comment by smaranjitghose** [comment]
Closed due to inactivity
