### ISSUE TITLE
Improve the UI of the READ MORE button(s) on Home Page

### ISSUE THREAD

**Issue by Himika-Mishra** [smaranjitghose/doc2pen#624]
Hi @smaranjitghose ,

I think the read more button on the cards in not that fascinating.
I would like to give some gloss effect to the buttons to become more trendy.

Please if you will assign me this task i will start working on it.

Thanks 
Himika Mishra

**Comment by smaranjitghose** [comment]
> Hi @smaranjitghose ,
> 
> I think the read more button on the cards in not that fascinating.
> I would like to give some gloss effect to the buttons to become more trendy.
> 
> Please if you will assign me this task i will start working on it.
> 
> Thanks
> Himika Mishra

Assigned for 3 days

**Comment by lakshita15** [comment]
I would like to contribute to this isssue.Please assign me this issue i'll use the tech stack provided by you and give best results.
lakshita(gssoc participant)..

**Comment by lakshita15** [comment]
I'll add hover animation and box shadow to the same with classy looking effects.

**Comment by Himika-Mishra** [comment]
I have already been assigned this issue ..... Please take another one

Thanks
Himika Mishra

**Comment by smaranjitghose** [comment]
> I'll add hover animation and box shadow to the same with classy looking effects.

@Himika-Mishra you have two more days for this. Do have a look at the feedback given in the PR
After that @lakshita15 can take over if there is any scope for improvement left.

**Comment by smaranjitghose** [comment]
Closed due to inactivity
