### ISSUE TITLE
2 more font choice for users of Editor Section

### ISSUE THREAD

**Issue by nijin26** [smaranjitghose/doc2pen#626]
hello @smaranjitghose 

I would like to add 2 more cursive handwritten type fonts, that best suits some user's cursive writing style.
I think the placeholder's (in the editor section) colour should be choosable for users for there text because it has the colour of the pencil.

I know it's not a major update. But I think we should consider every user, right?

So can you plz assign this work for me?

Thanks
Nijin Nazar
gssoc21 participant

**Comment by smaranjitghose** [comment]
Which fonts are you suggesting? Could you please attach a screenshot @nijin26 ?

**Comment by nijin26** [comment]
Miniver
![image](https://user-images.githubusercontent.com/63832147/111081930-a1d34e80-852b-11eb-8446-8159e87dd20a.png)

Better Grade
![image](https://user-images.githubusercontent.com/63832147/111081980-ef4fbb80-852b-11eb-861d-560fb11cf940.png)

These are the two fonts

**Comment by anushbhatia** [comment]
These don't have a human touch to it. More of easy to predict that they are manual fonts.
