### ISSUE TITLE
Update the contents of Contributing.MD with ContributionGuideline.MD and delete the latter

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#627]
Self Explanatory!

**Comment by vedikaag99** [comment]
@smaranjitghose Can I take up this issue?

**Comment by smaranjitghose** [comment]
> @smaranjitghose Can I take up this issue? I'm a GSSOC participant.

Try to wrap up asap. This is a fairly simple issue

**Comment by vedikaag99** [comment]
@smaranjitghose Should I keep the `Open Source Program grading part` of contributing.md?
