### ISSUE TITLE
Removing blue border

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#629]
![image](https://user-images.githubusercontent.com/40017559/111082569-f75d2a80-852e-11eb-8a53-b356f22261a1.png)
Currently, there's a blue border around the sketch page which needs to be improved. Entire page should have the canvas

**Comment by malavikarajeshvikraman** [comment]
Hi , I am interested to do this.
Could you please assign this to me ?

**Comment by anushbhatia** [comment]
Assigned for 1 day. Try to give a pr within 36 hours.
