### ISSUE TITLE
UI/UX Updates/Suggestions

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#63]
Any UI/UX related enhancements feel free to ping me or drop a comment here.

**Comment by himanshujaidka** [comment]
@anushbhatia I am very excited and wants to work

**Comment by arnoob16** [comment]
I think the navbar is too basic, also there's no C2A i.e. a button to go to the editor directly from the home page, while using mobile. The navbar-toggle is placed away for a right handed user on a phone display.

**Comment by shawavisek35** [comment]
The site is not responsive.
I would like to work upon this.

**Comment by shawavisek35** [comment]
@smaranjitghose can i use bootstrap4 in this project.

**Comment by anushbhatia** [comment]
sure if that makes it look great you can replace the whole structure

**Comment by varunvj1** [comment]
"What is Doc2Pen" and Key features section styling could be more organized and improved. Please assign it to me.

**Comment by The-Keshav-Agarwal** [comment]
In the Home page, in the "What is Doc2Pen" section there is some extra spacing which is not looking good. I want to remove this spacing. please assign this to me.
![image](https://user-images.githubusercontent.com/56120769/90329775-19a4bf00-dfc5-11ea-847c-bfb540a5dbf6.png)

**Comment by anushbhatia** [comment]
Fix the extra space. Try improving UI as well

**Comment by Deshmukh-Omkar** [comment]
Resolves #86

**Comment by imPGupta** [comment]
I want to add a new footer section.

**Comment by nikita-1801** [comment]
I'd like to work on stylizing the features and call to action section. It looks plain right now.
