### ISSUE TITLE
Changing UI for sketch

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#630]
![image](https://user-images.githubusercontent.com/40017559/111082626-502cc300-852f-11eb-8f5d-b44cdf356905.png)
Moving the current pannel completely to the right so that it doesn't feel like the complete copy.

**Comment by SalmaFarghaly** [comment]
Hello @anushbhatia , I am a GSSOC'21 participant and I would like to work on this issue , Can you assign it to me ?
Thanks in advance.

**Comment by smaranjitghose** [comment]
> Hello @anushbhatia , I am a GSSOC'21 participant and I would like to work on this issue , Can you assign it to me ?
> Thanks in advance.

Check out the interface of Canva. Similar to that we wish everything to be on the left panel.


Assigned for 5 days

**Comment by SalmaFarghaly** [comment]
@smaranjitghose What is Canva? I understand that I should make it as a block like "Fill" div for example, and put it under the "Fill" div. or am I mistaken?

**Comment by smaranjitghose** [comment]
> @smaranjitghose What is Canva? I understand that I should make it as a block like "Fill" div for example, and put it under the "Fill" div. or am I mistaken?

Please Google stuff by yourself. Atleast till some extent. . I don't mind helping out with doubts but these are really trivial ones.

[Canva](https://www.canva.com/)

**Comment by SalmaFarghaly** [comment]
Dear @smaranjitghose  thank you for the clarification, I have already reached that yesterday but wanted to make sure that you mean the same thing.
![new](https://user-images.githubusercontent.com/59613960/111288551-f6bab600-864c-11eb-8adf-dc03926eac91.png)
So I should do something like blocks on the left and put the shape icons in a new "Shape" block and add the line and arrow icons in the "Stroke Style" block?

**Comment by SalmaFarghaly** [comment]
Dear @smaranjitghose thank you for the clarification, I have already googled it but wanted to make sure you mean the same thing.
![new](https://user-images.githubusercontent.com/59613960/111294561-210f7200-8653-11eb-9528-25d95189df2f.png)
So, Should I do something like that in the left of the photo and put the shapes icons in a new "Shapes" block and add the line and arrow icons in the "Stroke Style" block?

**Comment by anushbhatia** [comment]
Currently, just add all of them together in the left panel add a heading of shapes to all of them.

**Comment by Mukta-Sawant** [comment]
@smaranjitghose @anushbhatia I would like to work on this as a part of GSSOC'21. Please assign it to me.

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia I would like to work on this as a part of GSSOC'21. Please assign it to me.

The recent PR has majorly messed up the sketch page w.r.t scroll option, edge mode, background color, etc.

Those need to be fixed first before handling the UI further. Do you wish to take up issues on those bugs?

**Comment by SalmaFarghaly** [comment]
I can continue working on the issue, I have just fixed the scroll option and re-added the canvas color option.
![bugs (1)](https://user-images.githubusercontent.com/59613960/111884879-0f202d00-89cd-11eb-8f48-4fac2c12de49.png)

**Comment by smaranjitghose** [comment]
> I can continue working on the issue, I have just fixed the scroll option and re-added the canvas color option.
> ![bugs (1)](https://user-images.githubusercontent.com/59613960/111884879-0f202d00-89cd-11eb-8f48-4fac2c12de49.png)

Cool. Do give separate PRs for each bug so that it is easier for us to review and we can reward you the points accordingly

**Comment by SalmaFarghaly** [comment]
Okay Great, Do you want me to change the UI of shapes or is it okay ? and for the Edge mode , Is it working fine and just doesn't appear on the toolbox or what is exactly the problem with it?
