### ISSUE TITLE
Add Feature to Change Pen Styles @Sketch Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#635]
## Sample 

![pen_style](https://user-images.githubusercontent.com/46641503/111250101-c108d380-8632-11eb-96ec-a5f8a10fdc16.png)

## Requirements:
- Currently, we have only a simple pen style of single line and which seems more of a computerized one.
we want to add a human touch to the design by implementing the above styles similar to the slopiness feature present [here](https://excalidraw.com/).
- Do rename the style standard accordingly don't use the word sloppiness here.
- DO NOT mess with the code unrelated to your task

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

**Comment by himanshujaidka** [comment]
interested, pls assign this to me

**Comment by himanshujaidka** [comment]
@anushbhatia where you want to implement this feature, on an editor or on the sketch, I am in doubt, I think on editor? pls clear this to me 🤔

**Comment by anushbhatia** [comment]
Sketch page

**Comment by himanshujaidka** [comment]
okay

**Comment by anushbhatia** [comment]
Would you want to continue?

**Comment by himanshujaidka** [comment]
> Would you want to continue?

yes, but there is already stroke width option

**Comment by anushbhatia** [comment]
That's more of a computerized option. We want it to be more of human touch.

**Comment by himanshujaidka** [comment]
okay

**Comment by himanshujaidka** [comment]
is there is any documentation, which describes how to make it more similar to humans? @anushbhatia

**Comment by ashuvssut** [comment]
i want to work on this. 

if by any chance asignee fails to submit PR then assign me instead . I will submit pr within one day

**Comment by smaranjitghose** [comment]
> okay
> Assign this to me

Assigned for 2 days.

**Comment by himanshujaidka** [comment]
![Screenshot (179)](https://user-images.githubusercontent.com/58654018/111593539-0e7e6f80-87f0-11eb-9b3e-fb410c73a5f5.png)
is it ok like this?

**Comment by anushbhatia** [comment]
> ![Screenshot (179)](https://user-images.githubusercontent.com/58654018/111593539-0e7e6f80-87f0-11eb-9b3e-fb410c73a5f5.png)
> see the stroke style, is it ok like this? @anushbhatia

This looks more like a computerized one and also these are not similar to the ones displayed in images. They are more of a 
dotted lines

**Comment by himanshujaidka** [comment]
okay, working

**Comment by smaranjitghose** [comment]
Any updates?

**Comment by ashuvssut** [comment]
i want to work on this

**Comment by anushbhatia** [comment]
@himanshujaidka needed help @ashuvssut you can help him with that

**Comment by himanshujaidka** [comment]
yes @ashuvssut

**Comment by ashuvssut** [comment]
Actually I dont have any idea how to do this. But I think that I will find out. I need to find ways to do this.

as of now, I dont have any clue.

I think I will manage to solve this issue

@anushbhatia you can assign me this issue

**Comment by anushbhatia** [comment]
Sure take your time do give an update within 3 days.
