### ISSUE TITLE
Adding a feature to save last instance

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#636]
To save the last instance of the sketch he/she made on the sheet and not giving him a blank sheet instead.
The last time you came to the site you created a square it should be there when you open it again.
![image](https://user-images.githubusercontent.com/40017559/111083204-4eb0ca00-8532-11eb-8dca-ddfacaa7b639.png)

**Comment by ashuvssut** [comment]
It would like to try this one

**Comment by ashuvssut** [comment]
@anushbhatia when I am trying to save the lines drawn array in a string...the size is enormous

![image](https://user-images.githubusercontent.com/60546840/111137283-d51dd980-853b-11eb-8fa1-2ec4b78614f9.png)

5-6 lines contribute to 127mb of storage space

Do you have any idea how should I store this data?

**Comment by anushbhatia** [comment]
> @anushbhatia when I am trying to save the lines drawn array in a string...the size is enormous
> 
> ![image](https://user-images.githubusercontent.com/60546840/111137283-d51dd980-853b-11eb-8fa1-2ec4b78614f9.png)
> 
> i have drawn 6 lines that contributed to 6 snapshots. 6 snapshots = 127mb
> so 1 snapshot = 21mb
> 
> @anushbhatia I suggest to delete all snapshots and **keeping the last snapshot only**.
> 
> ⚠⚠⚠by Deleting all snapshots the user cant undo/redo anymore
> 
> So I suggest to save the last snapshot and delete the rest.
> 
> browser localStorage can only store upto 5mb. I think I have to use some extra file to store this outside the browser (will require user permission)
> 
> OBSERVATION: the snapshot size increases with increase in sketch page size. so to stay safe lets assume that we need upto 60-70mb to store a single snapshot.

Sure we can go ahead with the saving only last snapshot of the user. Can in any case we can compress the screenshot and store that in local storage. needing user permission can be a temporary solution on exit you can ask an alert prompt adding the relevant to text to either discard or save for later.

**Comment by ashuvssut** [comment]
Ok I will see about that. if 21mb compresses to 2-3mb then its great we can use local storage

**Comment by ashuvssut** [comment]
I have tried various option to compress that 21 mb.. but I was able to compress to 11.6mb only. I think I have to store this snapshot outside the browser (will require user permission)

I think e
![Annotation 2021-03-17 113219](https://user-images.githubusercontent.com/60546840/112003609-45999d00-8ade-11eb-8e10-36ea5e572087.jpg)

**Comment by anushbhatia** [comment]
> I have tried various option to compress that 21 mb.. but I was able to compress to 11.6mb only. I think I have to store this snapshot outside the browser (will require user permission)
> 
> ![Annotation 2021-03-17 113219](https://user-images.githubusercontent.com/60546840/112003609-45999d00-8ade-11eb-8e10-36ea5e572087.jpg)

Ok then we can go ahead with the permission thing

**Comment by ashuvssut** [comment]
Hello @smaranjitghose , @anushbhatia 

I have a good news. we can use the local storage.

I came up with a simpler solution. I got to save that image data in kbs

imagedata is <50kb size
