### ISSUE TITLE
Add Tech Stack Icons to Sketch Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#637]
## Sample Icons

![WhatsApp Image 2021-03-15 at 2 00 39 AM](https://user-images.githubusercontent.com/40017559/111083274-b5ce7e80-8532-11eb-9ea4-f22836e4024b.jpeg)

## Requirements:

- Do not mess up any other part of the web app
- Add an icon on the horizontal menu, on clicking which a drop-down/another bar appears below showing options for icons representing common tech stack icons like HTML5, CSS3, JS, Python, React, Node, Express, Postgres, MySQL, MongoDB, ElasticSearch, Redis, Django, fastapi, Tensorflow, PyTorch, OpenCV, huggingface, streamlit, spacy,git, jupyter, colab, github,travisci, circleci, jenkins, terraform etc
- Add up to 30 different icons
- Please test this thoroughly before giving a PR
- Make use of any open source icons (or make custom icons) for this. You are required to give references in the PR description.

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

**Comment by ashuvssut** [comment]
If you mean that we need to add svg icons in our sketch page... like we are doing with arrow-icons (which are svgs too)...then I would like to work on this

**Comment by ashuvssut** [comment]
I will create a button that says "add icon" in the sketch page....after clicking that button a white screen appear which tells the user to select an icon. after the user selects one icon... the user gets to use that icon in the sketch page!

If you like the "separate white screen for showing icons idea" then I want to work on this

working on this idea would require to put a HOLD on those other "create icon pack" issues coz this white page needs to be created first

**Comment by anushbhatia** [comment]
> I will create a button that says "add icon" in the sketch page....after clicking that button a white screen appear which tells the user to select an icon. after the user selects one icon... the user gets to use that icon in the sketch page!
> 
> If you like the "separate white screen for showing icons idea" then I want to work on this
> 
> working on this idea would require to put a HOLD on those other "create icon pack" issues coz this white page needs to be created first

This is what we require not individual icons

**Comment by smaranjitghose** [comment]
> If you mean that we need to add svg icons in our sketch page... like we are doing with arrow-icons (which are svgs too)...then I would like to work on this

This is the requirement!

**Comment by niyatitotala** [comment]
Hello, Can I work on this? @smaranjitghose

**Comment by ashuvssut** [comment]
progress 85%. will submit PR for this one and other iconsPack issues today

**Comment by smaranjitghose** [comment]
> Hello, Can I work on this? @smaranjitghose

After 3 days. Once @ashuvssut has submitted his initial PR
