### ISSUE TITLE
We need links at index.html

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#64]
pls provide me details, so that I put links at footer

**Comment by debanshu08** [comment]
Please assign this issue to me.

**Comment by smaranjitghose** [comment]
Links to what? Can you please be specific?

**Comment by anushbhatia** [comment]
Don't create unecessary issues

**Comment by himanshujaidka** [comment]
please see the footer section of the index.html

**Comment by smaranjitghose** [comment]
> please see the footer section of the index.html

We have raised a separate issue for the footer to be done from scratch. That's a bug there which was initially meant for social media icons
