### ISSUE TITLE
Modify Contributor Section @Home Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#642]
![image](https://user-images.githubusercontent.com/40017559/111083990-6ee28800-8536-11eb-877e-03a1623bb282.png)

## Requirements
- Make the cards of the contributors round in shape(add border radius)
- Reduce the size of the cards so that all 65 contributors' details can easily be accomodated

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

**Comment by malavikarajeshvikraman** [comment]
Hi ,I am Malavika participating GSSOC'21 .
I am interested in contributing to this issue could you please assign me this  .

**Comment by anushbhatia** [comment]
Assigned for 4 days

**Comment by malavikarajeshvikraman** [comment]
![Screenshot 2021-03-15 124409](https://user-images.githubusercontent.com/42905287/111116553-31104e80-858c-11eb-9cc6-de7de480f737.jpg)
Is this fine ?

**Comment by anushbhatia** [comment]
> ![Screenshot 2021-03-15 124539](https://user-images.githubusercontent.com/42905287/111116673-5f8e2980-858c-11eb-989d-9ca4f64a71cc.jpg)
> 
> Is this fine ?

More circular. just like the profile picture of GitHub in the top right corner. Try adding all the contributors here.

**Comment by malavikarajeshvikraman** [comment]
Is it fine now ? 
![Screenshot 2021-03-15 171957](https://user-images.githubusercontent.com/42905287/111149277-b0b11400-85b2-11eb-92f9-caac839ab3d2.jpg)

**Comment by kanishkaa24** [comment]
Hello! Can I work on this?

**Comment by smaranjitghose** [comment]
> Is it fine now ?
> ![Screenshot 2021-03-15 171957](https://user-images.githubusercontent.com/42905287/111149277-b0b11400-85b2-11eb-92f9-caac839ab3d2.jpg)

Perfect. Do give a PR!

**Comment by smaranjitghose** [comment]
> Hello! Can I work on this?

After 2 days

**Comment by smaranjitghose** [comment]
Reminder:

- Give an appropriate title
- Refer to the Issue using `Closes # issue_no`
- Description of the changes(Bullet Points)
- Screenshot/Clip of the change

**Comment by smaranjitghose** [comment]
@malavikarajeshvikraman Raise a PR for your changes

 Please ensure that you follow the PR guidelines given above or in the Contributing.MD before raising a PR

**Comment by malavikarajeshvikraman** [comment]
Okay @smaranjitghose  will raise a PR following the guidelines .
