### ISSUE TITLE
Removing the contact page tab

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#646]
Removing the entire contact page and placing it in the Home Page below the "Open Source" section.

### Remove from here
![image](https://user-images.githubusercontent.com/40017559/111084607-2f696b00-8539-11eb-924f-f89901497b1f.png)

### Place it here
![image](https://user-images.githubusercontent.com/40017559/111084589-21b3e580-8539-11eb-8c24-6d458e6fe91a.png)

**Comment by nijin26** [comment]
I would like to do this task.

Can you please assign this task to me?

Thanks
Nijin Nazar

**Comment by CyberneTech** [comment]
Hey, I would like to work on this issue. Can you please assign this to me?

**Comment by lakshita15** [comment]
Hello, I am a participant of GSSoC'21. I can contribute to this issue.
Please assign me this task

**Comment by smaranjitghose** [comment]
@nijin26 You have a day for this. After that @lakshita15 can take over.

**Comment by nijin26** [comment]
> @nijin26 You have a day for this. After that @lakshita15 can take over.

It's done. any changes?
Sorry for the delay, my PC got some prblm yesterday.
