### ISSUE TITLE
Issue with buttons on editor page

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#65]
there is confusion between the button present on the editor page. We have to change the text on the button or change the UI design so that we are able to add more features and in future users clearly understand the functionality of buttons.
![Screenshot (49)](https://user-images.githubusercontent.com/58654018/90172615-eabdfb80-ddc0-11ea-874d-43fa23a313e9.png)

**Comment by anushbhatia** [comment]
this issue already exists in editor page don't create these until u don't ask a mentor for it.
