### ISSUE TITLE
Add padding and scroll options to the editor

### ISSUE THREAD

**Issue by Rishab-j** [smaranjitghose/doc2pen#658]
Right now the editor does not look so real.
By adding default padding and giving a scroll option it would feel more real.

**Comment by EANimesha** [comment]
I'm a gssoc participant. I like to try this issue

**Comment by krishnmohan19** [comment]
hey @Rishab-j 
i would like to contribute on this issue please assign me this issue.

**Comment by Rishab-j** [comment]
Hey @EANimesha @krishnmohan19 
I am not the project admin
I am also a GSSOC participant like you both.
I found this issue while running and somewhat testing the website on my system.

So I think the mentors or project admin will assign this issue to me.

**Comment by smaranjitghose** [comment]
> Right now the editor does not look so real.
> By adding default padding and giving a scroll option it would feel more real.

Assigned for 3 days. Give two PRs. First, for the padding, you suggest incorporating and once that is merged, a follow up PR for your scroll bar suggestion.

Please ensure:
- The title of the PR is short and meaningful
- You refer to the respective issue in the PR description ``Resolves # issue_number``
- Attach screenshot(s)/clip of the result of your changes
- (In bullet points) describe your changes
