### ISSUE TITLE
Opening Editor and Sketch Page in different tab

### ISSUE THREAD

**Issue by Sweeti-Gupta** [smaranjitghose/doc2pen#659]
If the Editor and Sketch will open in different tab, it will be very user-friendly.
Suppose a user is working in Editor, and in the mid of his work he/she wants to come back to the Home page, then his work on Editor will be lost.
Second thing is it will give an opportunity to the user to work on both editor and sketch by switching between the tabs and without losing their work.
Hey @mohit355, I want to work on this as a part of GSSOC'21. Please assign me this issue.

**Comment by mandepsingh** [comment]
please assign this task to me,
I am interested i the work.

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by smaranjitghose** [comment]
Not required as of now.
Perhaps in the later phases of the project.
For now, the simple solution would be to open two different tabs side by side

**Comment by Sweeti-Gupta** [comment]
Ok Sir
