### ISSUE TITLE
Add device related icons to the Sketch Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#668]
## Sample Icons
![mobile_icons](https://user-images.githubusercontent.com/46641503/111236971-14baf300-861a-11eb-9f65-db20edc3dcf3.jpeg)

## Requirements:

- Do not mess up any other part of the web app
- Add an icon on the horizontal menu, on clicking which a drop down/another bar appears below showing options for icons representing laptops, pc, phones, etc which can be imported as a shape like the other ones
- Add up to 10 different icons
- Please test this thoroughly before giving a PR
- Make use of any open source icons (or make custom icons) for this. You are required to give references in the PR description.

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

**Comment by ashuvssut** [comment]
i want to work on this

**Comment by smaranjitghose** [comment]
> i want to work on this

Assigned for 3 days
