### ISSUE TITLE
Create a New Page called MediaManip

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#676]
## Basic UI Suggestion:

![media_manip](https://user-images.githubusercontent.com/46641503/111247232-9ec08700-862d-11eb-898e-93c3c02fb6a4.png)

## Requirements:
- Do not mess up the code for the other pages
- Create a new page MediaManip
- Update the navbar
- Do the routing properly (Do not give a PR with routing w.r.t local host. We will immediately close it)
- Keep the page simple
- Have a section called **Image Converter**(put an appropriate heading)
- [Sample Reference](https://png2jpg.com/) w.r.t to functionality
- DO NOT copy-paste the exact UI of the reference.
- Have an option to download (perhaps trigger it once it is done)
- Have an area to upload images in a batch(maximum of 30 images)
- Functionalities (Dropdown options for input and ouput):
         - PNG to JPG
         - JPG to PNG
         - PNG to WEBP
         - WEBP to PNG
         - JPG to WEBP
         - WEBP to PNG
         - JIFF to PNG
         - JIFF to JPG
- **, For the time being, do not implement any of the above functionalities**

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

**Comment by ashuvssut** [comment]
I want to work on this

**Comment by smaranjitghose** [comment]
> I want to work on this

Finish up the other 5 PRs. If no one takes up the issue within the next couple of days and your other work is complete, it would be assigned to you.

**Comment by nijin26** [comment]
I would like to work on this issue. 

Can you assign this task to me ?

**Comment by smaranjitghose** [comment]
> I would like to work on this issue.
> 
> Can you assign this task to me ?

Assigned for 3 days

**Comment by lipsa199** [comment]
I would like to work on this issue .
