### ISSUE TITLE
Improve the Form UI of the Contact Section @Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#677]
## Requirements:

- Re-design the Contact Form

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

**Comment by Rohit-Parameswaran** [comment]
### Improving form UI of Contact section
I intend to increase the width of the contact form as stated in the requirements above and I would also like to add a couple of light-weight animation/transition effects to the message field and the emoji reactions.

**Comment by smaranjitghose** [comment]
@Rohit-Parameswaran Assigned for 2 days.

**Comment by padmajabhol** [comment]
I'm interested.

**Comment by samidha28** [comment]
Please assign this to me

**Comment by anushbhatia** [comment]
Any update?

**Comment by Mus2413** [comment]
Hello, I am Gssoc'21 participant . I would like to contribute on this project. Could you please assign me this issue.

**Comment by samidha28** [comment]
Hey !
I'm new to open source ,I've fixed the doc a little and increased the
scale for emojis. It'll be really helpful if you can guide me as to what
else I can change.
Please help me in making my first PR.

**Comment by samidha28** [comment]
Hey ! I was working on the issue ,I made few doc fixes and changed scaling of emojis .
Can you re-assign it to me ? and,
It will be helpful if you can suggest me any more changes .

**Comment by smaranjitghose** [comment]
> Hey ! I was working on the issue ,I made few doc fixes and changed scaling of emojis .
> Can you re-assign it to me ? and,
> It will be helpful if you can suggest me any more changes .

Please finish it within 2 days and give a PR.

Change the background of the form as well. consult with @anushbhatia if required

**Comment by samidha28** [comment]
Yeah sure ! Thanks .
