### ISSUE TITLE
Meta Tag Bug @Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#678]
![meta_tags](https://user-images.githubusercontent.com/46641503/111254416-092bf400-863b-11eb-8d9c-b230df1c2700.png)

Update this to simply display "Doc2pen"

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

**Comment by Rohit-Parameswaran** [comment]
### Updating meta tag (#678)
I wish to update the "Doc2pen - Contact us" page title that is being displayed in the Home page

**Comment by smaranjitghose** [comment]
> ### Updating meta tag (#678)
> I wish to update the "Doc2pen - Contact us" page title that is being displayed in the Home page

Assigned for 1 day
