### ISSUE TITLE
Convert all CSS related to Home Page to SCSS

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#679]
## Requirements:

- Self-Explanatory
- Do not mess up the other parts of the web app
- Test your changes thoroughly before giving a PR

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

**Comment by ashuvssut** [comment]
I want to work on this

Will complete within 1day

**Comment by smaranjitghose** [comment]
> I want to work on this
> 
> Will complete within 1day

Split the PR for this into 3 parts since there are multiple sections on the home page.

Coordinate with @lakshita15 since she is working on a part of the home page that would require changing some css into scss. Once her PR is merged give your PR

**Comment by smaranjitghose** [comment]
@ashuvssut **Only and Only if** you are able to complete this, raise two more issues for Editor and Sketch pages as well for the same tasks

**Comment by ashuvssut** [comment]
ha I will do all the sections and divide it in 3 PRs
