### ISSUE TITLE
Modifications to section home_about (id)

### ISSUE THREAD

**Issue by Lza-etc** [smaranjitghose/doc2pen#680]
Hi 
I would like to make modification to the page with title "what are we about?"
Would you please assign me to do this.

**Comment by smaranjitghose** [comment]
> Hi
> I would like to make modification to the page with title "what are we about?"
> Would you please assign me to do this.

Could you please be more specific about the modifications you are suggesting?

**Comment by Lza-etc** [comment]
I suggest modifications to title's font and color would be better . 
The changing the alignment of the paragraph a bit can make it more good .

**Comment by anushbhatia** [comment]
Sure go ahead with it.

**Comment by smaranjitghose** [comment]
Any updates @Lza-etc ?

**Comment by Lza-etc** [comment]
Yes , I will PR today

**Comment by anushbhatia** [comment]
@Lza-etc any update?

**Comment by smaranjitghose** [comment]
Closed due to inactivity
