### ISSUE TITLE
Modifications in the Experience form

### ISSUE THREAD

**Issue by 123mansha** [smaranjitghose/doc2pen#681]
**Before**

![doc2pen](https://user-images.githubusercontent.com/59260493/111266415-86159880-8650-11eb-97ee-1bd43d86d292.jpg)

**After**

![changed doc2pen1](https://user-images.githubusercontent.com/59260493/111266494-a34a6700-8650-11eb-8e2e-4ff0829c270e.jpg)

![changeddoc2pen0](https://user-images.githubusercontent.com/59260493/111266531-ad6c6580-8650-11eb-8651-9bcc99301787.jpg)

**_CHANGES PROPOSED_**
**1)** Changed the rate your experience emojis
          thumbs up--upvote (keep it up)
          thumbs down--downvote (needs improvement)
          clapping-- appreciable
          red heart-- loved it!!
          exploding head--mind blowing

**2)** Made modifications in the input fields so that each time the user enters the wrong information it will not accept it
_**For eg:**_ If a user enters text in place of number it will not accept it.

I am a GSSOC'21 participant.
Please assign me this issue.

**Comment by smaranjitghose** [comment]
Assigned for 2 days

**Comment by bishalshaw-164** [comment]
I'm gssoc'21 participant .
I want to work on this issue and make it colorful and impressive.
Can you assign issue to me ?

**Comment by subhasmitapradhan** [comment]
I would like to work on this issue. please kindly assign it to me.
-gssoc'21 participant

**Comment by 123mansha** [comment]
I have made the required changes 
Please check PR #721
