### ISSUE TITLE
Contributing guidelines link in Readme file showing error

### ISSUE THREAD

**Issue by pinnacle20** [smaranjitghose/doc2pen#686]
Hello sir, shivanand , GSSOC'21 participant
I would love to fix this issue. Can you please assign it to me?
thank you!

![sss](https://user-images.githubusercontent.com/73813570/111286352-1c08ed80-8668-11eb-9edd-995e4efacdf2.jpg)

**Comment by bishalshaw-164** [comment]
I'm gssoc'21 participant .I want to work on this issue
Can you assign issue to me ?

**Comment by smaranjitghose** [comment]
Seems to work fine as of now
