### ISSUE TITLE
Text append 

### ISSUE THREAD

**Issue by nishant23122000** [smaranjitghose/doc2pen#707]
//ISSUE
If we import a txt file Then there is no issue but if we import another file then the content of another file is appended with the first file content. 

//SOLUTION
I think we should remove the first file content first otherwise it will append continuously with other files content.

**Comment by anushka1309paul** [comment]
I would like to resolve this issue as a participant of GSSOC'21. Kindly assign it to me.

**Comment by nishant23122000** [comment]
Hey @anushka1309paul  i already did it , just waiting for assign

**Comment by anushka1309paul** [comment]
Ok!

**Comment by anushbhatia** [comment]
Assigned for 5 days.

**Comment by rk05-lenavo** [comment]
I am a GSSoC'21 participant @anushbhatia 
Can you assign me this issue

**Comment by nishant23122000** [comment]
@anushbhatia close this issue because it's already merged
