### ISSUE TITLE
Adding dark theme to the editor section

### ISSUE THREAD

**Issue by Adityakarthik18** [smaranjitghose/doc2pen#711]
i want to add dark theme to the editor section

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this...
-gssoc'21 participant

**Comment by subhasmitapradhan** [comment]
I would like to work on this issue, kindly assign it to me.

**Comment by anushbhatia** [comment]
No use in having a dark theme to the editor as the pen colours and the font will confuse the user what will be the expected output to this.,
