### ISSUE TITLE
Favicon not properly visible

### ISSUE THREAD

**Issue by ruhci28** [smaranjitghose/doc2pen#712]
@smaranjitghose  The pen-paper favicon is not properly visible. We should change it to some bright color.

**Comment by theSatvik** [comment]
I am a GSSOC'21 Participant, Please assign me this issue.

**Comment by anushbhatia** [comment]
sure do define dynamic favicon according to the browser theme of the user.

**Comment by anushbhatia** [comment]
Assigned for 5 days

**Comment by smaranjitghose** [comment]
any updates?

**Comment by ruhci28** [comment]
Yeah i am working on that

**Comment by ambivert-sam** [comment]
@ruhci28  I am a GSSOC'21 Participant, Can I work with this issue?

**Comment by ruhci28** [comment]
Go ahead

**Comment by smaranjitghose** [comment]
Closed due to inactivity
