### ISSUE TITLE
Underline Feature in Editor

### ISSUE THREAD

**Issue by ruhci28** [smaranjitghose/doc2pen#713]
we can add an underline feature in the editor to make more realistic

**Comment by theSatvik** [comment]
I am a GSSOC'21 Participant, Please assign me this issue.

**Comment by anushka1309paul** [comment]
I would like to work on this issue as a participant of GSSOC'21, kindly assign me this to me

**Comment by anushbhatia** [comment]
> we can add an underline feature in the editor to make more realistic

Great suggestion you can work on it.

**Comment by ruhci28** [comment]
Yeah sure i  will make a PR soon

**Comment by shahina-bano** [comment]
I want to implement this underline functionality, so kindly assign me this issue  @anushbhatia .

**Comment by anushbhatia** [comment]
Any update?

**Comment by shahina-bano** [comment]
> Any update?

yes, I m working on it, due to exams it got delayed...and will try to complete it by tomorrow.... so please don't unassign me @smaranjitghose  @anushbhatia

**Comment by anushbhatia** [comment]
Assigned for 3 days.

**Comment by shahina-bano** [comment]
@anushbhatia @smaranjitghose, actually I wanted to ask that the code after merging others PRs doesn't have the functionality of bold and italics, so I wanted to confirm that it was removed after your approval only right? Since I was thinking to implement the underline feature with bold and italics only but it's not there now in the main code.

**Comment by shahina-bano** [comment]
@anushbhatia sir I have done some work...but I am facing an issue... so can you please guide me a little.
I have implemented the underline thing, but the underline is not getting converted into an image along with the text.. So can you please tell me where the target is converted into image in the code?

**Comment by shahina-bano** [comment]
![Screenshot (327)_LI](https://user-images.githubusercontent.com/56913578/112745871-21036080-8fc9-11eb-8108-79d0c24279d3.jpg)

**Comment by smaranjitghose** [comment]
The entire issue was regarding adding a feature to the Editor and not the Sketch Page.

**Comment by shahina-bano** [comment]
Okay, I will implement it in the editor, sorry that was my mistake. Please open this issue again @anushbhatia
