### ISSUE TITLE
Certain special symbols omitted

### ISSUE THREAD

**Issue by anushka1309paul** [smaranjitghose/doc2pen#715]
Certain symbols such as, " , " , " @ ", " # " etc. on being imported from the txt file are not being displayed in the text area.
I would like to fix this issue, kindly assign the same to me.

**Comment by Sonaljain6431** [comment]
Hey, @anushka1309paul ! I am interested to work on this issue. Would you assign it to me?

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by anushka1309paul** [comment]
Respected sir,
This issue was already resolved by me and the PR was merged as well.
Could you close this issue please?
Thanks & Regards,
Anushka Paul

**Comment by smaranjitghose** [comment]
Oh sure!
