### ISSUE TITLE
their should be a sharing technique also

### ISSUE THREAD

**Issue by tanya070820** [smaranjitghose/doc2pen#727]
As to share it with others their should be a sharing technique.

**Comment by balarka135** [comment]
I would like to work on this issue. pls, assign me. I am Gssoc 21 participant

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by anushbhatia** [comment]
Could you elaborate more on this?

**Comment by tanya070820** [comment]
Please try to assign me this issue @smaranjitghose

**Comment by smaranjitghose** [comment]
> Please try to assign me this issue @smaranjitghose

Could you please explain your proposal in greater details first @tanya070820

**Comment by smaranjitghose** [comment]
Closed due to Inadequte work
