### ISSUE TITLE
Underline The words

### ISSUE THREAD

**Issue by nishant23122000** [smaranjitghose/doc2pen#730]
### I would like to suggest one feature,

There might be cases where the user wants to **underline** some words which are important from the user's perspective.

So, I think we need to add a feature to underline words which user wants

**Comment by shivansh-soni07** [comment]
I want to resolve this issue please assign it to me

**Comment by nishant23122000** [comment]
@shivansh-soni07  i already completed it, just waiting for assign

**Comment by anushbhatia** [comment]
theirs exist already an issue #713

**Comment by nishant23122000** [comment]
@anushbhatia  SO what about particular word color, bold, underline? can I do this?

**Comment by anushbhatia** [comment]
> @anushbhatia SO what about particular word color, bold, underline? can I do this?

you can raise an issue for strikethrough but bold isn't possible in real life.
