### ISSUE TITLE
Canvas Colour Option Missing from Sketch Page

### ISSUE THREAD

**Issue by nijin26** [smaranjitghose/doc2pen#736]
According to issue #634 and PR #690 is merged for adding Background or Canvas Colour Selecting Options.

But recently, it got missing due to other merges.

**Comment by nijin26** [comment]
Since one of my PR #726 is not merged. I am not able to create a new PR for this. I hope I have time to push the solution to this issue after the already mentioned PR get merged.

**Comment by anushbhatia** [comment]
You can create a new pr of a different branch on your codebase and push that.

**Comment by smaranjitghose** [comment]
Let this [PR](https://github.com/smaranjitghose/doc2pen/pull/735) be merged today after that we can continue

**Comment by nijin26** [comment]
I think this PR #735 solves the same issue.
