### ISSUE TITLE
Using Docker for the Project!

### ISSUE THREAD

**Issue by jain-rishabh-21** [smaranjitghose/doc2pen#739]
Can we use docker to set up an alternative setup and will be useful in the future.

**Comment by jain-rishabh-21** [comment]
If found useful, Please assign it to me.
Discord Username: krackerzzz#4371

**Comment by smaranjitghose** [comment]
Which server are you planning to use for the Docker image?

**Comment by jain-rishabh-21** [comment]
It is built on react so it can easily be done!

**Comment by jain-rishabh-21** [comment]
Can you please add the level also!

**Comment by smaranjitghose** [comment]
Closed due to inactivity

**Comment by jain-rishabh-21** [comment]
Hey @smaranjitghose , I have worked on it, Will raise a PR by today!
Please reopen the issue
