### ISSUE TITLE
Adding a Splash Screen

### ISSUE THREAD

**Issue by sameersrivastava13** [smaranjitghose/doc2pen#74]
# Description of the Feature
To give an end user immediate feedback that an application is starting and loading in the background.

**Comment by anushbhatia** [comment]
Give an example of the splash screen before making a PR

**Comment by sameersrivastava13** [comment]
@anushbhatia here is an example that i have implemented..
Also we can change the loading GIF to some other GIF whichever you want.

![splash](https://user-images.githubusercontent.com/56088741/90332202-b7ee5000-dfd8-11ea-834e-3b7356476459.gif)

**Comment by imsahil007** [comment]
> @anushbhatia here is an example that i have implemented..
> Also we can change the loading GIF to some other GIF whichever you want.
> 
> ![splash](https://user-images.githubusercontent.com/56088741/90332202-b7ee5000-dfd8-11ea-834e-3b7356476459.gif)

Looks great. Keep in mind to attach the final output as gif along with the PR @sameersrivastava13

**Comment by sameersrivastava13** [comment]
@anushbhatia  @imsahil007 Actually when i was implementing this i saw that already there is a pre-loading screen added.

![Screenshot (41)](https://user-images.githubusercontent.com/56088741/90338484-a3757c00-e007-11ea-951b-580fc8fecbfa.png)

**Comment by smaranjitghose** [comment]
> @anushbhatia here is an example that i have implemented..
> Also we can change the loading GIF to some other GIF whichever you want.
> 
> ![splash](https://user-images.githubusercontent.com/56088741/90332202-b7ee5000-dfd8-11ea-834e-3b7356476459.gif)

This is for the other project 😅

**Comment by anushbhatia** [comment]
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/40017559/90339062-f2251500-e00b-11ea-9e0f-5cfba70ee85f.gif)
use this

**Comment by sameersrivastava13** [comment]
@smaranjitghose yeah actually i was giving @anushbhatia an example that i have implemented.😅

**Comment by sameersrivastava13** [comment]
> > @anushbhatia here is an example that i have implemented..
> > Also we can change the loading GIF to some other GIF whichever you want.
> > ![splash](https://user-images.githubusercontent.com/56088741/90332202-b7ee5000-dfd8-11ea-834e-3b7356476459.gif)
> 
> Is this for the other project- Auto Vaidya😅?

@smaranjitghose yeah actually i was giving @anushbhatia an example that i have implemented.😅

**Comment by sameersrivastava13** [comment]
@anushbhatia after using the GIF you gave

> use this
> For this message me on slack

![Screenshot (44)](https://user-images.githubusercontent.com/56088741/90339688-ed626000-e00f-11ea-83d2-ddffa0778d45.png)

**Comment by smaranjitghose** [comment]
@sameersrivastava13  Any updates>?
