### ISSUE TITLE
Not able to increment or decrement value

### ISSUE THREAD

**Issue by nishant23122000** [smaranjitghose/doc2pen#740]
When I increment or decrement the font size or anything else I get an error:

![image](https://user-images.githubusercontent.com/53515714/111948363-0b8fc180-8b05-11eb-9744-b3916ca446e7.png)

I think there is not any onElementValueChange function inside editContext in the editor section. 

We have to solve this issue because I am unable to change letter-spacing, width, font-size etc

**Comment by smaranjitghose** [comment]
Closed due to inactivity
