### ISSUE TITLE
Improvement of Contact Us Form

### ISSUE THREAD

**Issue by ShubhamSj07** [smaranjitghose/doc2pen#741]
Contact-Us form validations is not properly validated , also when we submit form page gets reloaded 
Also phone no. field is not required
I would like too **validate** form with proper error messages and also **onSubmitting** form we will show a **card!** with some msg

Please assign me this issue
Thanks!

**Comment by Ayushgup85** [comment]
Is this issue still open?

**Comment by ShubhamSj07** [comment]
@Ayushgup85, I am working on this issue!

**Comment by Ayushgup85** [comment]
ok

**Comment by ShubhamSj07** [comment]
@smaranjitghose , @anushbhatia , pls let me know which color should we go for err msg!
so that i can open pr ASAP!

Color-01
![Color-01](https://user-images.githubusercontent.com/56510414/112590869-84568c80-8e29-11eb-9bee-dbd3dc7b18aa.JPG)

Color-02
![Color-02](https://user-images.githubusercontent.com/56510414/112590881-87517d00-8e29-11eb-818c-fc550bd48eff.JPG)

Color-03
![Color-03](https://user-images.githubusercontent.com/56510414/112590889-891b4080-8e29-11eb-9f77-dff0ce125330.JPG)

**Comment by ShubhamSj07** [comment]
@anushbhatia , pls review above colors

**Comment by smaranjitghose** [comment]
This makes the UI even worse. Just raise an alert message when the submit button is pressed without the necessary details

**Comment by smaranjitghose** [comment]
Just checked we already have that. This issue is pointless

**Comment by ShubhamSj07** [comment]
> Just checked we already have that. This issue is pointless

Do check contact us form validations!
No proper err message on fields, everything is cluttered and also on submitting form page is getting reloaded which shouldn't be happening!
I suggested my idea of improving form also on submitting form we were going to show msg card.
But no issues , nice to meet u guys👋🏻

**Comment by smaranjitghose** [comment]
![form_validations](https://user-images.githubusercontent.com/46641503/112715337-a02f6080-8f05-11eb-9ec5-1559a9e60c56.png)

**Comment by ShubhamSj07** [comment]
@smaranjitghose ,this is how i was going to do....

Preview

https://user-images.githubusercontent.com/56510414/112719561-8438b880-8f1f-11eb-9dd8-cf7bbbef654b.mp4

**Comment by smaranjitghose** [comment]
> @smaranjitghose ,this is how i was going to do....
> 
> Preview
> 
>  Doc2Pen_Contact-Us_Form.mp4

If it was a sign up or login form, it would have definitely made sense to add that. However, for a compact contact form as this one, it would be an overkill
