### ISSUE TITLE
Adding Tech stack used in the project

### ISSUE THREAD

**Issue by RaveenaBhasin** [smaranjitghose/doc2pen#743]
I would like to add the tech stack used in the project so that readme file will look attractive

**Comment by Nishayadav-bit** [comment]
Hello, I would like to work oh this issue .Please assign to me 
and I'm a GSSOC'21 participant

**Comment by smaranjitghose** [comment]
@RaveenaBhasin you have 1 more day to complete this or else the issue and the corresponding PR would be closed

**Comment by RaveenaBhasin** [comment]
@smaranjitghose I'm not able to find logo for scss anywhere. Will it be ok if I leave it like css only?

**Comment by Sonaljain6431** [comment]
Hey, I am interested to work in this issue. Would you assign it to me?

**Comment by smaranjitghose** [comment]
> @smaranjitghose I'm not able to find logo for scss anywhere. Will it be ok if I leave it like css only?

Check [this](https://worldvectorlogo.com/logo/sass-1)

**Comment by smaranjitghose** [comment]
Closed due to failure to meet deadlines
