### ISSUE TITLE
Less shapes available for sketch

### ISSUE THREAD

**Issue by alkatrivedi** [smaranjitghose/doc2pen#744]
There are currently 8 shapes for sketching. There should be more sketches in that section like bidirectional connector, ellipse, rectangle, etc.
![Capture](https://user-images.githubusercontent.com/58396306/112093808-1bb8a700-8bc0-11eb-8529-e4903ff2cc18.PNG)

I am a GSSoC'21 participant and I would like to work on this issue. May I work on it under GSSoC'21?

**Comment by Sonaljain6431** [comment]
Hey @alkatrivedi ! I am interested to work in this issue. Would you assign it to me?
