### ISSUE TITLE
unable to scroll down in the sketch section 

### ISSUE THREAD

**Issue by akshay1027** [smaranjitghose/doc2pen#745]
unable to scroll down in the sketch section to access properties like "fill", "edge" and "undo/redo"

**Comment by anushbhatia** [comment]
any update?

**Comment by smaranjitghose** [comment]
To be taken care after [this](https://github.com/smaranjitghose/doc2pen/pull/735) is merged

**Comment by akshay1027** [comment]
able to scroll now! 🙌🏻
