### ISSUE TITLE
Navbar-links UI modification

### ISSUE THREAD

**Issue by Tanya933** [smaranjitghose/doc2pen#747]
I would like to modify the navbar links UI.
Please assign this issue to me .Thankyou.

before
<img width="1440" alt="Screenshot 2021-03-23 at 11 09 18" src="https://user-images.githubusercontent.com/60508925/112098744-4f97ca80-8bc8-11eb-9e72-79450c44a08b.png">

after
<img width="1440" alt="Screenshot 2021-03-23 at 11 24 22" src="https://user-images.githubusercontent.com/60508925/112099826-35f78280-8bca-11eb-8085-794225ca46a6.png">

**Comment by rk05-lenavo** [comment]
I'm  the participants in GSSOC'21.Please assign me this issue.

**Comment by smaranjitghose** [comment]
We are not modifying the navbar till the rest of the web app is sorted. It took quite some time to get it to it's current state. Perhaps in a few weeks!
