### ISSUE TITLE
Changing the color of favicon

### ISSUE THREAD

**Issue by sharvariiii** [smaranjitghose/doc2pen#749]
The current favicon is black in color so it is not clearly visible. I wanted to enhance the look by changing its color which will match with the color combination of the website. I am attaching the sample .Let me know if I can go ahead with it.
![doc2penlogo](https://user-images.githubusercontent.com/78595265/112304075-11330600-8cc3-11eb-899c-59396d9fecb5.png)
![doc2penlogo1](https://user-images.githubusercontent.com/78595265/112304131-2019b880-8cc3-11eb-9986-23d97f0955f1.png)

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant in this project. could you please assign me this?

**Comment by sharvariiii** [comment]
Dear mentors @smaranjitghose @anushbhatia waiting for your response on this. If it is suitable for our project kindly assign it to me. Thank you!

> The current favicon is black in color so it is not clearly visible. I wanted to enhance the look by changing its color which will match with the color combination of the website. I am attaching the sample .Let me know if I can go ahead with it.
> ![doc2penlogo](https://user-images.githubusercontent.com/78595265/112304075-11330600-8cc3-11eb-899c-59396d9fecb5.png)
> ![doc2penlogo1](https://user-images.githubusercontent.com/78595265/112304131-2019b880-8cc3-11eb-9986-23d97f0955f1.png)

**Comment by anushbhatia** [comment]
> Dear mentors @smaranjitghose @anushbhatia waiting for your response on this. If it is suitable for our project kindly assign it to me. Thank you!
> 
> > The current favicon is black in color so it is not clearly visible. I wanted to enhance the look by changing its color which will match with the color combination of the website. I am attaching the sample .Let me know if I can go ahead with it.
> > ![doc2penlogo](https://user-images.githubusercontent.com/78595265/112304075-11330600-8cc3-11eb-899c-59396d9fecb5.png)
> > ![doc2penlogo1](https://user-images.githubusercontent.com/78595265/112304131-2019b880-8cc3-11eb-9986-23d97f0955f1.png)

This is good but it is barely visible.

**Comment by smaranjitghose** [comment]
@sharvariiii Could you just integrate this into your copy of the web app's code and send a small clip of the same. Because in this zoomed view, it is difficult to judge since the actual size would be much less in practice

**Comment by smaranjitghose** [comment]
@sharvariiii any updates>?

**Comment by smaranjitghose** [comment]
Closed due to inactivity
