### ISSUE TITLE
Adding scrollbar in the editor page

### ISSUE THREAD

**Issue by gritika18** [smaranjitghose/doc2pen#750]
The editor section doesn't have a scroll bar to see contents at the top of page once the page reaches the view limit.

**Comment by lopeselio** [comment]
can I work on this issue ?

**Comment by vanisingh-24** [comment]
I'd like to work on this issue. Please assign me this issue.

**Comment by anushbhatia** [comment]
inside the editor there's no need for a scrollbar

**Comment by smaranjitghose** [comment]
> inside the editor there's no need for a scrollbar

Touche!
