### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by ANSHIKA1806** [smaranjitghose/doc2pen#751]
@anushbhatia @iamdarshshah @Harshita-Kanal 
README is the first file one should read when starting a new project. It's a set of useful information about a project, and a kind of manual. A README text file appears in many various places and refers not only to programming. So i want to make your README file more meaningful and more easier to understand the whole project.

**Comment by ANSHIKA1806** [comment]
@anushbhatia @iamdarshshah @Harshita-Kanal 
please assign this task to me , i would love to contribute to your organization
thank you.

**Comment by anushbhatia** [comment]
it is currently giving all necessary details present in the project.

**Comment by smaranjitghose** [comment]
@ANSHIKA1806 Whenever you raise a documentation related issue, please be specific about the exact things you want to add
