### ISSUE TITLE
GitHub Reference in Footer

### ISSUE THREAD

**Issue by lopeselio** [smaranjitghose/doc2pen#752]
can I work on this for GSSOC 21 ?

**Comment by anushbhatia** [comment]
Sure but do add minimal icons from https://feathericons.com/ or https://useanimations.com/ to implement it.

**Comment by smaranjitghose** [comment]
> can I work on this for GSSOC 21 ?

Make it as simplistic as possible. Assigned for 2 days

**Comment by lopeselio** [comment]
Surely 😀

**Comment by lopeselio** [comment]
@anushbhatia @smaranjitghose Can you add the gssoc label to the issue? So that it would count for the GSSOC programme?

**Comment by lopeselio** [comment]
Also should I add it to the footer or to the header component?

**Comment by lopeselio** [comment]
![image](https://user-images.githubusercontent.com/43913734/112645979-0d42e780-8e6d-11eb-84d9-2f0a5a265665.png)

As requested, I have kept it simple, and used icons from https://feathericons.com/  shall I create a Pull Request. 
@anushbhatia @smaranjitghose
