### ISSUE TITLE
tour for the new users.

### ISSUE THREAD

**Issue by bindu030** [smaranjitghose/doc2pen#756]
We have to make sure all the new users are aware of all the options available to use for their editing.
PLease assign me this issue.
Thanks.

**Comment by anushbhatia** [comment]
Sure you can do this do explain the methodologies and the libraries used for this.

**Comment by smaranjitghose** [comment]
> We have to make sure all the new users are aware of all the options available to use for their editing.
> PLease assign me this issue.
> Thanks.

Please elaborate on how you plan to achieve this goal

**Comment by smaranjitghose** [comment]
Closed due to inactivity
