### ISSUE TITLE
Transform Steps to Cards

### ISSUE THREAD

**Issue by Saatvik21** [smaranjitghose/doc2pen#757]
I would like to transform the steps to cards and also add hover effects to them. 

Kindly assign me this issue under GSSoC'21.

- Result 👇

![Screenshot_3](https://user-images.githubusercontent.com/61618767/112584589-23758700-8e1e-11eb-8651-6844166f727b.png)

**Comment by Twinkle-Shimmer** [comment]
@Saatvik21  please assign me, i am participant

**Comment by smaranjitghose** [comment]
No, it would make the UX weird with too much of cards
