### ISSUE TITLE
hovered card size should be little small and shadow of button should be less

### ISSUE THREAD

**Issue by Twinkle-Shimmer** [smaranjitghose/doc2pen#758]
![60ae9ba1-7dd2-451a-975c-e1c0821f1d6c](https://user-images.githubusercontent.com/72192456/112598794-1ca63e80-8e35-11eb-9375-d15d6528e7fe.jpeg)

**Comment by Mus2413** [comment]
Hello, I am Gssoc'21 participant . I would like to contribute on this project. Could you please assign me this issue.

**Comment by Nishayadav-bit** [comment]
Hey , I would like to work on this issue please assign to me .
I am a participant in GSSOC'21

**Comment by anushbhatia** [comment]
Sure assigned for 3 days.

**Comment by Twinkle-Shimmer** [comment]
@anushbhatia  
![linux](https://user-images.githubusercontent.com/72192456/112708552-9ba08300-8ed8-11eb-9d5f-cbcafce7f432.jpeg)
