### ISSUE TITLE
Logo does not redirect to top section of homepage

### ISSUE THREAD

**Issue by aanchal-fatwani** [smaranjitghose/doc2pen#759]
ISSUE DETAILS
Currently, the logo does not redirect to the top section when the user is browsing the home page.
It should be redirected to the top section, to make it sync with the functionality which the user would experience from any other page or by clicking the Home tab on the header section.

**Comment by aanchal-fatwani** [comment]
Hey @smaranjitghose, @anushbhatia, I am a GSSOC 2021 participant. I would like to work on the issue. 
Could you please update the issue with relevant tags and assign the same?

**Comment by nikhv** [comment]
Hello @smaranjitghose, @anushbhatiaI ,I am a GSSOC 2021 participant. 
I want to work on this issue please assign this issue to me

**Comment by Mus2413** [comment]
Hello, I am Gssoc'21 participant . I would like to contribute on this project. Could you please assign me this issue.

**Comment by anushbhatia** [comment]
this can't be done as the component structure for every page is the same(means the header used everywhere is the same). Just for a small feature there would be lot of code repetition in the process
