### ISSUE TITLE
Adding New Fonts to the Editor

### ISSUE THREAD

**Issue by N-Shar-ma** [smaranjitghose/doc2pen#760]
## Proposal
I think all and any of the 71 fonts listed and shown here : https://goofonts.com/tag/authentic can be good font choices for the Editor page of Doc2Pen, as they all have a handwritten feel. I would like to add these fonts as style options for the user, under GSSoC'21. 

## A few examples:

![image](https://user-images.githubusercontent.com/68962290/112621607-2d2fc800-8de7-11eb-8323-f5b8ec8586e1.png)

![image](https://user-images.githubusercontent.com/68962290/112621665-3de03e00-8de7-11eb-8d45-7d3d6f17036f.png)

![image](https://user-images.githubusercontent.com/68962290/112621701-4c2e5a00-8de7-11eb-877c-2be1f468eea2.png)

![image](https://user-images.githubusercontent.com/68962290/112621760-5bada300-8de7-11eb-907b-a11e9ca0a270.png)

## Some Assistance needed
Since 71 is a big number, I'd appreciate some guidance on which fonts to add and which to not.

**Comment by Mus2413** [comment]
Hello, I am Gssoc'21 participant . I would like to contribute on this project. Could you please assign me this issue.

**Comment by anushbhatia** [comment]
Sure we want more cursive fonts present for example the ones given here 
1. beth ellen
2. Cedavire cursive

The more imperfections better it will the rest of the given fonts in the image are more computerized. 
List down the fonts that you find following these and make a list here then we can verify and you can give PR after that.

**Comment by N-Shar-ma** [comment]
I've shortlisted these, the ones marked with ⭐ I think are most suitable. Please give your views on the following fonts:

- Beth Ellen ⭐

![image](https://user-images.githubusercontent.com/68962290/112693036-23d14a80-8e3d-11eb-865c-62c69adac69b.png)


- Cedarville Cursive ⭐

![image](https://user-images.githubusercontent.com/68962290/112693067-35b2ed80-8e3d-11eb-83aa-15012d753282.png)


- Dawning Of A New Day ⭐

![image](https://user-images.githubusercontent.com/68962290/112693132-52e7bc00-8e3d-11eb-95cd-7d775cc8e29d.png)


- Give You Glory

![image](https://user-images.githubusercontent.com/68962290/112693173-67c44f80-8e3d-11eb-901d-bbacab8bf133.png)


- Kristi ⭐

![image](https://user-images.githubusercontent.com/68962290/112693211-79a5f280-8e3d-11eb-8679-cf95b82a8958.png)


- La belle Aurore

![image](https://user-images.githubusercontent.com/68962290/112693287-a1955600-8e3d-11eb-9951-910a06ed691b.png)


- Over the Rainbow ⭐

![image](https://user-images.githubusercontent.com/68962290/112693366-bd006100-8e3d-11eb-92d8-76329040a877.png)


- Ruthie ⭐

![image](https://user-images.githubusercontent.com/68962290/112693392-cbe71380-8e3d-11eb-9f75-59768a62da00.png)


- Zeyada

![image](https://user-images.githubusercontent.com/68962290/112693451-e7eab500-8e3d-11eb-9694-6f1a0ef14cc0.png)


- Meddon ⭐

![image](https://user-images.githubusercontent.com/68962290/112693665-41eb7a80-8e3e-11eb-9ce0-51c5c8397268.png)


- Zhi Mang Xing

![image](https://user-images.githubusercontent.com/68962290/112693828-870fac80-8e3e-11eb-9b21-e03375f8ad9f.png)


- League Script

![image](https://user-images.githubusercontent.com/68962290/112694476-aeb34480-8e3f-11eb-90dc-2efc549958ce.png)

**Comment by smaranjitghose** [comment]
This totally invalidates the purpose of the project. I we have to use fonts that do not closely resemble handwritings, we could have just used Google Docs

**Comment by N-Shar-ma** [comment]
@smaranjitghose You don't think any of those fonts work well for this project? What about the 2 that @anushbhatia liked? (Beth Ellen and Cedarville Cursive) 

I actually spent quite some time looking for and picking out suitable fonts, and then figuring out how to incorporate them in the project's code base, so I'd like to add at least 1-2 that you approve of. :)

**Comment by smaranjitghose** [comment]
> @smaranjitghose You don't think any of those fonts work well for this project? What about the 2 that @anushbhatia liked? (Beth Ellen and Cedarville Cursive)
> 
> I actually spent quite some time looking for and picking out suitable fonts, and then figuring out how to incorporate them in the project's code base, so I'd like to add at least 1-2 that you approve of. :)

Cedarville Cursive works but Beth Ellen is not that practical (nowadays, we don't have fountain pens using which the strokes would be so thick). If you wish you can go ahead with Cedarville Cursive
