### ISSUE TITLE
Canvas Color Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#765]
## Description

Whenever one tries to change the color of the canvas, the previous drawings disappear!

## Snapshots:

- Draw something on the default canvas

![Sketch_1](https://user-images.githubusercontent.com/46641503/112712552-70c52780-8ef6-11eb-8d42-114fcea36f3c.png)

- Try to change the canvas color

![Sketch_2](https://user-images.githubusercontent.com/46641503/112712562-791d6280-8ef6-11eb-8138-e3e1eaa55cd3.png)

- Previous work is lost!

![Sketch_3](https://user-images.githubusercontent.com/46641503/112712568-7cb0e980-8ef6-11eb-83ea-f24414d82e67.png)

__NOTE__: Please do not comment "I am Interested" or anything similar if you don't know how to resolve this

**Comment by ashuvssut** [comment]
i want to work on this
