### ISSUE TITLE
Add Line Color and Fill Color Options

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#767]
## Snapshot

![Sketch_Color](https://user-images.githubusercontent.com/46641503/112712773-6b1c1180-8ef7-11eb-968c-aebe9df88d07.png)

## Description

Currently, the sketch feature allows one to have either hollow or solid shapes. We intend to improve upon this by splitting the color feature to have:

- Line Color (Color of the strokes/boundaries of the figures)
- Fill Color (Color of the region enclosed by the figures in case the Fill Option is selected)

**Comment by ashuvssut** [comment]
i want to work on this
