### ISSUE TITLE
Opacity Feature UI @Sketch Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#768]
## Sample Snapshot:

![SKetch_opacoty](https://user-images.githubusercontent.com/46641503/112712833-e251a580-8ef7-11eb-80a3-3e5ba8b81133.png)

## Description:

Make the opacity option more appealing (i.e improve the UI of the slider). Additionally, remove the ability to see the amount of opacity. Having  both the quantitative option as well as GUI based option doesn't make much sense

**Comment by ashuvssut** [comment]
i want to work on this
