### ISSUE TITLE
Remove Title,Body @Editor Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#769]
## Sample Snapshot

![title_body](https://user-images.githubusercontent.com/46641503/112712891-54c28580-8ef8-11eb-83d2-ab1246a5d908.png)

## Description

At the current stage of the project, it does not make much sense to have separate options for title and body. Revamp the functions so that one can simply start entering text into the document without the already existing distinction of title and body

**Comment by N-Shar-ma** [comment]
I'd like to work on this!

**Comment by smaranjitghose** [comment]
> I'd like to work on this!

Assigned for 3 days
