### ISSUE TITLE
Unnecessary Links in the footer

### ISSUE THREAD

**Issue by Deshmukh-Omkar** [smaranjitghose/doc2pen#77]
## Description the change
There are multiple links in the footer which aren't fulfilling any purpose.

## Screenshots
![Screenshot 2020-08-16 at 12 10 59 PM](https://user-images.githubusercontent.com/42082976/90328377-8d40cf00-dfb9-11ea-9045-0c9fff431136.png)

**Comment by Nishtha3512** [comment]
Is there need to remove these links?

**Comment by imPGupta** [comment]
I will replace these by social media links. Assign me.

**Comment by AyushSatyam** [comment]
Please assign me. I will remove unwanted links and if necessary I will add some other links.

**Comment by Nishtha3512** [comment]
> Is there need to remove these links?
Let me know what I need to do here and please assign it to me

**Comment by anushbhatia** [comment]
Handled in footer issues
