### ISSUE TITLE
Improve Custom Scroll Bar UI

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#771]
## Requirements:

- Do not mess up any other part of the web app
- Ensure the color scheme of the new custom scroll bar conforms to that of the rest of the web app
- Feel free to use resources like dribble,codepen for inspirations but please **do not copy-paste** directly. I expect you to give references in the PR description
- The issue is self-explanatory given one has read the above points. Looking forward to your design tweaks!

__NOTE__: Do not blindly comment "I'm interested" or anything similar without having any improvements in mind. We are not going to exclusively give you pointers on this issue rather give you feedback on your proposal

**Comment by Abhishekkr93** [comment]
@smaranjitghose I would like to contribute as a Gssoc21 participant. could you please assign me this?

**Comment by smaranjitghose** [comment]
> @smaranjitghose I would like to contribute as a Gssoc21 participant. could you please assign me this?

Assigned for 3 days

**Comment by Abhishekkr93** [comment]
Okay, thanks for update!
