### ISSUE TITLE
Add Feature to Load Images from Local System on Sketch Page (similar to any photo editor)

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#774]
##  Requirements :

- Do not mess up any other part of the app that you are not working with
- Add a small button in the Editor Menu (Perhaps on the horizontal one)
- The functionality is self-explained by the title of the issue
- Write checks for importing images with extensions: .webp, .png, .jpeg. jpeg only

**Comment by Chaitanya31612** [comment]
@smaranjitghose I would like to work on this feature.

**Comment by smaranjitghose** [comment]
> @smaranjitghose I would like to work on this feature.

Assigned for 3 days

**Comment by shrishti-c** [comment]
Since, its been 5 days of issue being assigned, wanted to know if this issue is still open, I would like to work on it.

**Comment by smaranjitghose** [comment]
> Since, its been 5 days of issue being assigned, wanted to know if this issue is still open, I would like to work on it.

Assigned to you for 4 days

**Comment by shrishti-c** [comment]
On it :)

**Comment by anshika208** [comment]
hey!! @smaranjitghose if there is no update then can i work on it?

**Comment by smaranjitghose** [comment]
> hey!! @smaranjitghose if there is no update then can i work on it?

Sure. Assigned for 4 days
