### ISSUE TITLE
Image Format Conversion Functions @MediaManip

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#775]
In continuation to #676 

# Requirements:

Write functions to achieve the following conversions on the Media Manip page:

- PNG to JPG
- JPG to PNG
- PNG to WEBP
- WEBP to PNG
- JPG to WEBP
- WEBP to PNG
- JIFF to PNG
- JIFF to JPG

__NOTE__: Please do not take this issue if you don't have any clue how to resolve it. We expect multiple participants to work on this. Hence Please comment the exact functionality you wish to implement

**Comment by bijankundu** [comment]
I am not a participant of gssoc21, can I still work on this?

**Comment by Abhishek765** [comment]
@smaranjitghose Also Download button is not working properly, Media manip needs a lot of work Will work on this soon ;)

**Comment by smaranjitghose** [comment]
> @smaranjitghose I am not a participant of gssoc21, can I still work on this?

Sure

**Comment by bijankundu** [comment]
> 
> 
> > @smaranjitghose I am not a participant of gssoc21, can I still work on this?
> 
> Sure

actually, I am trying to convert the images using html5 canvas, though it's working fine with few files, but this might cause a problem if a large number of images are converted at a single go. While converting, the page might lag a bit. Do you have any alternate solution for this issue?

**Comment by bijankundu** [comment]
I am done with the media conversion part and also the download part. I can create a PR if you want or if we don't find an alternate solution.

**Comment by anushbhatia** [comment]
Sure just give the PR we will see if we can resolve it.
