### ISSUE TITLE
Add More fill Options for Figures @ Sketch Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#777]
## Sample Snapshot

![fill_style](https://user-images.githubusercontent.com/46641503/112713983-1d56d780-8efe-11eb-8b71-2fe0aadf5db5.png)

## Description

- The title explains the issue well!

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.

**Comment by smaranjitghose** [comment]
This is a continuation of the last PR @ashuvssut was working on. If he is unable to do it within a couple of days, then @AshuKV can go forward

**Comment by ashuvssut** [comment]
@AshuKV , I am removing current drawing methods and implementing roughjs instead.

So this issue is dependent on my work. My PR ETA: 2days

**Comment by ashuvssut** [comment]
> If he is unable to do it within a couple of days, then @AshuKV can go forward

Please assign me this one. I am 100% that I can make it
