### ISSUE TITLE
Remove meaningless content @Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#778]
## Sample Snapshot:

![Open_Source_Sectopm](https://user-images.githubusercontent.com/46641503/112714349-f4cfdd00-8eff-11eb-85da-78de53908295.png)

**Comment by ashuvssut** [comment]
i want to work on this. 

I have to remove that part only.. right?

**Comment by AbhipsaGuru1012** [comment]
@smaranjitghose can I work on this issue?

**Comment by priyamourya** [comment]
can I work on this issue?

**Comment by Mayank4git** [comment]
i want to work on this issue. Please assign me this issue.

**Comment by padmajabhol** [comment]
I want to work on this issue.

**Comment by smaranjitghose** [comment]
@padmajabhol @AbhipsaGuru1012 @Mayank4git @priyamourya Check out the other issues
