### ISSUE TITLE
Remove toTop button from Mobile View (or similar smaller screens)@Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#779]
## Sample Snapshot

![to_top](https://user-images.githubusercontent.com/46641503/112714389-2e084d00-8f00-11eb-949d-764e984cd7fc.png)

**Comment by ashuvssut** [comment]
i want to work on this'

**Comment by smaranjitghose** [comment]
> i want to work on this'

Assigned for 2 days
