### ISSUE TITLE
Add Feature to Choose Location and Name of the Download File @Editor

### ISSUE THREAD

**Issue by nishant23122000** [smaranjitghose/doc2pen#780]
currently, after editing the file, the file is generated in PNG or PDF format. but the file name is always **generated.pdf** or **generated.png**.
So, I think we should provide an input field to change the file name to the user when the user click on download button,

**Comment by anushbhatia** [comment]
Assigned for 2 days

**Comment by nishant23122000** [comment]
ok, sorry for this and can I use another npm package like materialUI?
