### ISSUE TITLE
Max-Width Bug in the Editor

### ISSUE THREAD

**Issue by Priyanshu-U** [smaranjitghose/doc2pen#798]
There is a bug in the Editor section that allows the user to increase the width of the writing section to more than what is allotted to the editing part.
The picture of the bug is attached below.
![image](https://user-images.githubusercontent.com/62770722/112761703-20df8100-901a-11eb-96b0-c213df2f2653.png)
I can solve the issue if you could assign it to me!

**Comment by Abhishek765** [comment]
@smaranjitghose  Is this bug fixed Can I work on it I found what's wrong with this. Please let me know.
