### ISSUE TITLE
Moving JS code from index.html to separate .js file in assets

### ISSUE THREAD

**Issue by sameersrivastava13** [smaranjitghose/doc2pen#80]
# Description of the change

Separate files makes maintenance easier. The separate code makes it easier for web browsers to cache.

# Screenshots

![Screenshot (43)](https://user-images.githubusercontent.com/56088741/90338983-4976b580-e00b-11ea-9ce3-29acd37ee006.png)

**Comment by sameersrivastava13** [comment]
please assign this to me so that i can make the changes.

**Comment by Aniruddhmuley2001** [comment]
Is this issue required to be worked over now, or is it resolved?

**Comment by smaranjitghose** [comment]
> Is this issue required to be worked over now, or is it resolved?

@sameersrivastava13 is doing it now

**Comment by Aniruddhmuley2001** [comment]
Ok

**Comment by sameersrivastava13** [comment]
Already completed.
