### ISSUE TITLE
Improve NavBar Responsiveness for Small Screens (+ UI Enhancment)

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#801]
[Reference](https://www.youtube.com/watch?v=T2MhVxJxsL0)

**Comment by tanishq-arya** [comment]
Please assign me this issue under gssoc

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by Rishikakanojia** [comment]
Can I work on this issue please ?

**Comment by AbhipsaGuru1012** [comment]
@smaranjitghose can I work on this issue under GSSoC?

**Comment by tanishq-arya** [comment]
@smaranjitghose I have made a new navbar component. This renders the header component unused so I will just remove the import if it's okay. I will make a pull request by today.

**Comment by smaranjitghose** [comment]
> @smaranjitghose can I work on this issue under GSSoC?

Assigned for 3 days

**Comment by smaranjitghose** [comment]
> Can I work on this issue please ?

If you wish, you can give a follow up PR for the one @AbhipsaGuru1012 would be working on and add a svg animation

**Comment by tanishq-arya** [comment]
@smaranjitghose is this still open? I can make changes in the color scheme of my PR if you want me to ?

**Comment by AbhipsaGuru1012** [comment]
@smaranjitghose I have made a PR. Please review.
