### ISSUE TITLE
Scrollbar Missing @Editor Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#802]
## Snapshot(s):
![scroll_bar_missing](https://user-images.githubusercontent.com/46641503/112787692-b6a8f980-9076-11eb-9e67-0d36408d7bbf.png)

## Requirement(s):

- Add the custom scrollbar (present on the other pages) to Editor Page

**Comment by adithyanarayana** [comment]
I am gssoc'21 participant and I would like to work on this

**Comment by smaranjitghose** [comment]
> I am gssoc'21 participant and I would like to work on this

Assigned for 2 days
