### ISSUE TITLE
Need Finer Control over Line Spacing in the Editor

### ISSUE THREAD

**Issue by N-Shar-ma** [smaranjitghose/doc2pen#803]
## Current Situation:

In the Editor, line-spacing can only be set from 1 to 5 in steps of 1.

## Problem:

- Only 5 permitted values with large gaps between them are not enough to satisfy most users
- For most font sizes and styles, **none of the 5 line spacing values allowed sync well with the ruled sheets**

## Proposed Solution:

Allow line-spacing to be set for the same range, but in smaller steps (0.1 instead of 1), to give finer control to the user, and to make it possible to match line-spacing with the ruled sheets.

## Before Screenshot:

- Improper Alignment with ruled sheet at line-spacing set to 4
![image](https://user-images.githubusercontent.com/68962290/112815684-68273b00-9035-11eb-9859-d083c9b6fd2b.png)

## Proposed After Screenshot:

- Proper Alignment with ruled sheet at line spacing set to 3.7
![image](https://user-images.githubusercontent.com/68962290/112816322-2054e380-9036-11eb-9d49-920a13399cf6.png)

**Comment by smaranjitghose** [comment]
Assigned for 2 days
