### ISSUE TITLE
No Full stop at the end of the sentences 

### ISSUE THREAD

**Issue by RubenFalcao14** [smaranjitghose/doc2pen#804]
There are no Full stop at the end of various sentences.
I would like to fix the issue by adding the full stops.

I'm a GSSOC'21 participant and I would love to fix it.

**Comment by smaranjitghose** [comment]
> There are no Full stop at the end of various sentences.
> I would like to fix the issue by adding the full stops.
> 
> I'm a GSSOC'21 participant and I would love to fix it.

Assigned for 1 day

**Comment by RubenFalcao14** [comment]
Hii, I have created a PR #812 , please check it and let me know if it's fine.
