### ISSUE TITLE
Discussion Issue

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#809]
How many of you would be interested in working on issues related to TFJS?

**Comment by Nishayadav-bit** [comment]
Hey @smaranjitghose ,I'm a GSSOC'21 participant .
I would like to work on this issue please assign to me .

**Comment by smaranjitghose** [comment]
This is just for discussion. @Nishayadav-bit would you be able to pick up the basics of TFJS or ML5 if assign issues related to it?

**Comment by ishitakapoor26** [comment]
@smaranjitghose Can you assign this issue to me? I can try.

**Comment by smaranjitghose** [comment]
@ishitakapoor26 check out the new issues I raised recently
