### ISSUE TITLE
Remove Header Transition Effect

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#810]
## Relevant Snapshot:
![meta_tag_conv](https://user-images.githubusercontent.com/46641503/112906877-932f8e80-910a-11eb-8618-ea14e3e197cd.png)

**Comment by raman-thakur** [comment]
I want to work on this issue as a participant in gssoc21, may I??

**Comment by priyamourya** [comment]
I went through the code and I can help in removing the transition effect from header so can you assign this task to me?

**Comment by smaranjitghose** [comment]
> I went through the code and I can help in removing the transition effect from header so can you assign this task to me?

Assigned for 2 days

**Comment by raman-thakur** [comment]
> > I went through the code and I can help in removing the transition effect from header so can you assign this task to me?
> 
> Assigned for 2 days

sir I commented first but you didn't assigned this to me ??

**Comment by priyamourya** [comment]
@smaranjitghose do you want me to remove the text come back also?
![modification](https://user-images.githubusercontent.com/65748264/113096587-12a88500-9213-11eb-91fe-1ff934e92faf.png)

**Comment by smaranjitghose** [comment]
> > > I went through the code and I can help in removing the transition effect from header so can you assign this task to me?
> > 
> > 
> > Assigned for 2 days
> 
> sir I commented first but you didn't assigned this to me ??

Actually, when I saw both of your comments  I randomly choose one of you for it. No specific reason for choice as such. There are lots of other issues. Feel free to claim others.

**Comment by smaranjitghose** [comment]
> @smaranjitghose do you want me to remove the text come back also?
> ![modification](https://user-images.githubusercontent.com/65748264/113096587-12a88500-9213-11eb-91fe-1ff934e92faf.png)
> 
> which appears ,when the viewer move to another page

Yes

**Comment by priyamourya** [comment]
#822
