### ISSUE TITLE
Add Feature to Put Default Filename into Inputbox @Editor

### ISSUE THREAD

**Issue by nishant23122000** [smaranjitghose/doc2pen#811]
## Actual behavior
For now, if we download the file without importing any file, then the file will download which contain the placeholder text in the body part of the file,
and second thing is ,The input box which is for the custom filename is empty 

## Expected behavior
I think we should not give permission to the user to download the file before importing any file, So we can show an alert message to the user.
if the user import file and then press a download button, then inside the download file dialog we should provide the default filename in the input box, So if the user don't want to change the filename then it will directly click the download button,
Check out the below video which I implement in code 

https://user-images.githubusercontent.com/53515714/112942083-3a351a00-914d-11eb-9e00-20665c03aabc.mp4

**Comment by smaranjitghose** [comment]
Actually, in most cases, the user would just copy-paste content from the internet and the need to import a txt file won't arise

**Comment by nishant23122000** [comment]
Oh, that's true , i forgot it😅 i think like only we can import file. 
Ok ok but if user import file then we can add default file name in input field . What about this?
