### ISSUE TITLE
[FEATURE] Load Previous State from our very own 'save file' (.d2psketch)

### ISSUE THREAD

**Issue by ashuvssut** [smaranjitghose/doc2pen#818]
I have seen that excalidraw.com offers users to save their progress in a .excalidraw file. It could be opened whenever the user wishes to continue his/her work by loading that saved .excalidraw file

Simlarly I will save state in .d2psketch file instead
And, I will add feature to load  Previous State form the .d2psketch file

**Comment by smaranjitghose** [comment]
> I have seen that excalidraw.com offers users to save their progress in a .excalidraw file. It could be opened whenever the user wishes to continue his/her work by loading that saved .excalidraw file
> 
> Simlarly I will save state in .d2psketch file instead
> And, I will add feature to load Previous State form the .d2psketch file

Make it d2ps🤣. Short and cute

**Comment by ashuvssut** [comment]
OK d2ps it is!😁
