### ISSUE TITLE
Update marking scheme for GSSOC in CONTRIBUTING file.

### ISSUE THREAD

**Issue by noviicee** [smaranjitghose/doc2pen#821]
The marking scheme for GSSOC'21 has been changed and should be updated in the CONTRIBUTING file also.
:)

**Comment by ashuvssut** [comment]
@noviicee give ur PR ;) dont wait to get assigned.

**Comment by noviicee** [comment]
@ashuvssut  Okay!
Btw any level tags associated with it..??

**Comment by ashuvssut** [comment]
minor doc changes get counted for : `level0` labels

**Comment by noviicee** [comment]
Okay thanks!!
Doing it right now!

**Comment by noviicee** [comment]
@ashuvssut 
Done [here](https://github.com/smaranjitghose/doc2pen/pull/824)
