### ISSUE TITLE
Improve UI @Editor

### ISSUE THREAD

**Issue by nishant23122000** [smaranjitghose/doc2pen#830]
Hey, I think we should improve our editor section UI. where we have to make 2 parts of settings.js like change color or change font will be move on left size and font,letter-spacing, etc will move on the right side.
Check this UI I created

## before
![image](https://user-images.githubusercontent.com/53515714/113303754-06115300-931f-11eb-9227-ed0f554e5321.png)

Also, the Setting section is on the top side so the user need to bit scroll down to show output content, So if we move settings on left and right side then it will be better UI as well as better UX

## After
![image](https://user-images.githubusercontent.com/53515714/113303456-bc286d00-931e-11eb-8807-e69889a4a9d5.png)

Also, I change the font to openSans in navbar, I think this look very professional and net and clean

**Comment by smaranjitghose** [comment]
Check #766

**Comment by nishant23122000** [comment]
@smaranjitghose  So we have to make it like this? because issue #766 is pointing on sketch page design

**Comment by anushbhatia** [comment]
we want to keep the theme of the editor the same. the only thing you can add is that if you can make it sticky. so that all features are available as we scroll
