### ISSUE TITLE
Links in the readme(under the hood) to open in a new tab.

### ISSUE THREAD

**Issue by akshay1027** [smaranjitghose/doc2pen#843]
Links in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

**Comment by smaranjitghose** [comment]
Are you planning to replace the markdown code with html and have a target = blank attribute for a tag?

**Comment by akshay1027** [comment]
Yes but even then it's not working!  I found out now that we can't do this on Github! here is the link to that: mojombo/github-flavored-markdown#28
so I will close this.
