### ISSUE TITLE
Animation in support us!!

### ISSUE THREAD

**Issue by 4kashyadav** [smaranjitghose/doc2pen#846]
website has animation in the first icon bit not in second so can you allow me to add animation in the second one also!
![Screenshot (505)](https://user-images.githubusercontent.com/78416508/113599988-01b9a280-965d-11eb-9a93-655e5320c581.png)
![Screenshot (506)](https://user-images.githubusercontent.com/78416508/113600002-05e5c000-965d-11eb-88a6-67269999a209.png)

**Comment by 4kashyadav** [comment]
@smaranjitghose please assign this to me!

**Comment by smaranjitghose** [comment]
Assigned for 3 days.

- Increase the space between the logos so that there is no overlap.

**Comment by 4kashyadav** [comment]
@smaranjitghose my pull request is accepted but not showing in this
