### ISSUE TITLE
Add tech stack in the readme file .

### ISSUE THREAD

**Issue by srisatya1197** [smaranjitghose/doc2pen#847]
As the readme file looks spiffing the only thing I want to do is adding tech stack with logos in readme file so it looks more understandable for contributors . I'm a GSSOC'21 participant I want to work on this issue please assign this to me .

**Comment by smaranjitghose** [comment]
Assigned for 1 day

**Comment by srisatya1197** [comment]
Sir I'm having exams . Can I please make it tomorrow Sir .

**Comment by srisatya1197** [comment]
due to exmas I was unable to do Sir today evening I 'll do it for sure

**Comment by srisatya1197** [comment]
@smaranjitghose Sir Could you please give level lable ?

**Comment by smaranjitghose** [comment]
Done
