### ISSUE TITLE
Remove PageScrollBar @ Editor Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#849]
![doc2pen](https://user-images.githubusercontent.com/46641503/113797832-a7f5cd00-976f-11eb-9ad6-92991455e368.png)

**Comment by ashuvssut** [comment]
I want to work on this

**Comment by adithyanarayana** [comment]
Hey! Is there any problem? I made changes accordingly in #806 
Do you want to revert this ?
