### ISSUE TITLE
Adding highlighting feature on download file button in Editor section.

### ISSUE THREAD

**Issue by Priyanshujha11** [smaranjitghose/doc2pen#853]
I want to add highlighting feature on download file button in Editor section as we hover over it which is present in other buttons like change sheet and change style.
![Screenshot (17)](https://user-images.githubusercontent.com/78751081/113910071-0bc2d900-97f6-11eb-8ade-1efbf670e3a5.png)
![Screenshot (18)](https://user-images.githubusercontent.com/78751081/113910086-11202380-97f6-11eb-949d-5b6c3942e747.png)

**Comment by iaryangoyal** [comment]
kindly Assign me this work sir

**Comment by smaranjitghose** [comment]
Assigned to @Priyanshujha11 for 2 days
