### ISSUE TITLE
Add github link of project maintainers!

### ISSUE THREAD

**Issue by 4kashyadav** [smaranjitghose/doc2pen#858]
I will add a GitHub link of the project maintainers, so by clicking on their photos we will be redirected to their accounts.
![Screenshot (514)](https://user-images.githubusercontent.com/78416508/114163544-ee9e1f80-9947-11eb-9d99-47bfbe67c008.png)

**Comment by iaryangoyal** [comment]
Kindly Assign me this work?

**Comment by smaranjitghose** [comment]
@anushbhatia could you please suggest the last configuration where we had this sorted along with linkedin?

**Comment by 4kashyadav** [comment]
@smaranjitghose bro please provide me the links I have almost completed this work! and bro please assign this work to me!

**Comment by Nishayadav-bit** [comment]
Hi @smaranjitghose , I'm a GSSOC'21 participant . I would like to work on this issue please assign to me.

**Comment by smaranjitghose** [comment]
> Hi @smaranjitghose , I'm a GSSOC'21 participant . I would like to work on this issue please assign to me.

Have a look at #674

**Comment by anushbhatia** [comment]
> @anushbhatia could you please suggest the last configuration where we had this sorted along with linkedin?

Last configuration had logos of both LinkedIn and github on hovering over these cards

**Comment by smaranjitghose** [comment]
> > @anushbhatia could you please suggest the last configuration where we had this sorted along with linkedin?
> 
> Last configuration had logos of both LinkedIn and github on hovering over these cards

@4kashyadav Please work with @anushbhatia for this

**Comment by 4kashyadav** [comment]
alright!
