### ISSUE TITLE
Add hovering effect in buttons present in sketch section!

### ISSUE THREAD

**Issue by 4kashyadav** [smaranjitghose/doc2pen#860]
I think if I will add a hovering effect in these buttons like they will change their colour when we hover over them then it will be more attractive can please assign this to me!
![Screenshot (522)](https://user-images.githubusercontent.com/78416508/114307029-7710f180-9afb-11eb-8a41-7232f6468b40.png)

**Comment by tend2infinity** [comment]
I would like to work on this issue under GSSOC
