### ISSUE TITLE
Add Feature to move and modify elements on Sketch Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#866]
## Sample Snapshot

![Zie](https://user-images.githubusercontent.com/46641503/112713944-e7b1ee80-8efd-11eb-973c-7d280a56e939.png)

## Description

- The title explains the issue well!

**Comment by tend2infinity** [comment]
I didn't understand what this issue is about, can you explain me a little bit because I want to work on this issue, but I'm not getting what exactly you want me to do

**Comment by smaranjitghose** [comment]
Basically once a figure/shape has been drawn on the canvas, we should be able to change it's dimensions as well it's position

**Comment by anshika208** [comment]
hey @smaranjitghose i would like to work on the issue . can i get assigned?
