### ISSUE TITLE
Improve Pre-Loader UI

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#867]
## Certain specifications
- **DO NOT COPY PASTE DIRECTLY FROM THE REFERENCE**
- Use the name of our project
- Use our logo (Favicon)
- DO NOT mess up the transition time ( keep it a sweet spot between too slow and too fast)
- Try to animate the pen in our logo
- Change the color of the background of the current animation to white, logo (with the animation) to sea green, text to black.
[Reference for color scheme](https://dribbble.com/shots/12425249-Wave) 
- DO NOT mess up any other part of the web app you are not dealing with

**Comment by sardonicankita** [comment]
Hey 
can u assign this issue to me? I am GSSOC participant.

**Comment by smaranjitghose** [comment]
> Hey
> can u assign this issue to me? I am GSSOC participant.

Assigned for 2 days
