### ISSUE TITLE
Make new Project Maintainer UI

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#868]
## Requirements

- Try to have a swish effect like the cards in [this](https://www.hellomonday.com/about)
- Below the pictures, put the respective names 
- Below the names put the Github and Linkedin icons
-  Use [microanimations](https://useanimations.com/) for the social media icons
- Try your level best to have the images change on click (as in the reference above). 
- The images (max of 3 for each card), text, link to social media should be loaded dynamically from the team.js as the current codebase does
- DO NOT mess up any other part of the web app you are not dealing with

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

**Comment by ashuvssut** [comment]
i want to work on this

**Comment by smaranjitghose** [comment]
> i want to work on this

Assigned for 3 days

**Comment by ashuvssut** [comment]
I have tried to create the swish effect. this is the best I came up with.

![render](https://user-images.githubusercontent.com/60546840/114834940-eac62f00-9d85-11eb-8bd3-f1ceb9193ed5.gif)
**_Loading GIF 6.8mb..._**

**Comment by ashuvssut** [comment]
its a canvas liquid background.

I didnt find any npm package or youtube video for that cool swish effect of happymoday website's cards

So this is what i came up with. Should I implement this for our maintainer section cards UI?

**Comment by smaranjitghose** [comment]
> @smaranjitghose its a blue canvas background with onhover liquid effect (wont work in mobile view coz hover does not exist for mobile).
> 
> I didnt find any npm package or youtube video for that cool swish effect of happymoday website's cards
> 
> So this is what i came up with. Should I implement this for our maintainer section cards UI?

Sure. LGTM

**Comment by ashuvssut** [comment]
previously the liquid effect showed up even when the mouse **moved out from the `div` element**. This was not in happymonday's swish effect

so I changed the code. now the liquid effect does not show up when the mouse **moves out from the `div` element**. the liquid effect shows up when the mouse enters the `div`

I hope now its more desirable😄

![render1](https://user-images.githubusercontent.com/60546840/114904530-d0fc0a80-9dcc-11eb-872c-ed2525eb1856.gif)
**_Loading GIF 4mb..._**
