### ISSUE TITLE
Sidebar Update in Sketch Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#869]
## Description:

The current sketch page toolbar is weirdly placed over the canvas. We intend to revamp it with a sidebar as shown in the example below

[Sample Tutorial](https://www.youtube.com/watch?v=mN3P_rv8ad4)

## Snapshot

- Current State

![Sketch_UI](https://user-images.githubusercontent.com/46641503/112712726-1b3d4a80-8ef7-11eb-8feb-9e7281d464a0.png)

- Sample Output

![](https://lvivity.com/wp-content/uploads/2018/08/canva.jpg)

**Comment by A-HK** [comment]
Hey @smaranjitghose, can I try working on this?

**Comment by smaranjitghose** [comment]
Assigned for 2 days

**Comment by ashuvssut** [comment]
if by any chance the assigned contributor @A-HK  thinks that he/she is unable to submit the PR.. then I would like to work on this😄

**Comment by A-HK** [comment]
Hey @ashuvssut , am definitely working on this !
Will submit PR by tomorrow night at the latest, as per the 2-day window assigned.

**Comment by ashuvssut** [comment]
@A-HK , you see that current ToolBox is a separate react component. Try to create the new SideBar as a separate react component.

**Comment by A-HK** [comment]
Hey @smaranjitghose @anushbhatia, sorry for the silly question, but would you like the entire toolbar to appear after clicking on the sidebar, or different components to appear separately?

If it's the latter, I'll have to make significant changes to the already created Toolbox.js file.
Is that okay?

**Comment by A-HK** [comment]
Hey @ashuvssut, you can go ahead with this issue if you're still interested. Unassigning myself, as I won't be able to complete it within the stipulated time.
So sorry for the inconvenience.

**Comment by ashuvssut** [comment]
ya sure

**Comment by ashuvssut** [comment]
@smaranjitghore please assign this to me please

**Comment by ashuvssut** [comment]
there will be 5 tabs (tabs will have icons only) on the side bar
```
--|
  |
  |-project tab----|
  |                |-save as (save progress)
  |                |-download sketch
  |                |-load project
  |                |-delete progress
  |
  |-canvas-setup---|
  |                |-canvas background
  |                |-more options that can be added in future when limitless canvas feature is implemented (canvasWidth canvasHeight options..)
  |
  |-shapes n tools-|
  |                |-will show all shapes n pen tool (all drawables) (NB-this excldues text tool)
  |                |-will show options/modifiers for that selected shape only
  |
  |
  |-text tool------|
  |                |-all option related to text tool
  |
  |-ICONS LIBRARY--|
  |
  |

````
> NB:- i dont know where should i keep the undo redo buttons. so i have not added it. for tablet we might need those buttons...can i keep it separately (not in sidebar) and keep it in top right position in canvas?

**Comment by smaranjitghose** [comment]
> # Proposal
> there will be 5 tabs (tabs will have icons only) on the side bar
> 
> ```
> --|
>   |
>   |-project tab----|
>   |                |-save as (save progress)
>   |                |-download sketch
>   |                |-load project
>   |                |-delete progress
>   |
>   |-canvas-setup---|
>   |                |-canvas background
>   |                |-more options that can be added in future when limitless canvas feature is implemented (canvasWidth canvasHeight options..)
>   |
>   |-shapes n tools-|
>   |                |-will show all shapes n pen tool (all drawables) (NB-this excldues text tool)
>   |                |-will show options/modifiers for that selected shape only
>   |
>   |
>   |-text tool------|
>   |                |-all option related to text tool
>   |                |-( we can have more text options in future. See canva websites's text tab)
>   |
>   |-ICONS LIBRARY--|
>   |
>   |
> ```
> 
> > NB:- i dont know where should i keep the undo redo buttons. so i have not added it. for tablet we might need those buttons...can i keep it separately (not in sidebar) and keep it in top right position in canvas?
> 
> **Please tell if you have any suggestion regarding the tabs arrangement**

Sure
