### ISSUE TITLE
Adding Footer to Sketch Page🎉

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#872]
### Requirements
1. Add the same footer to all pages similar to present in the footer and editor.
2. But after the scroll bar issues is resolved proceed with this #871 

#### Currenlty
![image](https://user-images.githubusercontent.com/40017559/114615261-17654280-9cc3-11eb-9761-cc35379b5647.png)
 
##### Required
![image](https://user-images.githubusercontent.com/40017559/114615315-277d2200-9cc3-11eb-87ae-e3471616970e.png)

**Comment by subhasmitapradhan** [comment]
I would love to work on this too.

**Comment by anushbhatia** [comment]
Sure after #871 work on this.

**Comment by anniesaxena** [comment]
Can I work on this issue?

**Comment by AbhipsaGuru1012** [comment]
@smaranjitghose @anushbhatia can I work on this issue under GSSoC'21?

**Comment by subhasmitapradhan** [comment]
May I know why this issue was closed? I haven't  made the PR for it yet though.

**Comment by smaranjitghose** [comment]
Your deadline is over
