### ISSUE TITLE
Bug: Media Manip

### ISSUE THREAD

**Issue by SandeepKrSuman** [smaranjitghose/doc2pen#874]
### Bug detail : 
- Input and Output dropdown holds the value of previous file even after removing the file.

---
### Gif explaining the bug :
![doc2pen_issue](https://user-images.githubusercontent.com/54541515/114746257-27d1f780-9d6d-11eb-99e9-76dc3d7d589e.gif)

---

### The fix :
- The input and output dropdown should be changed to default after removing the file from the drag and drop box.

**Comment by anushbhatia** [comment]
Sure Resolve the error in 3 days

**Comment by SandeepKrSuman** [comment]
I'm working on it. @anushbhatia , can you please add the level tag.
