### ISSUE TITLE
Making the Settings Section in Editor Uniform.

### ISSUE THREAD

**Issue by Rishab-j** [smaranjitghose/doc2pen#879]
![Screenshot (793)](https://user-images.githubusercontent.com/59995879/114921156-dd717900-9e47-11eb-8419-49993c63caa4.png)

Right now the text setting options are distributed in 2 rows (X-axis, Font Size, and Y-axis are in the first row and the rest are in the second row).
I would like to make them uniform i.e put them all together in the second row and rearranging them.
I would also like to add few more styles so that it looks good.

**Comment by sardonicankita** [comment]
Can u guys please assign this to me?

**Comment by smaranjitghose** [comment]
@Rishab-j Do give a PR for this. Would love to see how it turns out

**Comment by Rishab-j** [comment]
@smaranjitghose Yep alright
