### ISSUE TITLE
scroll-To-Top of editor page

### ISSUE THREAD

**Issue by MennaMagdy2019** [smaranjitghose/doc2pen#880]
Can I make a scroll to the top for the editor page?
like this 
![Capture20](https://user-images.githubusercontent.com/50016070/114964205-8a5eec80-9e6e-11eb-946a-71d8f06ab66a.JPG)

I think it will look nice. Can you assign me this issue, please? @anushbhatia

**Comment by ashuvssut** [comment]
you need not to create a new one. just import the scroll-to-top component in editor page

**Comment by MennaMagdy2019** [comment]
ok, can I do this @ashuvssut ?

**Comment by ashuvssut** [comment]
actually I am a contributor. 

project maintainers will assign you this issue if they need this feature

**Comment by smaranjitghose** [comment]
@MennaMagdy2019 Assigned for 2 days
