### ISSUE TITLE
Bug: Card Details Is not rendered properly for Maintainers

### ISSUE THREAD

**Issue by Abhishek765** [smaranjitghose/doc2pen#885]
Found One Bug Like when we Hover over the Maintainers Card The details is not visible. See the ScreenShot for more Info.

**_Intially Image is like:_**
![image](https://user-images.githubusercontent.com/43133456/115007164-55cb4f00-9ec7-11eb-8c44-7faa8e9e0c19.png)

**_On Hover over it:_** 

![image](https://user-images.githubusercontent.com/43133456/115007382-8c08ce80-9ec7-11eb-8142-39f5c41af29d.png)

**_Expected One:_** 

![image](https://user-images.githubusercontent.com/43133456/115007547-b65a8c00-9ec7-11eb-8880-e84e4baac51d.png)

**Please assign me and let me Fix this**

**Comment by Abhishek765** [comment]
@smaranjitghose Please have a look at it so that I can create the PR.

**Comment by smaranjitghose** [comment]
This is already a part of another issue involving the revamp of the card UI

**Comment by Abhishek765** [comment]
> This is already a part of another issue involving the revamp of the card UI

Yes just saw that but there he didn't fix the issue, that I am mentioning here so I guess this issue should be valid one🤔
