### ISSUE TITLE
Vertical navbar links

### ISSUE THREAD

**Issue by MennaMagdy2019** [smaranjitghose/doc2pen#886]
Can I make the navbar links verticals instead of horizontal?

![Navbar](https://user-images.githubusercontent.com/50016070/115036401-c5dcd380-9ecd-11eb-9d5e-37225934fed3.JPG)
 
I think it will look nice If I made it vertical. Can you assign me this issue, please? @anushbhatia

**Comment by smaranjitghose** [comment]
Assigned for 2 days
