### ISSUE TITLE
Tooltips on Rate your experience

### ISSUE THREAD

**Issue by sparshsharma2510** [smaranjitghose/doc2pen#890]
I want to add a tooltips feature using the react-bootstrap package on the rate your experience emojis, such that when the user hovers over them, he/she sees a short message box of what that emoji means.
Here is what I mean :

![tooltip](https://user-images.githubusercontent.com/53931981/115125220-3d9d2200-9fe4-11eb-8ebd-107cc48d5e93.JPG)

Kindly assign this issue to me under gssoc21.

**Comment by smaranjitghose** [comment]
Assigned for 2 days
