### ISSUE TITLE
path collision 

### ISSUE THREAD

**Issue by bijankundu** [smaranjitghose/doc2pen#893]
git clone is throwing path collision warning on windows 10

![image](https://user-images.githubusercontent.com/50210712/115135236-85e43080-a034-11eb-9458-ef626fd4c6f4.png)

**Comment by ashuvssut** [comment]
we can fix this in the following way. You can rename the file in a case-sensitive way and commit the change:

`git mv --cached name.txt NAME.TXT`

Please take care what you are renaming by checking the number of lines in both files or by manually checking.
if number of lines differ or you find differences in code then you have to check which files has the most recent updated code and keep that only. its most probably to kebab-cased scss files and PascalCase jsx files that have the most-recent code

**Comment by ashuvssut** [comment]
ref https://www.hanselman.com/blog/git-is-casesensitive-and-your-filesystem-may-not-be-weird-folder-merging-on-windows
