### ISSUE TITLE
Adding a go to top button in home page.

### ISSUE THREAD

**Issue by kanishka8276** [smaranjitghose/doc2pen#907]
I will like to add a go to top button in home page.
Please assign this to me.

**Comment by ashuvssut** [comment]
we already have one. its a component. scroll-to-top.

its used in both pages (home and editor).

**Comment by kanishka8276** [comment]
@ashuvssut Ok! Actually I ran it on my phone through the website mentioned. And couldn't see that.

**Comment by ashuvssut** [comment]
actually

we removed that for mobile view
