### ISSUE TITLE
Banner & readme enhancements 

### ISSUE THREAD

**Issue by aditisneh** [smaranjitghose/doc2pen#908]
I would like to add a banner in the readme for doc2pen.
This will include a personalised gif / poster.

**Comment by smaranjitghose** [comment]
Sure! Assigned for 2 days

**Comment by aditisneh** [comment]
@smaranjitghose I have made a PR, do check and let me know, also don't forget to add the level tag to this issue

**Comment by aditisneh** [comment]
Hey, do add the level tag for this issue, I am not able to fetch points otherwise. @smaranjitghose
