### ISSUE TITLE
Styling on scroll to navbar, and on focusing page in editor

### ISSUE THREAD

**Issue by hsnice16** [smaranjitghose/doc2pen#912]
On scrolling, it will look good if we show the bottom shadow to the navbar. (For its demo, Can I add my work? I did for a personal project)

And right now, when we click on the page to start writing, its border becomes black. Which I think, doesn't right as there is already a border outside it. (I think this is happening because of focus state)

So, Are these problems are good for work?

**Comment by hsnice16** [comment]
Can I work on it?

**Comment by Furquan712** [comment]
I would like to work on this, will you assign me?

**Comment by Furquan712** [comment]
any update??
