### ISSUE TITLE
Add floating animation in images of steps section .

### ISSUE THREAD

**Issue by Shivangi-ch** [smaranjitghose/doc2pen#914]
I want to add floating animation in images that will make  page look more attractive.
![Screenshot from 2021-04-27 09-04-14](https://user-images.githubusercontent.com/57783826/116181079-9af94780-a737-11eb-8ff7-e18f8b74b60c.png)
Originally it looks like this.Floating images will look more nice.
Please assign this to me.

**Comment by smaranjitghose** [comment]
Assigned for 2 days
