### ISSUE TITLE
Sketch Page - Custom Pencil cursor instead of crosshair

### ISSUE THREAD

**Issue by N-Shar-ma** [smaranjitghose/doc2pen#915]
## Issue
Currently, the cursor for the canvas on the Sketch Page is a crosshair, which is not really related to drawing. A custom css cursor like a pencil, might look more appropriate.

## Link to Cursor demo
https://custom-cursor.com/en/collection/life-style/pencil

If you like this idea, I would love to add a custom pencil cursor exactly like the demo one

**Comment by smaranjitghose** [comment]
Assigned for 2 days
