### ISSUE TITLE
There should be an option to change font colors differently

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/doc2pen#921]
I want to create an assignment where I want the questions in black color and the answers in blue color, but when I tried to change the answer color it changed the color of the whole document.
![image](https://user-images.githubusercontent.com/49204837/116770546-6997b900-aa62-11eb-98df-0740c1f5f14d.png)

**Comment by Furquan712** [comment]
I would like to work on this, will you assign me?
