### ISSUE TITLE
Feedback Form

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#93]
# Description:
we have to add feedback form so that our users give us valuable feedback and suggestions for new features
# Screenshots:

**Comment by nooras** [comment]
Hey Can i do this ? Will you assign me ? @himanshujaidka

**Comment by smaranjitghose** [comment]
I just realized we have a small design glitch, the current ```Contact``` form should be ```About Us``` and the feedback form should be ```Contact Page```

@nooras and @himanshujaidka collaborate on this and try to finish it in 2 or 4 PRs (divide the work equally and discuss over slack)

So for the ```Contact Page``` we need,

- A feedback/contact form with the following details:
     - Name
     - Phone Number
     - Email
     - Message
     - Captcha
- A map (use openbox API or google maps API, simply putting the location to India)

**Comment by himanshujaidka** [comment]
yes @smaranjitghose and I also think that we have to add some more contributors pics in about us section?😜

**Comment by nooras** [comment]
Okay @smaranjitghose

**Comment by himanshujaidka** [comment]
@nooras give me your slack id
or mess me at himanshu jaidka

**Comment by himanshujaidka** [comment]
@smaranjitghose we have to do backend for this
will we use node.js?

**Comment by himanshujaidka** [comment]
and Mailchimp for API?

**Comment by smaranjitghose** [comment]
> yes @smaranjitghose and I also think that we have to add some more contributors pics in about us section?😜

Ofcourse man, everyone's first PR merged is meant to be credited there..( But no points to again include your name and pic🤣..just with your second or third PR, add yourself to our sweet little hall of fame😇)

**Comment by himanshujaidka** [comment]
No, no 😅 but it's my 2 PR which is merged and I want to be a permanent member of it @smaranjitghose

**Comment by himanshujaidka** [comment]
> @smaranjitghose we have to do backend for this
> will we use node.js?

@smaranjitghose and please tell us

**Comment by anushbhatia** [comment]
as of now we won't be using the backend try using only html css js

**Comment by himanshujaidka** [comment]
ok

**Comment by nooras** [comment]
Hey @smaranjitghose there is already contact is present in Navbar... what we have to update in navbar ?
![Screenshot from 2020-08-20 21-47-05](https://user-images.githubusercontent.com/30138146/90797802-c1581f00-e32e-11ea-8a8b-590380447a4f.png)

**Comment by anushbhatia** [comment]
try using better format for the maps https://demos.creative-tim.com/material-kit/index.html refer this for layout
