### ISSUE TITLE
New Feature: Option for Bold Text on Editor Page

### ISSUE THREAD

**Issue by N-Shar-ma** [smaranjitghose/doc2pen#932]
## Problem

Most of the current fonts available have a very thin and light stroke, and there is no way the user can change that

## Solution

The control panel can have an additional dropdown to select between normal and bold font weight

## Screenshot Examples for Dawning Font

- Normal font weight 
![image](https://user-images.githubusercontent.com/68962290/117067165-85a78e80-acde-11eb-9f91-b66dd83bd6e8.png)

- Bold font weight
![image](https://user-images.githubusercontent.com/68962290/117067127-79bbcc80-acde-11eb-873c-2d80386c2caa.png)

I would like to work on this issue if you approve of this new feature

**Comment by Furquan712** [comment]
I would like to work on this, will you assign me?

**Comment by N-Shar-ma** [comment]
@smaranjitghose @anushbhatia Could I please know if I should work on this? Not a problem if this feature is not something you want for this project, but please let me know either way

**Comment by N-Shar-ma** [comment]
@smaranjitghose any updates? May I work on this?

**Comment by smaranjitghose** [comment]
> @smaranjitghose any updates? May I work on this?

Assigned for 3 days
