### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by Saumya-07** [smaranjitghose/doc2pen#937]
## **Describe the bug**
Make a better responsive webpage.

## **Possible solution**
I would like to make responsive this about-steps section

## **Screenshots**
![Screenshot (570)](https://user-images.githubusercontent.com/68998355/117581280-ab3afa80-b119-11eb-8dbe-e9b9e2711a8b.png)

I am a GSSOC'21 participant and would like to work on this issue.
please assign this issue to me if you find it valid.

**Comment by Saumya-07** [comment]
Should I work on it?

**Comment by smaranjitghose** [comment]
Assigned for 2 days

**Comment by AbhipsaGuru1012** [comment]
@smaranjitghose can I work on this issue?

**Comment by Tanya933** [comment]
@smaranjitghose  i would like to work on this issue.Please assign this issue to me .Thankyou

**Comment by Saumya-07** [comment]
I am working on the issue but facing a problem in setting it up on my local machine.

Please help me @smaranjitghose with this.
Screenshot of the error-
![Screenshot (576)](https://user-images.githubusercontent.com/68998355/118268406-fc146f80-b4da-11eb-9977-e1aafe18d65c.png)

I had successfully cloned the repository.
then npm install.
but then too facing problem while npm start

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by anushbhatia** [comment]
> I am working on the issue but facing a problem in setting it up on my local machine.
> 
> Please help me @smaranjitghose with this.
> Screenshot of the error-
> ![Screenshot (576)](https://user-images.githubusercontent.com/68998355/118268406-fc146f80-b4da-11eb-9977-e1aafe18d65c.png)
> 
> I had successfully cloned the repository.
> then npm install.
> but then too facing problem while npm start

clone it again deleting the previous code.

**Comment by Saumya-07** [comment]
I should not work on the issue now @smaranjitghose @anushbhatia ?

**Comment by Saumya-07** [comment]
Thank you @anushbhatia  that worked the issue resolved
I had set up it on my local machine successfully

Sorry @smaranjitghose by mistake the issue was closed by me.

**Comment by Saumya-07** [comment]
Please review PR #948 
@smaranjitghose @anushbhatia
