### ISSUE TITLE
Clean the code.

### ISSUE THREAD

**Issue by Shivangi-ch** [smaranjitghose/doc2pen#938]
- Due to a lot of contributions, the code is messy right now. For example improper indentation, unesseccary spaces/tabs, lack of comments to explain the code and extra commented code.
- All this makes it difficult for beginner contributors to understand the code.
- So the code should be cleaned

**Comment by Shivangi-ch** [comment]
@smaranjitghose Please assign

**Comment by farseenmanekhan1232** [comment]
please assign

**Comment by smaranjitghose** [comment]
@Shivangi-ch  Assigned for 2 days

**Comment by pranjay-poddar** [comment]
please assign

**Comment by Shivangi-ch** [comment]
I am working on it. Clicked on unassign button by mistake.
Reassign me @smaranjitghose

**Comment by Shivangi-ch** [comment]
@smaranjitghose Made a pull request for this issue.
