### ISSUE TITLE
Button not matching with project theme

### ISSUE THREAD

**Issue by atharva21-stack** [smaranjitghose/doc2pen#942]
![Capture](https://user-images.githubusercontent.com/70438130/118388896-b83d7980-b644-11eb-9e04-e2a9d3368651.PNG)

The button in above image doesn't match the project theme, changing color to solid blue and change in hover effect might look more good.

I would like to work on this issue.

**Comment by smaranjitghose** [comment]
Sure. Assigned for 2 days

**Comment by atharva21-stack** [comment]
Thank you , I'll start working on it

**Comment by atharva21-stack** [comment]
https://user-images.githubusercontent.com/70438130/118528945-946f5600-b760-11eb-8fbc-9551f86aef0d.mp4

**Comment by atharva21-stack** [comment]
I have created this button design , what are your thoughts on this?


https://user-images.githubusercontent.com/70438130/118529626-59215700-b761-11eb-9e72-78a7a8efa648.mp4

**Comment by atharva21-stack** [comment]
I have created this button design , what are your thoughts on this?


https://user-images.githubusercontent.com/70438130/118530055-d3ea7200-b761-11eb-9ac3-5b4945ec9f84.mp4

**Comment by smaranjitghose** [comment]
> I have created this button design , what are your thoughts on this?
> 
>  Doc2pen.-.Google.Chrome.2021-05-17.22-40-42.mp4

Give a PR

**Comment by srishtij2000** [comment]
Can I work on this issue?
