### ISSUE TITLE
Repo README is not properly formatted

### ISSUE THREAD

**Issue by cmulay** [smaranjitghose/doc2pen#943]
![image](https://user-images.githubusercontent.com/38172685/118394768-4ffe9000-b664-11eb-8d6c-1946e914f10a.png)

Problems
- Check boxes are used instead of pointers
- the badges are not following the same design (combination of plastic and for the badge)
- also adding an open-source label would be nice

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by hardikshah197** [comment]
If no one is working, may I take up this issue? @cmulay?

**Comment by cmulay** [comment]
I'm not a maintainer of this project @smaranjitghose and @anushbhatia are, they can assign one of you on this issue.

**Comment by cmulay** [comment]
@AshuKV @hardikshah197 any one of you send PR for this change
