### ISSUE TITLE
Icons are too small

### ISSUE THREAD

**Issue by garvitgupta13** [smaranjitghose/doc2pen#944]
We can increase the size of these icons so the are easily visible
![image](https://user-images.githubusercontent.com/70805691/118397286-e2a52c00-b670-11eb-9562-328dff3e840c.png)

Please assign me this issue under `gssoc21`

**Comment by smaranjitghose** [comment]
Give it a try @garvitgupta13

**Comment by MayankBeck** [comment]
I can do it if in any case @garvitgupta13 is not able to complete it.

**Comment by garvitgupta13** [comment]
Working on it, will be creating a PR by today

**Comment by srishtij2000** [comment]
Can I work on this issue?
