### ISSUE TITLE
frontend: dark mode button to the homepage

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/doc2pen#949]
Yes, I want to work

**Comment by hardikshah197** [comment]
May I work on this issue if no one is working on it?

**Comment by MayankBeck** [comment]
I want to work on this issue.

**Comment by himanshujaidka** [comment]
@smaranjitghose pls approve this issue

**Comment by Simi06** [comment]
Can I work on this issue as a participant of GSSoC'21?

**Comment by smaranjitghose** [comment]
We are not opting for a dark mode exclusively for the Home Page
