### ISSUE TITLE
Dark Mode in the editor looks ugly

### ISSUE THREAD

**Issue by imsahil007** [smaranjitghose/doc2pen#95]
# Description:

Dark mode in the editor is all black with white font. Try to separate text box with rest of the webpage.

# Screenshots:

![image](https://user-images.githubusercontent.com/35963992/90648909-bc746c00-e257-11ea-882a-30cfa11cddee.png)

**Comment by smaranjitghose** [comment]
> # Description:
> Dark mode in the editor is all black with white font. Try to separate text box with rest of the webpage.
> 
> # Screenshots:
> ![image](https://user-images.githubusercontent.com/35963992/90648909-bc746c00-e257-11ea-882a-30cfa11cddee.png)

It does not just look ugly, it sucks 🤣🤣. We need a total revamp!

**Comment by ymaheshwari1** [comment]
I am interested in working on this.

**Comment by anushbhatia** [comment]
distribute pages among yourself

**Comment by ymaheshwari1** [comment]
@smaranjitghose Can I start now, as the PRs is still not merged?

**Comment by anushbhatia** [comment]
Yes go ahead

**Comment by ymaheshwari1** [comment]
@smaranjitghose @anushbhatia Have a look on the below screenshot:

![image](https://user-images.githubusercontent.com/41404838/92319619-00c58180-f038-11ea-85de-db6df0853fea.png)

**Comment by anushbhatia** [comment]
https://uxdesign.cc/dark-mode-ui-design-the-definitive-guide-part-1-color-53dcfaea5129
https://material.io/design/color/the-color-system.html#color-theme-creation
Refer to these for colour codes

**Comment by ymaheshwari1** [comment]
@anushbhatia Which section color should I change?
