### ISSUE TITLE
Add Merge PDF feature to MediaManip Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#965]
[Sample Reference](https://www.ilovepdf.com/merge_pdf)

**Comment by subhangi2731** [comment]
@smaranjitghose please assign this issue to me

**Comment by subhangi2731** [comment]
@smaranjitghose please help when i click this button i cannot select any pdf files to test my pdf merger
![Screenshot from 2021-05-25 22-38-25](https://user-images.githubusercontent.com/53938490/119542105-cad65200-bdac-11eb-9eb6-30ad8e461256.png)

**Comment by smaranjitghose** [comment]
Could you please share the snapshots of your code?

CC: @anushbhatia

**Comment by subhangi2731** [comment]
@smaranjitghose the existing cause which helps select files to convert only image files can be selected but not the pdf files..so please tell me how should I do

**Comment by subhangi2731** [comment]
@smaranjitghose please reply on above

**Comment by smaranjitghose** [comment]
> @smaranjitghose the existing cause which helps select files to convert only image files can be selected but not the pdf files..so please tell me how should I do

Can you please attach a clip/screenshot and explain elaborately. I am unable to understand your query.

**Comment by subhangi2731** [comment]
@smaranjitghose ok I will attach the ss of code I was saying that it is not selecting the files in pdf format

**Comment by N-Shar-ma** [comment]
@smaranjitghose @anushbhatia I'd like to try adding this feature!
