### ISSUE TITLE
New Narrative for the Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#966]
## Background:

Doc2pen started as a pet project to make handwritten assignments for students easier during the pandemic. However, we have come a long way from that phase from having a sketch page to a budding media conversion page. It is high time we change our pitch which forms the main attraction of the home page.

![New Narrative for the  Home Page](https://user-images.githubusercontent.com/46641503/119380247-1837be00-bcde-11eb-935b-8279a64749d9.png)

**Comment by N-Shar-ma** [comment]
Can I please be assigned to work on this? I'll make sure to highlight all the capabilities of this web app in the new pitch

**Comment by smaranjitghose** [comment]
> Can I please be assigned to work on this? I'll make sure to highlight all the capabilities of this web app in the new pitch

Sure. Take up the readme Issue as well then.
