### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#967]
## Task 1:

Update the Demo Section

[Reference](https://github.com/smaranjitghose/awesome-portfolio-websites)

## Task 2:

Improve the Intro line. We need a convincing pitch for the repo description as well!

## Task 3:

Design a banner image for github repo (would be visible when the link is shared on social media platforms)

**Comment by subhangi2731** [comment]
@smaranjitghose please assign me this I want to work

**Comment by smaranjitghose** [comment]
Assigned for Task 1. Complete that and proceed with the other two in separate PRs

**Comment by smaranjitghose** [comment]
Reassinged to @N-Shar-ma

**Comment by N-Shar-ma** [comment]
@smaranjitghose Should I make separate PRs for the 3 tasks or do them all in 1 PR?
