### ISSUE TITLE
Update License Related Info on the Repo to Creative Commons

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#969]
Self-explanatory.

**Comment by Kumud-869231165** [comment]
I want to work on this @smaranjitghose

**Comment by smaranjitghose** [comment]
This is a very simple issue. Assigned for 1 day but try to wrap up asap

**Comment by Kumud-869231165** [comment]
Allow adaptations of your work to be shared?
 Yes	 No	 Yes, as long as others share alike
Allow commercial uses of your work?
 Yes	 No 

Should I click on yes for both the questions

**Comment by Kumud-869231165** [comment]
@smaranjitghose should I click yes on both the questions
