### ISSUE TITLE
Update Steps Section on the Homepage

### ISSUE THREAD

**Issue by N-Shar-ma** [smaranjitghose/doc2pen#974]
## Problem:
The steps section only mentions steps to use the editor page, which is incomplete, as the sketch and media manip pages are not mentioned

## Solution:
It can instead have the following content: (moved from the "What are we about" section above)

![image](https://user-images.githubusercontent.com/68962290/119566489-0eef3580-bd60-11eb-8703-fc488bef87c0.png)

The svgs can also be updated appropriately

**Comment by smaranjitghose** [comment]
Feel free to proceed @N-Shar-ma
